### PR TITLE
Implement clickable column headers on the users table

### PR DESCRIPTION
**Pull request by donker**
This PR allows the user to click on the three column headers to sort by them (DisplayName, Email and Joined Date). Clicking again will invert the sort order.

### CODE REVIEW

**Comment by mitchelsellers** [comment]
@donker @valadas I see this tagged as version 9.8.x as this is a new feature.  I think we could put in revision release, but adding the "On Hold" tag to prevent merging

**Comment by donker** [comment]
> 
> 
> @donker @valadas I see this tagged as version 9.8.x as this is a new feature. I think we could put in revision release, but adding the "On Hold" tag to prevent merging

I added it as I wanted to play it safe and have it on the list of new features for a minor release. But feel free to adjust.

**Review by valadas — APPROVED** [review]
Looks good to me and works great. Maybe as a future improvement we could add some sort indicators...

**Comment by valadas** [comment]
I am feeling pretty save getting this into 9.7.2 anyone against ?

**Pull request merged**
