### PR TITLE
Updated dependencies on dnn-resource-manager

### PR DESCRIPTION
**Pull request by valadas**
Fixes https://github.com/dnnsoftware/Dnn.Platform/issues/5290

The actual fix for the reported issue was done in https://github.com/DNNCommunity/dnn-elements/pull/579

This PR pulls in that new version and also updates the other dependencies on this project.

### CODE REVIEW

**Review by david-poindexter — APPROVED** [review]
Thanks @valadas 🎉

**Review by donker — APPROVED** [review]

**Review by mitchelsellers — APPROVED** [review]

**Review by bdukes — APPROVED** [review]

**Comment by bdukes** [comment]
Build error from second run:
image

**Pull request merged**
