### PR TITLE
Adjusts build scripts to build CKEditor

### PR DESCRIPTION
**Pull request by valadas**
This is a follow up PR on #4096 which merged CKEditor into this repository. This PR adjusts the build to no longer fetch it externally and build it as the rest of the project.

### CODE REVIEW

**Review by mitchelsellers — APPROVED** [review]

**Review by bdukes — APPROVED** [review]
I pushed one commit to add StyleCop.Analyzers to the `packages.config` for the CKEditorProvider.  Once the build is done this can be merged 👍🏻

**Comment by valadas** [comment]
@bdukes I thought we had a main packages.config and projects would just reference the common packages folder, am I wrong about that?

**Comment by bdukes** [comment]
Yeah, each package has its own `packages.config` file (except for the couple of newer projects that use `<ProjectReference />` inside the `csproj` file).  There's a shared `packages` folder in the root (next to the `sln`), but each project needs its own list of NuGet packages (in addition to the references).

**Comment by valadas** [comment]
Hmm, ok, thanks, I guess it makes sense if you only build one project. I thought for some reason there was a single packages.config to make it easier to bump dependency verisons...

**Pull request merged**
