### PR TITLE
Username is changed to email address in the user profile

### PR DESCRIPTION
**Pull request by mikebigun**
fixes https://github.com/dnnsoftware/Dnn.Platform/issues/2621

I didn't find any reason why we replace username in database on login event. There is a well-working mechanism to get user object by email, so then we use it's username property to authenticate it.

See demo: [demo](https://drive.google.com/file/d/1PMVgt31AbgT83WX8iKFopL_OUYjgTZyg/view?usp=sharing)

### CODE REVIEW

**Comment by mitchelsellers** [comment]
I believe that this was added to support a website switching from usernames to email as a username.

**Comment by daguiler** [comment]
Does it mean it was working as designed @mitchelsellers?

If not, and this can be fixed as Mike suggests, we can still include it in this final test round, meaning we could leave the release branch as target branch.

**Comment by bdukes** [comment]
Yes, the current behavior is how it was designed (whether that's the right design can be debated).

IMO, this is neither a showstopper nor a regression, and therefore shouldn't target the release branch.

**Comment by mikebigun** [comment]
I'm in curious of how then this setting expected to work. 
In a current design, there is only one way to switch this option ON, but switching it OFF will not lead to the username usage. Users still have to enter email addresses.
I mean, there should be some reason why don't keep both username and email in database. Why there should be replacement?

**Comment by valadas** [comment]
If I remember correctly, I submitted a fix a long time ago, even before the repo was on GitHub about this. The problem was like @mitchelsellers said that if you switch an existing site to use emails as usernames, the existing users could no longer login. There was also a related problem with duplicated emails already existing in the database when switching to that option. 

If memory serves good, you needed to first require unique emails and there would be a warning if there was duplicated emails, you needed to fix that to actually enable "require unique emails". Then you could only activate "emails as usernames" if "require unique emails" is on.

**Comment by valadas** [comment]
This was one related issue (not exactly this but it had some relation) https://dnntracker.atlassian.net/browse/DNN-5874

I cannot find the exact one for this actual issue but there are many logged here that relate to this https://dnntracker.atlassian.net/browse/DNN-20654?jql=text%20~%20%22email%20as%20username%22%20order%20by%20created%20DESC

**Comment by daguiler** [comment]
In any case I think you should re-target this PR to development branch @mikebigun

**Comment by mikebigun** [comment]
Team, many thanks for explanation. 
Is there way to re-target PR without its reopening?

**Comment by daguiler** [comment]
@mikebigun click on Edit next to the PR title and then a dropdown will show up below it for you to select a different base branch.

**Comment by mikebigun** [comment]
@daguiler done.

**Comment by daguiler** [comment]
Ok I don't think this played out well, I see unrelated changes now in this PR. Please close and open a new one @mikebigun.

**Comment by mikebigun** [comment]
Dear approves, I'm closing this PR in favor of https://github.com/dnnsoftware/Dnn.Platform/pull/2625
New PR is targeted to development branch.

**Pull request closed without merging**
