### PR TITLE
DNN-6760 - Added some links to resources that help you to contribute in ...

### PR DESCRIPTION
**Pull request by robsiera**
...the correct way.

### CODE REVIEW

**Comment by bdukes** [comment]
:+1: looks good to me

**Comment by cathalconnolly** [comment]
thanks - though I would inclined to remove the first two links and use http://www.dnnsoftware.com/wiki/page/github instead as it collates all the useful github links

**Comment by robsiera** [comment]
Ah, even better.

**Comment by jbrinkman** [comment]
@robsiera If you just update it in your DNN-6760 branch, it will automatically update the Pull Request and we can go ahead and merge the change.

**Comment by robsiera** [comment]
Don't hesitate to make the necessary linguistic improvements!

**Comment by cathalconnolly** [comment]
it just occurred to me that we have all the relevant information on the contributing page at https://github.com/dnnsoftware/Dnn.Platform/blob/master/CONTRIBUTING.md - but that some people are clearly not seeing it as they pull the development repo - perhaps a change to point to the contributing.md page would be good?

**Comment by cathalconnolly** [comment]
I've updated the wiki page to contain a link to the contributing.md, so I will merge this as is for 7.4.1 - thanks

**Comment by cathalconnolly** [comment]
Note: we don't require JIRA tickets for documentation updates , so if you have any future pull requests to do documentation/xml documentation tags, don't worry about creating a jira. I will merge this and mark the jira as complete - however @jbrinkman  may want to delete the jira as it doesn't correspond with a change in platform.

**Pull request merged**
