### PR TITLE
DNN-7813: support moving files between portals

### PR DESCRIPTION
**Pull request by sleupold**

### CODE REVIEW

**Comment by fjlucas** [comment]
@sleupold, there was an error in the script that breaks its execution, so I couldn't test it. Could you please fix and test it again? Once tested the filename should be renamed in order to avoid a conflict with the files in Platform, which already has a sqldataprovider file with that number. Thanks!

**Comment by sleupold** [comment]
@fjlucas , I fixed the typo, please try again

**Comment by sleupold** [comment]
renamed file to 08.00.00.23.sqldataprovider

**Comment by fjlucas** [comment]
Hi @sleupold, the resolution of the conflict of your last commit deletes the file '08.00.00.17.sqldataprovider' in Platform/development. It must be kept since contains new store procedures that are used in other parts of Platform.

Could you please fix this and try a clean instalation to be sure that everything works? Thanks

**Comment by sleupold** [comment]
fixed deleted file (adjusted formatting)
Both procedures have been tested locally.

**Pull request merged**
