### PR TITLE
DNN-7176: Fix data type

### PR DESCRIPTION
**Pull request by sleupold**
Make sure, compared value is of correct data type, use UniCode where appropriate

### CODE REVIEW

**Comment by zyhfish** [comment]
why there have CREATE, DROP, CREATE? maybe the first CREATE is no need.

**Comment by sleupold** [comment]
agreed

**Comment by cpaterra** [comment]
@zyhfish Can you please remove the initial create and merge this? Thanks.

**Comment by sleupold** [comment]
should the function stay inside DNN Core or be moved to SiteLog module repository (which is still empty)?

**Pull request closed without merging**
