### PR TITLE
Email Above Username in User.ascx.cs & Registration Form Issue #3371

### PR DESCRIPTION
**Pull request by thabaum**
Closes issue #3371
## Summary
Changed code to create email address field above Username on registration form and the User.ascx.cs file to match the User.ascx email order.

### CODE REVIEW

**Comment by thabaum** [comment]
I had made a note that Lines 219 &220 + 670 & 671  might be missing some characters but was just a github scroll issue I had made a note of in my code change.  It was cutting off the end of the lines but after going back to it they appeared ok.  

Let me know if I need to make any adjustments here.  Trying to move the email address above the Username here for the registration form.  I also noticed some of the code and css classes for the password strength here for possibly using with the text areas that may need it as a note.  Thank you!

**Comment by thabaum** [comment]
Any reason to close this PR?

**Comment by bdukes** [comment]
This needs to be resubmitted against the `develop` branch (`releaase/9.4.x` has been deleted).

**Comment by mitchelsellers** [comment]
@thabaum sorry about that, trying to clean things so that we don't lose PR's and this got caught in the crossfire

**Comment by thabaum** [comment]
OK thank you I see the 9.4.x was missing so that was throwing me off a bit.  I will redo these today thanks for the clarity and info @bdukes @mitchelsellers

**Comment by valadas** [comment]
@thabaum you can read a bit about our recent branching strategy cleanup in this PR:

https://github.com/dnnsoftware/Dnn.Platform/pull/3368/files

It simplifies a lot of stuff:
1. Most PRs will now come to the correct branch for the very next release
2. Issues will properly close when merging a PR to the default branch.
3. Less merge conflicts.
4. No longer a need to wait during RC stages before merging PRs for the next releases
5. Faster release cycles possible.
And many more.

**Pull request closed without merging**
