### PR TITLE
Fix some conflicts with ASP.NET dependencies

### PR DESCRIPTION
**Pull request by bdukes**
## Summary
The original PR #4716 missed a few pieces.

1) Need to include the WebMatrix DLLs in the new AspNetWebPages package, they were also updated.
2) Need to include DotNetNuke.Web.Mvc in the AspNetMvc package, since it relies on a particular version of MVC (another option would be adjusting the version range on the binding redirect, but that would only fix subsequent upgrades).
3) Move the HTTP module for MVC into the AspNetMvc package, since the pieces it relies on aren't included until after install.

### CODE REVIEW

**Comment by valadas** [comment]
Thank you soooo much for looking into this!

I will test a clean install and upgrade after it builds.
Just one little thing, where the removals of newlines in the comments in release.config and development.config intentional ?

**Comment by bdukes** [comment]
No, the whitespace changes were done automatically by my editor, I've reverted those changes.

**Comment by david-poindexter** [comment]
I'll be on my computer again in a bit - I can also do a test as soon as the build finishes.

**Comment by bdukes** [comment]
I successfully installed the package and successfully upgraded from 9.9.1

**Comment by david-poindexter** [comment]
Awesome @bdukes - I just downloaded and will test as well.

**Review by david-poindexter — APPROVED** [review]
Woo hoo - great success!  Thank you @bdukes 🎉

**Review by valadas — APPROVED** [review]
Awesome, a clean install worked fine for me too.

**Pull request merged**
