### PR TITLE
Upgrade Yarn to 3.4.1

### PR DESCRIPTION
**Pull request by bdukes**
This may fix the build failure of #5568

### CODE REVIEW

**Comment by david-poindexter** [comment]
Looks like the build failed here too.  These gremlins!  ☹️

**Comment by valadas** [comment]
Yeah, it probably has to do with Webpack v4 and Node v18. And wndows-latest runners got upgraded to Node v18 since it went LTS. I'll try to take a look at that problem this weekend.

**Review by david-poindexter — APPROVED** [review]
Assuming #5570 resolves the build issues, I still think this PR good to roll in.  Thanks @bdukes

**Review by valadas — APPROVED** [review]
Looks good to me too @bdukes feel free to either merge knowing that the build issues is unrelated to this change, or if you want to make sure it works fine in CI, you could review/merge #5570 and then rebase this one on it to double-check...

**Pull request merged**
