### PR TITLE
DNN-22201: release write lock as well.

### LINKED ISSUE #2231: Sometimes search result will be empty in azure instances
DotNetNuke.Services.Search.Internals.LuceneControllerImpl - Lucene.Net.Store.AlreadyClosedException: this IndexReader is closed
at Lucene.Net.Index.IndexReader.EnsureOpen()
at Lucene.Net.Index.DirectoryReader.DoReopen(Boolean openReadOnly, IndexCommit commit)
at DotNetNuke.Services.Search.Internals.LuceneControllerImpl.InstantiateReader()
at DotNetNuke.Services.Search.Internals.LuceneControllerImpl.GetSearcher()
at DotNetNuke.Services.Search.Internals.LuceneControllerImpl.Search(LuceneSearchContext searchContext, Int32 retryTimes)

### PR DESCRIPTION
**Pull request by zyhfish**
fixes #2231

### CODE REVIEW

**Comment by mitchelsellers** [comment]
Can we get some detail as to what this change is, and why this change is necessary?  There is no link to an issue or detail here.

**Comment by zyhfish** [comment]
this is for issue #2231 , thx

**Comment by zyhfish** [comment]
Hi @tpluscode , this need update after PR #2248 merged.

**Comment by zyhfish** [comment]
Hi @tpluscode , the conflict should resolved automatically after DNN-21973 merged, please confirm, thx

**Comment by tpluscode** [comment]
Well indeed, not more conflict. Thanks @zyhfish

**Pull request merged**
