### PR TITLE
DNN-8940: Module online help could not be displayed due to wrong iframe markup

### PR DESCRIPTION
**Pull request by roman-yagodin**
This will fix DNN-8940 by adding closing tag for generated iframe markup.

### CODE REVIEW

**Comment by galatrash-at-dnn** [comment]
@roman-yagodin , please provide more information for QA testers to be able to reproduce and validate this issue properly.

**Comment by roman-yagodin** [comment]
@galatrash-at-dnn, can you please clarify, what information is required?

**Comment by galatrash-at-dnn** [comment]
The QA tester workin g on this needs a clear description of how to test this issue (how to reproduce) before the fix was applied (in old releases) and after the fix was implemented (in the upcoming release).

**Comment by roman-yagodin** [comment]
https://dnntracker.atlassian.net/browse/DNN-8940?focusedCommentId=139898&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-139898

**Pull request merged**
