### PR TITLE
Fixed issue where the uninstall extension shows version 0.0.0

### LINKED ISSUE #3778: Uninstall extension shows version 0.0.0 i.s.o. the real version
## Description of the bug
If you uninstall an extension, the version number in the confirmation box shows 0.0.0 i.s.o. the real version number.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Install an extension
2. If the install is ready, Uninstall the same extension
3. Version 0.0.0 is shown

See screenshot:
image

## Current behaviour
Show 0.0.0

## Expected behavior
Show the real version #

## Screenshots
See above

## Additional context
Small test extension attached.
[DNN Package test-1.zip](https://github.com/dnnsoftware/Dnn.Platform/files/4669475/DNN.Package.test-1.zip)

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.06.01 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

### PR DESCRIPTION
**Pull request by Mostafa-Moafi**
Fixes #3778

## Summary
In the delete extensions PersonaBar, the version of the module is not displayed and I fixed that problem

## How to test 
please go to delete the extension in PersonaBar

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dnnsoftware/Dnn.Platform?pullRequest=5285) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dnnsoftware/Dnn.Platform?pullRequest=5285) before we can accept your contribution.<br/><br/>:x: Mostafa-Moafi [sign now](https://cla.dotnetfoundation.org/dnnsoftware/Dnn.Platform?pullRequest=5285)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dnnsoftware/Dnn.Platform?pullRequest=5285) it.</sub>

**Review by valadas — APPROVED** [review]
Looks good to me, version here is a string and has no `value` property, I also tested this and it works.

Thanks for your first contribution!

**Comment by valadas** [comment]
I just going to change your PR message from `Fix Bug #3778` to `Fixes #3778` as this will automatically close the issue when this PR gets merged as per https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Review by valadas — APPROVED** [review]

**Comment by Mostafa-Moafi** [comment]
Thank you too.
I'm too happy about the first contribution.
This issue in which version release?
@valadas

**Comment by valadas** [comment]
It is slated for v9.11.1 if we do make another path release for 9.11.x if we don't then it will go in v10.0.0

**Pull request merged**
