### PR TITLE
Fix localizing parent tabs breaking existing localized child tabs

### LINKED ISSUE #5383: Localized child pages don't get deleted correctly if parent pages have localization added after they were created
## Description of bug

_Requires the localization module_
Localized child pages don't get deleted correctly if parent pages have localization added after they were created.

Ordinarily whenever a new localized child page is added, it is linked to the corresponding localized version of its parent page:

```
In TabController.CeateLocalizedCopyInternal:
                // Get the original Tabs Parent
                // check the original whether have parent.
                if (!Null.IsNull(originalTab.ParentId))
                {
                    TabInfo originalParent = this.GetTab(originalTab.ParentId, originalTab.PortalID, false);

                    // Get the localized parent
                    TabInfo localizedParent = this.GetTabByCulture(originalParent.TabID, originalParent.PortalID, locale);
                    localizedCopy.ParentId = localizedParent.TabID;
                }
```

But if you create a parent page, make it non-localized, add localized children, and then localize the parent the child pages aren't updated to have their corresponding localized parent.

We have found one particular thing that this breaks, but there are probably more:

If you then delete the localized child page, it will mark both child pages as deleted in the database, but only the original localization of the child page will show up in the recycle bin (note that you have to switch locales with the locale selector to see correctly deleted localized pages in the recycle bin).

## Steps to reproduce

<ol>
<li>Update site language settings:
<ol>
 
<li>Go to Settings -> Site Settings -> Languages tab
 
<li>If only English (United States) language is present in the Languages list  
<ol>
  
<li>Click Add New Language
  
<li>Select English (CAN)
  
<li>Click Save button

<ol>
 
<li>If the “Allow Content Localization” option is not on:  
<ol>
  
<li>Turn it on
  
<li>Click the newly shown Enable Localized Content button 
  
<li>In the new panel, turn on the “Make All Pages Translatable” switch
  
<li>Click Enable Localized Content button
  
<li>Wait until all pages have been processed 

</li>  
</ol>
</li>  
</ol>
</ol>
</ol>

<li>Add a parent page 
<ol>
 
<li>Go to Content -> Pages
 
<li>Click Add Page button
 
<li>Give it the name and title: “Parent page”
 
<li>Click Add Page button at the bottom
 
<li>Click Publish at the bottom right
 
<li>Go back to Content -> Pages, and select the Parent Page
 
<li>Click on the new Localization tab
 
<li>Click the “Make Page Neutral” button at the bottom left, and Click Yes to confirm deletion of localized pages if they exist
</li> 
</ol>

<li>Add a child page 
<ol>
 
<li>Go to Content -> Pages
 
<li>Select Parent Page in the list on the left
 
<li>Under … menu of the parent page, click Add Page option
 
<li>Give it “Child Page” name
 
<li>Click “Add Page” at the bottom, and then “Publish” button on the main page
</li> 
</ol>

<li>Localize the child page 
<ol>
 
<li>Go to Content -> Pages and select the child page in the list on the left
 
<li>Click the new Localization tab
 
<li>Click “Add Missing Languages” button
 
<li>Add a suffix to the pages titles / names (us / ca), just to easily distinguish them
 
<li>Click Update Localization button, and confirm by clicking Continue
</li> 
</ol>

<li>Localize the parent page 
<ol>
 
<li>Go to Content -> Pages and select the parent page
 
<li>In the Localization tab, click Make Page Translatable button
 
<li>Add us/ca suffixes to US and CAN versions titles / names
 
<li>Click Update Localization button, and Continue
</li> 
</ol>

<li>Delete the child page 
<ol>
 
<li>Go to Content -> Pages and select the child page
 
<li>Click Delete button at the bottom and confirm with Delete button in the popup
</li> 
</ol>

<li>Go to Content -> Recycle Bin

<li>The US Child page should be present in the bin

<li>Change language to English (Canada) at the top of the page

<li>Go to Content -> Recycle Bin. The bin is empty

<li>Switch back to English (US) in the top
<li>Go to Content -> Recycle Bin, and empty the bin.

<li>Now both the US and Canada language Recycle Bins are empty but if you check the Tabs table in the database, the US version of the page is deleted, but a zombie version of the Canada page is still there.

</ol>

## Current behavior

When a nonlocalized parent with localized children has localization added, the localized children are not updated to point to their localized parents. This means that deleted localized children without the default language do not show up in the recycle bin.

## Expected behavior

When a nonlocalized parent with localized children has localization added, the localized children should be updated to point to their localized parents.

When the child page is then deleted, all localized children should show up in their corresponding localized recycle bin.

## Screenshots

Localized child page remains attached to default localization parent page in database:
image

Should actually be attached to the localized version of its parent page:
image

US recycle bin

image

Switching with language selector:
image

CA recycle bin - empty:

image

## Affected version
Reproducible on any remotely modern version.

* [X] 10.00.00 alpha build
* [X] 09.11.00 release candidate
* [X] 09.10.02 release candidate
* [X] 09.10.01 latest supported release

## Affected browser
Any - is a server side issue

### PR DESCRIPTION
**Pull request by mwigley-trilogy**
Fix localizing parent tabs breaking existing localized child tabs by updating the child->parent tab links when localizing parent tabs.

Closes #5383

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dnnsoftware/Dnn.Platform?pullRequest=5382) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dnnsoftware/Dnn.Platform?pullRequest=5382) before we can accept your contribution.<br/><br/>:x: mwigley-trilogy [sign now](https://cla.dotnetfoundation.org/dnnsoftware/Dnn.Platform?pullRequest=5382)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dnnsoftware/Dnn.Platform?pullRequest=5382) it.</sub>

**Comment by mitchelsellers** [comment]
@mwigley-trilogy Can we get details on the recreation steps, and what was the actual issue in this situation that is being resolved.

**Comment by mwigley-trilogy** [comment]
Ah, sorry @mitchelsellers! I just realised that that I just created this PR in the public repo, I'll close this PR and remake once I've created an issue with repro steps.

**Comment by mitchelsellers** [comment]
No need to close @mwigley-trilogy just add the issue with detail and we can review!

**Comment by mwigley-trilogy** [comment]
This fixes: https://github.com/dnnsoftware/Dnn.Platform/issues/5383

By the way, I'm getting an error when trying to sign the contributor license agreement.  Any idea how to resolve?
image

**Comment by valadas** [comment]
@mitchelsellers I have some info about a possible cla bot being broken, ping me up when able...

**Review by valadas — APPROVED** [review]
Thanks for the detailed issue, really helped understand the issue and the fix.
This PR makes sense to me.

**Review by v-karbovnichy — APPROVED** [review]

**Review by mitchelsellers — APPROVED** [review]

**Comment by valadas** [comment]
@mwigley-trilogy There appears to be a temporary issue with the CLA bot at the moment, we contacted .Net Foundation and are just waiting on a reply/fix... Quick question, usually when one goes there for the first time, they get a first view and a button to login to github to then continue on to the signing part.
Do you see that error before or after the github login button is clicked ?

**Comment by mwigley-trilogy** [comment]
@valadas Today I'm getting this:

image

click ->

image


Yesterday I got the authorise app confirmation part and approved it.

Yesterday I got a few different errors, initially I got an error straight away on clicking the 'sign now' link, later I got the 'sign with github' button and could authorize the integration, and could fill out the part of the form that approved access, but then got an error when clicking the sign button.  So in summary I think I've seen an error at each point in the process :)

**Comment by mitchelsellers** [comment]
@mwigley-trilogy Are you an Employee of IgniteTech/DNNSoftware/Whatever level of the company

**Comment by mwigley-trilogy** [comment]
@mitchelsellers Yes, I'm a new VP of Software Engineering for Trilogy

**Comment by mitchelsellers** [comment]
@mwigley-trilogy Thank you for your contributions first of all, secondly, we will accept your PR's for now given your status as we work through the CLA bot issues with the .NET Foundation and will get you signed in the coming days.

@valadas keep me updated on the CLA bot stuff.

**Pull request merged**
