### PR TITLE
Dnn-3522: If-tokens in DDRmenu templates fail

### PR DESCRIPTION
**Pull request by ohine**
The token template processor would only check for true/false values (0, 1). Added a super ugly check if they're not 0 or 1 and also not an empty string. It seems to solve the issue with checking for icons or any other string node via the ddr token text template.

### CODE REVIEW

**Comment by KenGrierson** [comment]
Hi Oliver
Can you provide an example use case for this fix?
I've tried adding the page icon definition in the JIRA but I don't get any change after I've done that and recycled the AppPool from the Toolbar

Thx,
Ken

**Comment by ohine** [comment]
The ddr menu template needs to be modified to include the page icon token. Then need to modify the page settings and select icons for the page. Let me know if you are still having issues, and I can try and package up my test skin to the jira ticket.

**Comment by cathalconnolly** [comment]
QA still reports issues with missing images in the JIRA - https://dnntracker.atlassian.net/browse/DNN-3522 . As we are closing the release today, I am going to revert this back, and we can then resolve it in 7.4.2 i.e. see if the issue is in our setup, or perhaps a bug in the pull request.

**Comment by cathalconnolly** [comment]
QA now reports they have this working, so I will leave everything as is.

**Pull request merged**
