### PR TITLE
Feature/5101 ck editor option to resize images on upload

### LINKED ISSUE #5101: CKEditor option to resize images on upload
## Description of problem
Administrators still used to the RadEditorProvider are missing the option to specify a maximum size for images in the Editor Provider Settings. Since images from phones are getting larger and larger, and users tend to upload images straight from their device, people are very much used to the convenience of the RadEditor to resize the images to a certain maximum size on upload.
This is keeping sites from being upgraded to the latest version of DNN, with CKEditorProvider, or at least keeps them from removing Telerik.

## Description of solution
The CKEditor Provider settings should get an extra option for maximum height and width of images being uploaded. On upload images larger than these dimensions need to be automatically resized to fit within those dimensions.

## Description of alternatives considered
It would also be possible to check for maximum dimensions and present the user with an error, but that would be inacceptable from a UX point of view. Users should not have to worry about the resizing for a maximum size. Users needing more control (e.g. on quality) will know how to resize themselves, but most users won't care.

## Screenshots
image

## Additional context
A PR is being worked on

## Affected browser
Not browser related

### PR DESCRIPTION
**Pull request by skamphuis**
Closes #5101 
This PR is built on PR #5122 which was submitted for #5100, but is not necessarily related.

## Summary
This PR adds settings for:
* Image Resize Width On Upload
* Image Resize Height On Upload
And will resize any uploaded image to fit within these dimension on upload.

Since pictures are becoming larger and larger, it can be important on many portals, to have this automatic resize option, to allow users uncapable of resizing images themselves, to upload reasonably sized images.
image

### CODE REVIEW

**Review by donker — APPROVED** [review]
Looks good to me but not sure how this works with the other PR with regards to merge conflicts.

**Comment by skamphuis** [comment]
> Looks good to me but not sure how this works with the other PR with regards to merge conflicts.

Thanks, I have been wondering that too, but given the fact that the changes from #5122 are also shown in the changes here, it looks like the easiest thing would be to just merge this one.
The reason I made two, was that I assumed one PR for 2 issues wouldn't be the right either...

**Comment by david-poindexter** [comment]
Just chiming in on the logistics of the "stacked commits".  We can still manage these PRs independently.  The branch for this PR will just need to be rebased once #5122 is merged.

**Comment by valadas** [comment]
I agree, let's resolve #5122 and come back to this one, happy to help with the rebase if any conflicts arise.
@skamphuis I guess here you started this branch from the other branch instead of starting over from fresh develop.

**Comment by skamphuis** [comment]
I merged the most recent develop branch into this one before crafting the pull request, so merging should be fairly easy and without conflicts?

**Comment by skamphuis** [comment]
> @skamphuis I guess here you started this branch from the other branch instead of starting over from fresh develop.

It seemed to me that both would be more related than they actually turned out be.

I appreciate all your (and @donker , @david-poindexter ) efforts to get this merged in, by the way.

**Comment by valadas** [comment]
@skamphuis looking at the conflicts did you:

A: use different variable names on the 2 PRs ?
B: They represent 2 different things and they are both to keep ?

image

Sorry, I am not super familiar here with all the possible settings in this area :)

**Comment by skamphuis** [comment]
> @skamphuis looking at the conflicts did you:
> 
> A: use different variable names on the 2 PRs ?
> B: They represent 2 different things and they are both to keep ?
> 
> image
> 
> Sorry, I am not super familiar here with all the possible settings in this area :)

B.
I introduced the ...OnUpload field to specify the size to resize to in upload. The other ones already existed and specify the default size for the Resize option in the image browser.

**Comment by skamphuis** [comment]
@valadas I obviously messed up trying to rebase this thing on release/9.11.0 as there are now a **lot** of changed files.

Do you have any advice?

**Comment by valadas** [comment]
Not knowing what went wrong, it's hard to advise on it. But above you have the list of commits, if you know the ones that should be part of this unit of work, you can copy their hash code, create a new clean branch based on release/9.11.0 and then cherry-pick those hashes into it to redo a new pr.  https://git-scm.com/docs/git-cherry-pick

**Comment by valadas** [comment]
Not knowing what went wrong, it's hard to advise on it. But above you have the list of commits, if you know the ones that should be part of this unit of work, you can copy their hash code, create a new clean branch based on release/9.11.0 and then cherry-pick those hashes into it to redo a new pr.  https://git-scm.com/docs/git-cherry-pick

**Comment by skamphuis** [comment]
> Not knowing what went wrong, it's hard to advise on it. But above you have the list of commits, if you know the ones that should be part of this unit of work, you can copy their hash code, create a new clean branch based on release/9.11.0 and then cherry-pick those hashes into it to redo a new pr. https://git-scm.com/docs/git-cherry-pick

That turned out to be easier than I thought. New PR is #5128 . I'll close this one.
Thanks.

**Pull request closed without merging**
