### PR TITLE
Adjust labels used by dependabot

### PR DESCRIPTION
**Pull request by bdukes**
## Summary
This adjusts the Dependabot config to add the following labels to all dependency PRs:

* [_Type: Maintenance_](https://github.com/dnnsoftware/Dnn.Platform/labels/Type%3A%20Maintenance)
* [_Priority: Low_](https://github.com/dnnsoftware/Dnn.Platform/labels/Priority%3A%20Low)
* [_Status: Testing_](https://github.com/dnnsoftware/Dnn.Platform/labels/Status%3A%20Testing)

It also adds [_Type: Build/Release_](https://github.com/dnnsoftware/Dnn.Platform/labels/Type%3A%20Build%2FRelease) to PRs for GitHub Actions updates.

Let me know if any of those don't make sense to y'all and we can adjust or remove.  Thanks!

### CODE REVIEW

**Comment by david-poindexter** [comment]
Thanks @bdukes - I would recommend sticking with just the `Type: ...` label.  The other ones are more for issues than PRs.

**Review by david-poindexter — CHANGES_REQUESTED** [review]
Thanks @bdukes - I would recommend sticking with just the `Type: ...` label.  The other ones are more for issues than PRs.

**Comment by bdukes** [comment]
Thanks for the feedback @david-poindexter, I've made that adjustment 👍🏻

**Review by valadas — APPROVED** [review]
I had the same thought as @david-poindexter , so it now looks good to me

**Review by mitchelsellers — APPROVED** [review]

**Comment by valadas** [comment]
> Thanks @bdukes - I would recommend sticking with just the `Type: ...` label. The other ones are more for issues than PRs.

@david-poindexter good to go with the changes ?

**Pull request merged**
