### PR TITLE
Merge 9.4.x to development

### PR DESCRIPTION
**Pull request by bdukes**
@mitchelsellers used a squash on #3189, but we need a merge commit to connect the commits into both branches.  This PR includes a merge commit (and still needs to be approved/integrated via merging), and also happens to fix a merge conflict we missed in `.github/ISSUE_TEMPLATE/bug-report.md`

### CODE REVIEW

**Comment by mitchelsellers** [comment]
My Bad!

**Comment by mitchelsellers** [comment]
@bdukes You ok with me "Merge Committing" this as an admin function to fix this

**Comment by bdukes** [comment]
yup! thanks, @mitchelsellers

**Comment by valadas** [comment]
Do I need to do something or is this good to go now?

**Comment by valadas** [comment]
@bdukes in general we should not use "Squash and merge", only if the commits are really too granular for a single thing we would use that right?

**Comment by bdukes** [comment]
In general, squash or rebase are both fine (and, yes, the difference between them would be how important the individual commits are).  But when we're copying commits from one long-lived branch to another long-lived branch, that's when a merge commit is important.

**Pull request merged**
