### PR TITLE
Fixes 2 wrong merged conflicts resolutions

### PR DESCRIPTION
**Pull request by valadas**
That prevented the buid from running

### CODE REVIEW

**Comment by valadas** [comment]
@david-poindexter @donker 

I found the build issue, if you guys want to try again.

**Comment by david-poindexter** [comment]
Thank you @valadas

**Comment by valadas** [comment]
I am going to merge this now since @donker is probably asleep and it's pretty much just us 3 working in this area so it will unblock us and the whole branch will be reviewed later anyway when we merge that into develop.

**Comment by david-poindexter** [comment]
Weird - tried to review, but couldn't approve

**Comment by david-poindexter** [comment]
Oh - you merged!  Lol 😂

**Pull request merged**
