### PR TITLE
Fix Typo "Frind" to "Friendly issue #3233

### PR DESCRIPTION
**Pull request by thabaum**
To fix following issue

https://github.com/dnnsoftware/Dnn.Platform/issues/3233

### CODE REVIEW

**Comment by thabaum** [comment]
Can I move the target up on the one that was already approved as well?

**Comment by david-poindexter** [comment]
> Can I move the target up on the one that was already approved as well?

I’m sorry, I don’t know what you mean.

**Comment by thabaum** [comment]
Well I am just setting pull requests to development because I dont see the branch to set it to.   Is it release/9.4.x ?  I am a bit confused here still.  Although I did make an issue then the PR this time.

**Comment by thabaum** [comment]
OK Nevermind I do understand.  I guess my question was if I can change the last PR that was already approved and is in version 10.  I wonder if more can be moved to 9.4.x

**Comment by thabaum** [comment]
https://github.blog/2016-08-15-change-the-base-branch-of-a-pull-request/
found my solution. I hope that did it.

**Comment by bdukes** [comment]
@thabaum since your change was done on `development`, switching the PR against `release/9.4.x` brings all of the changes from `development` along with it.  I rebased your change onto `release/9.4.x`, so this should be correct now.  Thanks!

**Comment by valadas** [comment]
Quick note guys, don't forget the set the milestone when you merge PRs :)

**Comment by david-poindexter** [comment]
Sorry @valadas - that was my fault.

**Pull request merged**
