### PR TITLE
DNN-7245: Fix PurgeSiteLog to remove site log records even if portal's SiteLogHistory is set to 0

### PR DESCRIPTION
**Pull request by janjonas**
See https://dnntracker.atlassian.net/browse/DNN-7245

### CODE REVIEW

**Comment by jbrinkman** [comment]
@janjonas We won't accept this into the platform as we are removing SiteLog from the platform.  I'll incorporate it into the Forge project we are creating for SiteLog so that we don't lose the capability.

**Comment by janjonas** [comment]
@jbrinkman: Maybe you can merge this into 7.4.2 if this branch has not already been "freezed".

**Comment by jbrinkman** [comment]
I can't commit to getting it into 7.4.2.  We are already past freeze date, but things are a little fluid at the moment so I might be able to get one or two more items included.

**Comment by ohine** [comment]
:+1:

**Comment by francescorivola** [comment]
hi folks, I am going to close this pull request. We have created a clone PR in the Site Log repository https://github.com/DNNCommunity/Dnn.SiteLog/pull/2.

**Pull request closed without merging**
