### PR TITLE
Add UI to Manage Google Analytic Tracking Code

### LINKED ISSUE #2129: Bring back a basic Google Analytics UI
## Description 
Previously, Dnn had a module to configure google analytics tracking code. I _think_ all the necessary code is still in place and that it is just a matter of writing the code in a config file to have it working. I _think_ this would just be missing the UI to actually set the google analytics tracking account id.

## Steps to reproduce
Try to enter the google analytics tracking account id.

## Current result
There is no UI to do it

## Expected result
Users should be able to enter their tracking id and have basic google analytics working on their site.
Currently, they need to resort to injecting javascript or using a third party module.

## Affected version

* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

This I think should be implemented with just the basic account id, nothing more than what was provided in older versions because commercial editions have more advanced google analytics management.

### PR DESCRIPTION
**Pull request by mikesmeltzer**
Closes #2129 

## Summary
Added a new Connector extension project to the solution called DNN.GoogleAnalyticsConnector.

The connector adds the previously removed fields for managing the Google Analytic fields that were previously exposed in the Platform in prior versions of DNN. The fields should match the fields that were in DNN 8.0.4.

The connector also adds a new button for deactivating the analytic codes. This button is visible only when an analytics code is saved. Behind the scenes, this behaviour only clears the fields for the GA provider which is turn prevents the provider from writing code to the page. This isn't, however, a true deactivation of the GA Http Module and site analytics config.

Validation was added to verify that the Google Analytics tracking code is not empty.

## How to Test

On an existing site that is using the core Google Analytics provider, you should be able to view and edit the previously defined tracking code settings. These settings are stored at the root of each portal folder within the GoogleAnalytics.config file.

On a new installation, you should be able to fill out the tracking code details and have them reflected within the page source after saving the screen. Additionally, the GoogleAnalytics.config file should now be visible on the root of the portal in question with the proper settings added to it.

After saving the tracking code, try deleting it and re-adding,etc.

## Known Issues

1. What I perceive to be a workaround for the showing/hiding the Delete Connection button was implemented due to some shortcomings in the connectors extension.  This has been indicated with comments in both the C# and JS.

2. Pressing cancel after the connector has been saved will make it appear that it is no longer saved.  This appears to be an issue with the core connectors extension. Another issue will be created to review the connectors extension in general.

### CODE REVIEW

**Comment by mikesmeltzer** [comment]
Mitch,

In its current state, and with DNN 8.0.4, you could remove the tracking code and save which would essentially disable the functionality.

To make that more clear, we could add some messaging to the screen to indicate how to disable it.

Thoughts?

**Comment by mitchelsellers** [comment]
@mikesmeltzer THat might be good enough, I guess from what I remember if you remove the code, the script is still rendered on-page which is what I was hoping to avoid.

**Comment by mikesmeltzer** [comment]
Let me double check if that completed removes it.  If not, maybe I can add a checkbox or something else to disable it entirely.

My intent was like for like with what we had in the last version but if we can do a bit of a value add to then that is great.

**Comment by pjkruger** [comment]
@mikesmeltzer and @mitchelsellers,  are there any plans to integrate Google Tag Manager (GTM) as well?

**Comment by mikesmeltzer** [comment]
Mitchel,




I have some pending changes that I haven't committed yet based on the last round of feedback.




Please hold off on merging this until I push those.  I'm currently out of the country and will touch base in a few days.




Thanks,




Mike




Get Outlook for Android







From: Mitchel Sellers


Sent: Thursday, September 13, 10:25 PM


Subject: Re: [dnnsoftware/Dnn.Platform] Add UI to Manage Google Analytic Tracking Code (#2288)


To: dnnsoftware/Dnn.Platform


Cc: Mike Smeltzer, Mention






@mitchelsellers approved this pull request.


This appears to be working as the old one was working

**Comment by ohine** [comment]
@mikesmeltzer No worries, we will hold off on merging till you let us know it's all set. Hopefully we can get it merged in before the first week of October so it can make it into the v9.3.0 release.

**Comment by mitchelsellers** [comment]
@mikesmeltzer Do you have an ETA on the final changes?

**Comment by mikesmeltzer** [comment]
I anticipate doing another commit today.  The delete / remove analytics functionality has been added and now I'm just in the process of some final testing.

**Comment by mitchelsellers** [comment]
@mikesmeltzer Awesome!

**Pull request merged**
