### PR TITLE
Migrate WebRequestCachingProvider to open source

### LINKED ISSUE #2634: Migrate WebRequestCachingProvider to open source
Migrate WebRequestCachingProvider to open source.
Migrate web monitor scheduled task as well.

### PR DESCRIPTION
**Pull request by zyhfish**
Fix #2634 .

### CODE REVIEW

**Comment by ashishpd** [comment]
This needs to be closed as we have not decided yet on this. It's a communication issue on ESW side. Sorry about that.

**Comment by hismightiness** [comment]
Wasn't this already promised at DNN Summit 2018?

**Comment by ohine** [comment]
Same issue with Liquid Content. It’s been communicated multiple times it would be in the platform. It’s really getting quite annoying the back and forth on these features.

**Comment by nvisionative** [comment]
Yes, you are 100% correct @hismightiness and @ohine - nothing but empty promises, ☹️

**Pull request closed without merging**
