### PR TITLE
Related to Issue 2249: "There are references to www.dotnetnuke.com in text"

### PR DESCRIPTION
**Pull request by VashJuan**
This does not (yet) resolve "There are references to www.dotnetnuke.com in text #2249", but started as a way to remove some of the superfluous mentions of dotnetnuke in the code base.

WARNING: This is my first commit/pull request, so be suspicious and feel free to ask questions! (That's also why issue #2249 is not noted in the commit message.)

## Summary
The issue got me started replacing DotNetNuke with DNN through the code base - though I've yet to tackle the files actually mentioned in the issue! (I'll edit those SqlDataProvider scripts in a separate salvo in some weeks.) 

I largely modified comments, updating the various copyright statements and making them consistent. I did not verify those changes with Corp legal, but they do seem common sense to me.

However I did edit some instances of old URL's, some output strings, some licenses, and assembly 'owner' fields. I believe these changes should not break any code, but they might break some tests that look for the old strings possibly. (I've not tryed rebuilding the platform as I don't know how yet.)

Thus I'd not suggest grabbing these changes until starting in on the next version - 9.4 (or 9.3.1).

### CODE REVIEW

**Comment by VashJuan** [comment]
OK, indeed some test results need adjusting. Where to do that????

2019-01-26T19:42:06.7016263Z Failed   HtmlUtils_CleanWithTagInfo_Should_Return_Clean_Content_Without_Attribute_Values
2019-01-26T19:42:06.7016426Z Error Message:
2019-01-26T19:42:06.7016575Z    Expected string length 67 but was 60. Strings differ at index 52.
2019-01-26T19:42:06.7016749Z   Expected: "...World This is a sample HTML text for testing DotNetNuke Corp "
2019-01-26T19:42:06.7016907Z   But was:  "...World This is a sample HTML text for testing DNN Corp "
2019-01-26T19:42:06.7017084Z   ------------------------------------------------------------^
2019-01-26T19:42:06.7017205Z 
2019-01-26T19:42:06.7017355Z Stack Trace:
2019-01-26T19:42:06.7017539Z at DotNetNuke.Tests.Core.Services.HtmlUtilsTests.HtmlUtils_CleanWithTagInfo_Should_Return_Clean_Content_Without_Attribute_Values() in D:\a\1\s\DNN Platform\Tests\DotNetNuke.Tests.Core\Services\HtmlUtilsTest.cs:line 97
2019-01-26T19:42:06.7017941Z 
2019-01-26T19:42:06.7018056Z 
2019-01-26T19:42:06.7018218Z Failed   HtmlUtils_StripUnspecifiedTags_Should_Not_Return_Attribute_Values
2019-01-26T19:42:06.7018361Z Error Message:
2019-01-26T19:42:06.7018530Z    Expected string length 67 but was 60. Strings differ at index 52.
2019-01-26T19:42:06.7019089Z   Expected: "...World!This is a sample HTML text for testing!DotNetNuke Corp."
2019-01-26T19:42:06.7019325Z   But was:  "...World!This is a sample HTML text for testing!DNN Corp."
2019-01-26T19:42:06.7019544Z   ------------------------------------------------------------^
2019-01-26T19:42:06.7019701Z 
2019-01-26T19:42:06.7019883Z Stack Trace:
2019-01-26T19:42:06.7020115Z at DotNetNuke.Tests.Core.Services.HtmlUtilsTests.HtmlUtils_StripUnspecifiedTags_Should_Not_Return_Attribute_Values() in D:\a\1\s\DNN Platform\Tests\DotNetNuke.Tests.Core\Services\HtmlUtilsTest.cs:line 130
2019-01-26T19:42:06.7020321Z 
2019-01-26T19:42:06.7020451Z 
2019-01-26T19:42:06.7020624Z Failed   HtmlUtils_StripUnspecifiedTags_Should_Return_Attribute_Values
2019-01-26T19:42:06.7020843Z Error Message:
2019-01-26T19:42:06.7021042Z    Expected string length 259 but was 252. Strings differ at index 52.
2019-01-26T19:42:06.7021236Z   Expected: "...sample HTML text for testing!DotNetNuke Corp. "HappyFaceAl..."
2019-01-26T19:42:06.7021469Z   But was:  "...sample HTML text for testing!DNN Corp. "HappyFaceAlt" "Hap..."
2019-01-26T19:42:06.7021657Z   --------------------------------------------^
2019-01-26T19:42:06.7021818Z 
2019-01-26T19:42:06.7021977Z Stack Trace:
2019-01-26T19:42:06.7022345Z at DotNetNuke.Tests.Core.Services.HtmlUtilsTests.HtmlUtils_StripUnspecifiedTags_Should_Return_Attribute_Values() in D:\a\1\s\DNN Platform\Tests\DotNetNuke.Tests.Core\Services\HtmlUtilsTest.cs:line 114
2019-01-26T19:42:06.7022483Z

**Comment by VashJuan** [comment]
I think updating test results was easy, and adding the latest commit to this pull request, and having the build kick off again: I like this!

**Comment by mitchelsellers** [comment]
Thanks for this awesome contribution!  

@dnnsoftware/tag-group How do we want to handle reviewing this?  The changes are mostly to metadata only elements?

**Comment by VashJuan** [comment]
Just doing a fresh install of DNN 9.3.0 build 284 (~last night) and see in the status bar that cdn.dotnetnuke.com is still active. My commit changes that to cdn.dnnsoftware.com I'm sure. Are both good perchance?

**Comment by ohine** [comment]
@VashJuan, I apologize for that, because we're in the middle of an RC period, the CI system is only configured to produce RC builds at this time. We were going to discuss this at our meeting last week, but we ran out of time due to other issues taking up more time then they were allotted. Hopefully the next meeting will stay more on agenda and we will be able to discuss the CI issues and work towards a solution that will work with both the main development branch and our release candidate process.

**Comment by mitchelsellers** [comment]
@VashJuan We will need to confirm on that one.  @ashishpd do you have a way to verify domain names?

**Comment by VashJuan** [comment]
All the edits only took like 3 hours to make, so it may be simpler to have someone knows what the code base better repeat my work - I certainly won't be offended. That said, all the cdn.dnnsoftware.com references are only in Build/Deploy TBEX.xml - which deserves a close review anyway, and Website\Install\InstallWizard.aspx. Another URL I assumed has moved is the Update Service at update.dnnsoftware.com, referred to in 3 files: dev & release.config and Application.cs.

I don't recall much else that looked questionable - I tried to have a light hand, not a heavy one during editing!

**Comment by VashJuan** [comment]
Still figuring out git, as I thought this would result in a new Pull Request. Instad it merged with the previous one.

I did another Commit today that directly addresses the original issue ("References to www.dotnetnuke.com in text #2249"). I do NOT understand how the .SQLDataResource files work, so am only assuming from the issue that they needed modification.

I modified 
Dnn.Platform\Website\Install\App_LocalResources\InstallWizard.aspx.resx
and hope that is enough to get the changes rippled on to the language specific files like 
Dnn.Platform\Website\Install\App_LocalResources\InstallWizard.aspx.fr-FR.resx
since they are not in the source tree.

There are still a few references to Shaun Walker, but hey they can stand as far as I care!

**Comment by mitchelsellers** [comment]
This pull request still has conflicts with the base installation, additionally, there are a few other items needing correction, or limitation of rename.  (Ownership for example>) and additionally, the community will be moving some documentation to a new location.

I am going to close this for now, and we can revisit with 9.4.  @VashJuan we really do appreciate the contribution, the large number of file edits make the final review on this one a bit harder to manage.  Additionally the rules around copyright changes are a bit unique.  Feel free to message me with questions.

**Pull request closed without merging**
