### PR TITLE
Fixes errors with previous build scripts following PB merge

### LINKED ISSUE #3166: 503 error after clean install
## Description of bug
Something went wrong with #3041 Although multiple persons tested and confirmed everything was fine, something happened and there was files missing in the Persona Bar UI package and Extensions package. I cannot figure out if the PR was missing a commit or what, but some of the build scripts adjustments did not make it into the codebase.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Clone release/9.4.x or development branch
2. run ./build.ps1 in PowerShell
3. Create a new site using the install package produced in the Artifacts folder

## Current result
After installation, the site reports a 503 error and the browser console has multiple 404 for missing files.

## Expected result
The site should run fine.

## Additional context
I corrected the problem already before creating this issue, will submit a PR in a minute...

## Affected version

* [x] 10.0.0 nightly build
* [x] 9.4.1 nightly build
* [ ] 9.4.0 latest supported release

### PR DESCRIPTION
**Pull request by valadas**
Closes #3166 

## Summary
This fixes some missing commits from the merge of the persona bar into this repository and restores ability to build a working site.

For people reviewing this, please try the following before approving.

1. `git clone -b fix-merge-build https://github.com/valadas/Dnn.Platform`
2. open powershell as admin and run `./Build.ps1`
Let it build then verify the following

** Status should be clean **
`git status` should show nothing to commit (providing there was no build errors that stopped the build midway in which case, you should run `git reset --hard` and try again fixing what caused the error.

** You should have 4 zips in the Artifacts folder **
Try a clean install.
Try an upgrade.
Verify the Persona Bar works and gets 9.4.2 version
Verify the Edit Bar works

### CODE REVIEW

**Comment by valadas** [comment]
Also note that this is not a replacement for #3137 but just fixes the current build scripts while we still work on the other one (might fix #3137 too maybe)

**Comment by ahoefling** [comment]
This is going to be needed for #3160 as we don't have an installer being generated correctly by the build.

**Comment by valadas** [comment]
@ahoefling can you give it a test please.

**Comment by ahoefling** [comment]
I have tested the CreateInstall workflow which is what I noticed was broken when @valadas and I spoke offline about this issue.

* The Install Artifact from Azure DevOps works and installs correctly
* I cloned the PR and was able to generate an installer using `./Build.ps1 -Target CreateInstall`. Generated installer worked, however I ran into file path length which was easy enough to re-clone at the root level

If interested I have attached my build log from building local 
[build-output.log](https://github.com/dnnsoftware/Dnn.Platform/files/3746077/build-output.log)

**Comment by mitchelsellers** [comment]
Given that this is build related I’m exercising special approval steps to merge now.

**Pull request merged**
