### PR TITLE
Replace momentjs with dayjs for Servers.Web

### PR DESCRIPTION
**Pull request by david-poindexter**
## Summary
This is the first of several PRs for #3875.  This one replaces `momentjs` with `dayjs` for `Servers.Web` in Dnn.AdminExperience.

### CODE REVIEW

**Review by valadas — APPROVED** [review]
Looks good to me and saw it working fine

**Review by mitchelsellers — CHANGES_REQUESTED** [review]
Can we update the license documentation to include this new third party to keep compliant.

**Comment by valadas** [comment]
> Can we update the license documentation to include this new third party to keep compliant.

My suggestion is a bit beyond the scope of this PR but what do you guys think if we use https://classic.yarnpkg.com/en/docs/cli/licenses/ to generate all the mentions for the stuff we grab using npm. If we are in agreement, I can work on a PR that would do this on build... It would no cover stuff we use without npm but that would be a lot less maintenance for what does.

**Comment by mitchelsellers** [comment]
Possibly the generate disclaimer option could work. But for the interim id like to get it added here the normal way.

**Comment by david-poindexter** [comment]
@mitchelsellers yes, the license stuff is on my list.  This is the first of many PRs to switch from moment.js to dayjs.  Do you want the license mention to be added to this specific PR?  Also, I have seen license information in multiple places, so at this point I am not clear where it should be based on the usage context.

@valadas I really like your idea and it would really help to have this automated like this.  To me, the sooner we do that, the better off we'll be covered for attribution.

**Comment by mitchelsellers** [comment]
Just needs to be in the master list of licenses for the project. 

No specific place for this PR

**Comment by david-poindexter** [comment]
> Just needs to be in the master list of licenses for the project.

@mitchelsellers I just pushed a commit to put it where I think it needs to be.  Let me know if that is not the correct place.

**Review by mitchelsellers — APPROVED** [review]

**Pull request merged**
