### PR TITLE
Unable to "Add an Existing Module" from a disabled page

### LINKED ISSUE #2594: Not all pages visible when adding existing module
## Description of bug
I want to add an existing module but the page residing that module is not visible in the UI for adding the module

## Steps to reproduce
List the steps to reproduce the behavior:
1. A have a page 'For who'
2. This page has sub pages Developer, Projectmanager, Scrum master
3. In the page Scrum Master I click on the Add exsiting module page as I want to use a copy of modules on the Developer page
4. In the UI the Page 'For who' is not visible.

## Expected result
I expect the page in the UI so I can expand that page to select the subpage

## Additional context
If I paste the pagename in the UI, the page is visible. So, there is a workaround but not a friendly one.

## Affected version
* [x] 9.2.2
Did not test other versions

## Affected browser

* [x] Chrome
* [x ] Edge
Did not test other versions.

### PR DESCRIPTION
**Pull request by Mhtshum**
Fixes #2594 

## Summary
Append , includeDisabled in call from UI

### CODE REVIEW

**Comment by Mhtshum** [comment]
Please review [@dnnsoftware/approvers](https://github.com/orgs/dnnsoftware/teams/approvers)

**Comment by mitchelsellers** [comment]
@Mhtshum Can you update this to be based off of Development rather than 9.3.0, this would be something for 9.3.1

**Comment by Mhtshum** [comment]
@mitchelsellers 

Done #2623

**Comment by bdukes** [comment]
Superseded by #2623

**Pull request closed without merging**
