### PR TITLE
Add JsonIgnore Attribute

### LINKED ISSUE #5005: JsonIgnore Needs to be Added wherever XmlIgnore is
## Description of problem
I am currently working on updating the Redis Cache Provider to support JSON serialization with a binary fall back. A common error I am currently seeing is:

```
Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'Vocabulary' with type 'DotNetNuke.Entities.Content.Taxonomy.Vocabulary'. Path '$values[0].DesktopModule.Terms.$values[0].Vocabulary.Terms.$values[0]'.
```

Looking at the file `DNN Platform/Library/Entities/Content/Taxonomy/Term.cs` I see that in order to avoid this issue on the XML side, `XmlIgnore` was added to multiple properties. In order to support Json Serialization we will need to add `JsonIgnore` to the attributes that have `XmlIgnore`

## Description of solution
In order to support Json Serialization we will need to add `JsonIgnore` to the attributes that have `XmlIgnore`

### PR DESCRIPTION
**Pull request by mtrutledge**
Fixes #5005 

## Summary
Anywhere there was an ```XmlIgnore``` attribute we have added a ```JsonIgnore``` attribute from the Newtonsoft.Json library. This will help to ensure serializing to Json is mirroring the XML serialization objects.

### CODE REVIEW

**Review by bdukes — APPROVED** [review]
Thanks!

**Review by donker — APPROVED** [review]
LGTM

**Comment by mtrutledge** [comment]
YAY passing build.

**Pull request merged**
