### PR TITLE
Fix bug - postback issue with the cke editor

### LINKED ISSUE #4709: CKEditor disappears on Postback
## Description of bug
Rich Text Editor(CKEditor) disappears after the page performs a postback.

## Steps to reproduce
1. From a fresh install, edit content on a HTML module on the default home page
2. Click on the combobox at the bottom to select Basic Text Box.
3. Click on the same combobox to choose Rich Text Editor.

## Current behavior
The Rich Text Editor is there when the page first loads, but disappears and will not reload after a postback was triggered.

## Expected behavior
When Rich Text Editor is selected from the combobox, the Rich Text Editor is expected to load and be usable.

## Screenshots
image

## Error information
No errors seen in logs or console

## Additional context
https://dnncommunity.org/forums/aft/2502

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.09.00 latest supported release

## Affected browser

* [X] Chrome
* [X] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

### PR DESCRIPTION
**Pull request by nellaaayyy**
Fixes #4709 

## Summary

CKE Editor disappears on postback. Returning false will stop the postback from happening.

### CODE REVIEW

**Comment by mitchelsellers** [comment]
@skamphuis or @Timo-Breumelhof Do you have any insight on this one by chance since you have been in the editor?

**Comment by skamphuis** [comment]
I'm happy to have a look tomorrow.

**Comment by skamphuis** [comment]
@mitchelsellers I tested this change and indeed it does fix the issue as described in #4709 . Saving changes in both editor mode and basic text mode keeps working. Good catch, @nellaaayyy

**Review by david-poindexter — APPROVED** [review]
Awesome - thanks @nellaaayyy 🎉

**Comment by nellaaayyy** [comment]
> Awesome - thanks @nellaaayyy 🎉

no problem!

**Pull request merged**
