### PR TITLE
check the url with case insensitive.

### LINKED ISSUE #3201: module settings dialog can't be open if urls converted to lower case
## Description of bug
module settings dialog can't be open if urls converted to lower case

## Steps to reproduce
1. install engage 9.3.4 and login as host;
2. open Settings > SEO from persona bar, enable "Convert URLs to Lowercase" and save;
3. open Content > Pages, select a page, and switch to "Advanced " tab, click any edit content icon of settings icon for modules.

## Current result
the persona bar will be closed, and page redirect to the dialog page.

## Expected result
the dialog should open correctly.

## Affected version
* [ x] 9.4.1 latest supported release
* [ x] 9.3.2

### PR DESCRIPTION
**Pull request by zyhfish**
Fix #3201

### CODE REVIEW

**Comment by david-poindexter** [comment]
Hi @zyhfish - can you remove the Jira number reference from the PR title?  It can be referenced in the description if necessary but we need to keep PR titles clean moving forward.  Also, this PR Is targeting `development` instead of `release/9.4.x`.  Which release is intended for this change?  Thanks.

**Comment by david-poindexter** [comment]
@zyhfish is this intended for inclusion in DNN 9.4x or 10?  

Currently the PR is targeting the `development` branch (which is for DNN 10).  If you want this considered for DNN 9.4.x, please target the `release/9.4.x` branch.  Thanks!

**Comment by zyhfish** [comment]
thanks @david-poindexter , I will create another PR later.

**Comment by david-poindexter** [comment]
Thank @zyhfish - sorry for the hassle.  The branching at this time is a bit confusing. 
😁👍🏼

**Comment by zyhfish** [comment]
#3208 created.

**Pull request closed without merging**
