### PR TITLE
Feature/resource manager

### LINKED ISSUE #3708: add resource manager module to replace DAM.
add resource manager module to replace DAM.

### PR DESCRIPTION
**Pull request by zyhfish**
Fix #3708

### CODE REVIEW

**Comment by ashishpd** [comment]
Hi Everyone - This PR is coming from DNN Corp. We are open sourcing a new module to be used in the DNN Platform named Resource Manager. This module has a modern way to manage folder and files in DNN. The feature-set matches that of Digital Asset Management with some limitations. The PR has been approved for submission by DNN's CEO, Andy Tryba. 

Enjoy!

**Comment by mitchelsellers** [comment]
@valadas @bdukes How do we want to manage this?  Accept the PR as-is and submit follow-on PR's for missing features/enhancements?

I'm seeing some verbiage and things that I'd like to clean up.  For example, the spelling of Behavior is using the European styling and I would prefer to match current styles etc.

**Comment by valadas** [comment]
I think the main problem now is it is not building which will block other PRs is we merge it as is and need more time to make it build...

I would maybe:
1. Create a feature branch for it
2. On that branch, fix the build
3. On that branch adjust the manifest so it is locked with 9.7.0 version but the same name as the current on (so it can be an in place replacement)
4. Ensure the build scripts package it as .resources instead of .zip

That will allow us to have it live on develop and be an optional replacement for people who are happy with it as it stands, then we can improve it and when we get feature parity (folder settings and stuff) it will simply replace our old one by default just by removing the old one and adjusting our build scripts to package it as a zip

**Comment by mitchelsellers** [comment]
Ok, what's the best way to do that?

* Branch off of develop now
* Rebase this PR to that new branch
* Approve the PR?

Then continue working?

**Comment by valadas** [comment]
Hmm, let me merge the latest changes from 9.6.0 into develop, release 9.6.0 and then we branch a feuture branch, sounds good?

**Comment by zyhfish** [comment]
I just made changes to fix the items mentioned by @valadas, waiting for the CI building result.

**Comment by valadas** [comment]
Awesome, thanks @ash @zyhfish @mitchelsellers 

I just created a branch for it called feature/resource-manager so we can work on that in isolation (pun intended). It fired up a new build but should be the same thing. I need to go to bed, approving and ready to merge as soon as built.

**Pull request merged**
