### PR TITLE
DNN-8564: Performing Hard Tab Deletion, messes up TabOrder of other portals

### PR DESCRIPTION
**Pull request by JoshuaBradley**
See Jira Ticket: [https://dnntracker.atlassian.net/browse/DNN-8564](https://dnntracker.atlassian.net/browse/DNN-8564)

### CODE REVIEW

**Comment by bdukes** [comment]
:+1: LGTM (I put a diff between the 9.0.0 version of this sproc and this update at https://gist.github.com/bdukes/fe8c45e7991c35bc445068892c0c200f#file-dnn-8564-patch)

Any issues from @jbrinkman or @ashishpd?

**Comment by bdukes** [comment]
Any feedback/status, @wmorgenweck, @cpaterra, @ashishpd, or @jbrinkman?

**Comment by galatrash-at-dnn** [comment]
There is already PR for this issue: https://github.com/dnnsoftware/Dnn.Platform/pull/1453

**Comment by zyhfish** [comment]
The changes looks good but it add in old version file, i merge the changes into new PR #1893. close this one.

**Pull request closed without merging**
