### PR TITLE
Update Project URL on all Web Projects

### PR DESCRIPTION
**Pull request by ohine**
and fix the designer files

### CODE REVIEW

**Comment by bdukes** [comment]
looks good to me :+1:

**Comment by jbrinkman** [comment]
This needs a Jira with a good description of what this is supposed to fix.

**Comment by galatrash-at-dnn** [comment]
@ohine this PR has many conflicts. Moreover, this has to follow what @jbrinkman commented earlier (need a Jira, etc.). I will close it without merging. If you still feel it is relevant, please follow the guidelines by creating a Jira issue and adding relevant info there with a conflict free PR.

**Comment by galatrash-at-dnn** [comment]
Due to the large number of merge conflicts and no response from the submitter, beside no associated Jira issue # for this PR, I will close this without merging.

**Pull request closed without merging**
