### PR TITLE
Added right-to-left support

### PR DESCRIPTION
**Pull request by moshefi**
The PB UI part of this PR is here https://github.com/dnnsoftware/Dnn.AdminExperience.Library/pull/10

### CODE REVIEW

**Comment by moshefi** [comment]
Attached is the right-to-left (*.rtl.css) files extension package
[Dnn901.RTL.StyleSheets.zip](https://github.com/dnnsoftware/Dnn.Platform/files/747408/Dnn901.RTL.StyleSheets.zip)

**Comment by moshefi** [comment]
dnn9-rtl

**Comment by moshefi** [comment]
[Dnn901.RTL.StyleSheets.zip](https://github.com/dnnsoftware/Dnn.Platform/files/759969/Dnn901.RTL.StyleSheets.zip)

**Comment by moshefi** [comment]
Also see PersonaBar RTL
https://github.com/dnnsoftware/Dnn.AdminExperience.Library/pull/10

**Comment by galatrash-at-dnn** [comment]
@moshefi , you need to sign and send the CLA document before we look into this PR. See this https://github.com/dnnsoftware/Dnn.Platform/blob/development/CONTRIBUTING.md

**Comment by mitchelsellers** [comment]
Closing this PR due to staleness and procedural changes to the PR process.  If this issue/contribution is still desired please resubmit, we apologize for any delay as the finalize the transition of PR management to the DNN Community.

If re-submitted please make note of the re-submission with the new PR and we will expedite review following the current procedures.

**Pull request closed without merging**
