### PR TITLE
Move Email above Username in User.ascx

### PR DESCRIPTION
**Pull request by thabaum**
https://github.com/dnnsoftware/Dnn.Platform/pull/3204

This PR is accepted in 10, it was my first PR so I wished to include in current version.  I was working on development branch so this can be removed from there.  I changed to 9.4.x for the correct version.

Again make changes as needed... or close it if it is a change best in 10.

### CODE REVIEW

**Comment by valadas** [comment]
@thabaum can you look at the conflict please...

**Comment by thabaum** [comment]
I seen that warning trying to make sense of it

**Comment by thabaum** [comment]
how does the same file conflict with itself?

**Comment by thabaum** [comment]
image
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

image

wow this is deep it will take some time to learn this...

**Comment by thabaum** [comment]
I see the problem is https://github.com/dnnsoftware/Dnn.Platform/pull/3204 is already merged into 10, how do I take care of this?  Can I have a clue please :)

**Comment by valadas** [comment]
Ok, so git is just a huge tree of commits, a conflict occurs when after the commit where you started there is more than one commit that changed the same file/lines. Sometimes it is obvious and github can resolve them automatically, sometimes it is in between and github can show you a UI to decide what to keep or not or what to change. In this case github cannot figure it out and it needs more attention by a human using other tools. This often happens when files are moved and other issues...

To resolve this one, you need to merge back (or rebase, but rebase is more advanced and I would not touch it unless you really know what you are doing) the latest the target branch into your own branch...

I am assuming you setup your local clone with the **upstream** remote pointing to this repository and the **origin** remote pointing to yours, if not, let me know and I can explain that step..

So step on is for your local branch of your target for the PR to be updated to the latest changes from here, we change to the branch, we fetch the latest changes (metadata only), then we pull those latest changes locally:
```
git checkout release/9.4.x
git fetch upstream
git pull upstream release/9.4.x
```

Step to is to merge these new changes into your branch. But you did not create a separate branch to isolate your changes.... Soooo, yeah, not sure how to handle it from now, normally you would merge that into your branch and then open any editor to resolve the conflict then commit and push...

Now your branch is both ahead and in advance of your target, sooooo hard to manage, you are missing commits and have commits that are not present relative to your target... @bdukes do you have a trick up your sleeve or does @thabaum need to start over?

**Comment by thabaum** [comment]
@valadas thanks for the info, sorry to be a bug here.  I will deal with this i need to learn thank you.  I may just start from scratch.

I am just starting to work with visual studio/github and creating branches in a way to where I know I am working on the right one, and if not how to fix it the fastest way possible depending on the situation.

**Comment by valadas** [comment]
Yeah, sometimes it is quicker to start over for 1 file change this simple... :)

But yeah, usually you want to have your clone up to date and create a separate branch for each PR you want to submit starting from the point you want to submit the PR for.

**Pull request closed without merging**
