### PR TITLE
Update test dependencies

### PR DESCRIPTION
**Pull request by bdukes**
## Summary
This PR upgrades packages used only by tests

### CODE REVIEW

**Review by david-poindexter — APPROVED** [review]

**Review by david-poindexter — CHANGES_REQUESTED** [review]
Sorry - accidentally approved.  I meant to comment about the failed build.

**Comment by bdukes** [comment]
Hmmm… that happened locally, it's missing an assembly from the output directory (even though it's marked as Copy Local). I had thought maybe it was an environment thing and we wouldn't see it in a clean CI build, but I guess not… It's only that one Config console tests project. I didn't see an obvious difference.

**Comment by bdukes** [comment]
@david-poindexter removing the reference to the assembly it needed resolved the issue 🤷🏻‍♂️

**Review by valadas — APPROVED** [review]

**Review by david-poindexter — APPROVED** [review]
Thank you @bdukes 🎉

**Pull request merged**
