### PR TITLE
Automatically handle TLS negotiation for MailKit

### PR DESCRIPTION
**Pull request by bdukes**
Based on http://www.mimekit.com/docs/html/Frequently-Asked-Questions.htm#SslHandshakeException

### CODE REVIEW

**Review by david-poindexter — APPROVED** [review]
Looks good to me - thanks @bdukes 🎉

**Review by valadas — APPROVED** [review]
Looks good to me

**Comment by valadas** [comment]
Oops, there is this error though
`D:\a\1\s\DNN Platform\Library\Services\Mail\MailKitMailProvider.cs(158,52): error CS0103: The name 'SecureSocketOptions' does not exist in the current context [D:\a\1\s\DNN Platform\Library\DotNetNuke.Library.csproj]`

**Comment by bdukes** [comment]
I've pushed a change with the missing `using` statement, sorry about that.

**Pull request merged**
