### PR TITLE
Fixes an issue where Dnn would not install

### LINKED ISSUE #4135: Current develop branch builds but won't install
## Description of bug
Current develop branch does build and test fine but when installing Dnn, there is a error related to no root node in xml file.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Build current develop branch using `.\build.ps1`.
2. Try to install using the produced install package.

## Current behavior
Install errors out with an error about not having an xml root node.

## Expected behavior
Should install fine.

## Additional context
I think I found the cause, an empty 09.07.03.config file that was committed in #4121 
I will test this theory and submit a PR shortly.

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.07.03 alpha build
* [ ] 09.07.02 latest supported release

### PR DESCRIPTION
**Pull request by valadas**
- Removes empty 09.07.03.config file
- Includes other config files in project so they are visible in Visual Studio

Closes #4135

### CODE REVIEW

**Review by david-poindexter — APPROVED** [review]

**Review by mitchelsellers — COMMENTED** [review]
A prior PR had a config element in it though?  Did that file content get lost?

**Comment by valadas** [comment]
> A prior PR had a config element in it though? Did that file content get lost?

Oh, then yeah, that got lost, on develop that file is empty...

**Comment by valadas** [comment]
But I am not seeing that in the file history https://github.com/dnnsoftware/Dnn.Platform/commits/develop/DNN%20Platform/Website/Install/Config/09.07.03.config

You have any reference to that content @mitchelsellers  ?

**Comment by mitchelsellers** [comment]
It was on the removal of the Beacon

**Comment by valadas** [comment]
After discussion with @mitchelsellers , holding this for the actual content that should have been in this file...

**Comment by mitchelsellers** [comment]
@valadas I will not be until tomorrow that I can re-create this.  It was the removal of the appSetting Key for the ImprovementService URL

**Review by bdukes — APPROVED** [review]

**Comment by bdukes** [comment]
Can we just merge this as-is, and the upcoming PR will add the file back?

**Comment by mitchelsellers** [comment]
@bdukes Yes, I'll merge now

**Pull request merged**
