### PR TITLE
Enhance CI integration of Cake

### PR DESCRIPTION
**Pull request by bdukes**
This PR integrates the Cake tool Cake.BuildSystems.Module:
>This module will introduce a number of features for running in hosted CI build environments to tightly integrate with the host environment/tools. These modules require no changes to build scripts and instead rely on your Cake script's standard aliases and lifecycle events to integrate your script into the environment.

For Azure DevOps it will provide the following
> * Individual timeline records for each task
> * Percentage reporting on build progress
> * Integrates `Warning` and `Error` logging aliases with the Build Issues summary
> * Includes a Cake Build Summary widget on the build summary page

### CODE REVIEW

**Comment by bdukes** [comment]
This doesn't seem to have had an effect, I have an open issue on the tool repo to investigate if I'm doing something wrong.

**Comment by bdukes** [comment]
I (temporarily) directly added a custom version of the NuGet package which works for Cake 1.0.0, you can see the extra build info at https://dev.azure.com/dotnet/DNN/_build/results?buildId=44680&view=ms.vss-build-web.run-extensions-tab.  I don't see that there's enough info in there to worry about integrating this Cake module.

My next attempt will be looking at integrating https://cakeissues.net/, which can read MSBuild logs and report issues to the build, as well as to the PR as a comment (if we want that).

**Review by donker — APPROVED** [review]

**Review by mitchelsellers — APPROVED** [review]

**Comment by bdukes** [comment]
This PR is in a testing state where I'm using manually build DLLs instead of a NuGet package.  My change https://github.com/cake-contrib/Cake.BuildSystems.Module/pull/25 was merged, but waiting for a new version to be published first.

**Comment by valadas** [comment]
@bdukes is this good to go now or still in testing state?

**Comment by bdukes** [comment]
This is available to merge now (no rush)

**Pull request merged**
