### PR TITLE
Update 9.11.0 branch with changes from develop

### PR DESCRIPTION
**Pull request by bdukes**

### CODE REVIEW

**Comment by bdukes** [comment]
This is a release management task, as per our policy, we are self-approving it.

**Comment by valadas** [comment]
What happens if there are more PRs like #4933 ? Will this be closed and a new PR will replace it ?

**Comment by bdukes** [comment]
This is a PR between `release/9.11.0` and `develop`, so it automatically includes whatever is currently on `develop` (until this PR gets merged)

**Comment by valadas** [comment]
Oh, nice, yeah makes total sense. Thanks

**Review by valadas — APPROVED** [review]

**Pull request merged**
