### PR TITLE
Do all non-major npm upgrades

### PR DESCRIPTION
**Pull request by bdukes**

### CODE REVIEW

**Comment by bdukes** [comment]
@valadas @david-poindexter Any idea why [this TS error from the Resource Manager build](https://dev.azure.com/dotnet/DNN/_build/results?buildId=96296&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=d01ed771-bc1f-5e98-e7ad-71f8c6eef93d&l=340) might have happened after upgrading @stencil/core from 2.18.0 to 2.22.3?

```
dnn-resource-manager: [30:42.6]  @stencil/core
dnn-resource-manager: [30:43.1]  v2.22.3
dnn-resource-manager: [30:47.4]  build, dnn-resource-manager, prod mode, started ...
dnn-resource-manager: [30:47.7]  transpile started ...
dnn-resource-manager: [31:00.3]  transpile finished in 12.59 s
dnn-resource-manager: [ ERROR ]  TypeScript: ../../../../node_modules/@types/ws/index.d.ts:328:18
dnn-resource-manager:            Type 'Server' is not generic.
dnn-resource-manager:     L327:  backlog?: number | undefined;
dnn-resource-manager:     L328:  server?: HTTPServer<V> | HTTPSServer<V> | undefined;
dnn-resource-manager:     L329:  verifyClient?:
dnn-resource-manager: [31:00.3]  build failed in 12.86 s
```

**Comment by valadas** [comment]
@bdukes potentially because of the typescript version. More details here: https://stenciljs.com/docs/support-policy

Now we should bump it to at least the v3, I have done so on about 20 other projects without too much trouble, we just need to also bump some plugins at the same time and take a look for any deprecated feature used in the stencil config file. I'll try to do that this weekend 🤞

**Comment by bdukes** [comment]
I reverted @types/ws from 8.5.5 to 8.5.4 based on https://stackoverflow.com/a/76570993/2688, and that resolved the build for me locally.

**Comment by bdukes** [comment]
Once that was resolved, there were eslint errors around undeclated prop-types. These appear to be real issues due to [a bug in the `prop-types` rule](https://github.com/jsx-eslint/eslint-plugin-react/issues/442). For now, I reverted to an older version of `eslint-plugin-react` and fixed the two issues that came up when on that version. It's now all successfully building (for me, locally 🤞🏻)

**Review by valadas — APPROVED** [review]
Awesome, I downloaded the CI build and can confirm everything appears to be working fine.

**Review by david-poindexter — APPROVED** [review]

**Pull request merged**
