### PR TITLE
Bump System.IdentityModel.Tokens.Jwt from 4.0.2.206221351 to 6.31.0

### PR DESCRIPTION
**Pull request by bdukes**
## Summary
This PR upgrades the JWT auth project to the latest version of the System.IdentityModel.Tokens.Jwt package.

This involved translating one piece of code from the old objects to a new set of types.

It introduces a dependency on System.Text.Json, as well as a couple of new IdentityModel assemblies.

### CODE REVIEW

**Comment by bdukes** [comment]
I've installed the updated JWT package on a 9.11.2 site and was able to successfully call APIs using JWT

**Review by valadas — APPROVED** [review]
Awesome, thanks for cleaning up the code in the process 😄

**Comment by bdukes** [comment]
@mitchelsellers this PR is ready to merge

**Review by mitchelsellers — APPROVED** [review]

**Comment by mitchelsellers** [comment]
Boo? Merging the other one seems to have added a conflict

**Comment by bdukes** [comment]
Conflicts resolved

**Pull request merged**
