### PR TITLE
Close #2263: change support@dotnetnuke.com to support@dnnsoftware.com

### LINKED ISSUE #2263: Update references to support@dotnetnuke.com to support@dnnsoftware.com
## Description 
The text support@dotnetnuke.com and www.dotnetnuke.com should reference dnnsoftware.com i.s.o. dotnetnuke.com

## Steps to reproduce
Nothing special,  just search for the references dotnetnuke.com

## Current result
Multiple locations in multiple files

## Expected result
None

## Affected version

* [x] 9.2.1
* [x] 9.2.0
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

### PR DESCRIPTION
**Pull request by EPTamminga**
Close #2263 

## Summary

change reference to  support@dotnetnuke.com into support@dnnsoftware.com

### CODE REVIEW

**Comment by EPTamminga** [comment]
@mitchelsellers I did a straight text search in the DNN.Platform repo and the ones I changed are the ones that I found.
There are also references to the text in (pre DNN9) SQLProvider scripts. Do you want to change the old scripts?
In the other DNN repo's, there are references to support@dotnetnuke.com as well. IF I change those, they will become PR's for those repo's

**Comment by mitchelsellers** [comment]
@EPTamminga  my search was flawed, you are correct.

Would it be possible to get you to update this file as well: https://github.com/dnnsoftware/Dnn.Platform/blob/584b0f54bd6b6d237594dd9f96053f14db0b1a53/DNN%20Platform/Components/Microsoft.CodeDom.Providers.DotNetCompilerPlatform/releaseNotes.txt 

Just so we can keep 1 PR for this update.  That is a dnncorp.com reference.

**Comment by EPTamminga** [comment]
@mitchelsellers: additional files (release notes txt) corrected (including https:// i.s.o. http://)

**Comment by ohine** [comment]
@mitchelsellers can you review this again? I don't want to merge it if you still have outstanding issues.

**Pull request merged**
