### PR TITLE
DNN-7746 Implement IPortable for DCC Viewer

### PR DESCRIPTION
**Pull request by jmauret**

### CODE REVIEW

**Comment by ohine** [comment]
@jmauret did you have any plans on adding support for cross-installation templates? or would that be a separate pull request?

**Comment by jmauret** [comment]
Brian and I discussed exactly that on Friday.  Since this is on company
time (its training, basically) I can't say for sure what else I'll be
adding or changing.

But I think my current implementation has problems in some edge cases which
I'll be investigating more this week.  I want to make sure portal-to-portal
is bulletproof before aiming any higher.

-Jeremy

On Mon, Oct 26, 2015 at 7:11 AM, Oliver Hine <notifications@github.com>
wrote:

> @jmauret <https://github.com/jmauret> did you have any plans on adding
> support for cross-installation templates? or would that be a separate pull
> request?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnnsoftware/Dnn.Platform/pull/932#issuecomment-151114631>
> .
>



-- 

*Jeremy Mauretto*
jmauretto@engagesoftware.com <jlissner@engagesoftware.com> | *314.884.2447*

*Team Engage:* Your ideas. Our know-how.
*~ Engage is proud to be a **DotNetNuke Gold Partner ~*

About Engage <http://bit.ly/engage-email> | Twitter
<http://bit.ly/engage-twitter> | LinkedIn <http://bit.ly/engage-li>

**Comment by ohine** [comment]
Ok, that sounds like a great plan. Since @bdukes is working with you on this pull request I'll let him merge it into the platform. I was about to earlier today, but I wanted to make sure you were complete with the changes you wanted to include.

**Comment by cpaterra** [comment]
@jmauret I have marked this as merged (so you get credit), this is something that is important for the viewer. However, since we are in the middle of re-architecting the backend and API of DCC itself I am going to reject this pull request. This was a good contribution, but since we are going to really change up how the data is stored this will be very different in the end. Thanks!

**Pull request closed without merging**
