### PR TITLE
Improve HTML attribute support in client resource manager

### PR DESCRIPTION
**Pull request by bdukes**
## Summary
This PR improves on #5242. 

- Use dictionaries of attributes directly instead of requiring them to be serialized and deserialized as strings
- Add HTML attributes overloads for CSS
- Clean up some comments, typos, and other code

### CODE REVIEW

**Review by valadas — APPROVED** [review]
This is awesome, even cleaner.
I used empty dictionaries so it does not get confused and hit the wrong overload (multiple strings passing nulls), never thought about using the parameter name to resolve that ambiguity. Great idea, and love the ternaries for empty strings, much much simpler and easier to understand!

**Comment by valadas** [comment]
@bdukes you think the build failure is a fluke

**Comment by bdukes** [comment]
Yeah, I've re-run the build

**Review by david-poindexter — APPROVED** [review]

**Pull request merged**
