### PR TITLE
DNN-7120: Add New Module should allow adding individual module definitions

### PR DESCRIPTION
**Pull request by stephen-lim**

### CODE REVIEW

**Comment by bdukes** [comment]
I would expect that there would also need to be changes to the installer to allow this, in addition to your control bar changes.  Have you tried installing a package with multiple module components?  Does anything need to change to make uninstalling work?

**Comment by stephen-lim** [comment]
Hi Brian

I had thought so too at first but it turns out there's no need to change the installer because the Add New Module in the controlbar was previously referring to DesktopModuleID when it simply need to pass the ModuleDefinitionID instead. This is now a little more consistent with how the Add Existing Module works.


Yes, I have tested with both a simple and a complex Revindex Storefront ecommerce module (24 modules in a single package with all sorts of config changes, url extension provider, custom permissions, sql scripts, cleanup) and they both worked great. I made sure to test adding new module in the same and different pages, then search and add existing module to another page, then deleting the modules. I also made sure the recycle bin is properly working after a module delete and the module bookmarks work properly. I also test the Extension uninstall and they all worked properly with no client side and server side errors.


Thanks,

Stephen----------------------
www.revindex.com







---- On Tue, 16 Jun 2015 10:11:46 -0400 Brian Dukes&lt;notifications@github.com&gt; wrote ---- 

I would expect that there would also need to be changes to the installer to allow this, in addition to your control bar changes. Have you tried installing a package with multiple module components? Does anything need to change to make uninstalling work?

**Comment by cathalconnolly** [comment]
Please note, that QA will request a test package so they can verify this otherwise we wont be able to accept it in a timely fashion -the best thing to do is to attach it to the jira.

Also @cnurse will likely want to review this code first.

**Comment by stephen-lim** [comment]
Thank you Cathal. I have attached a test package to the JIRA for QA.

**Comment by stephen-lim** [comment]
Any idea how soon can we include this fix to correctly handle multiple modules in a package? It's one of the top 10 most voted idea:
http://www.dnnsoftware.com/voice/allow-packages-to-contain-multiple-modules

**Comment by bdukes** [comment]
It doesn't look like there's a way to access any modules other than the first via Extensions.  On one hand I'd expect to see both modules in the Extensions list, but on the other I'd like the uninstall action to affect the entire package.

Trying this out I get this error from the Add Module action in the control bar:
```
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
at System.Collections.Generic.SortedList`2.Add(TKey key, TValue value)
at DotNetNuke.Entities.Modules.DesktopModuleController.GetPortalDesktopModules(Int32 portalId) in c:\Code\Dnn.Platform\DNN Platform\Library\Entities\Modules\DesktopModuleController.cs:line 558
at DotNetNuke.Web.Components.Controllers.ControlBarController.GetCategoryDesktopModules(Int32 portalId, String category, String searchTerm) in c:\Code\Dnn.Platform\DNN Platform\DotNetNuke.Web\Components\Controllers\ControlBarController.cs:line 57
at DotNetNuke.Web.InternalServices.ControlBarController.GetPortalDesktopModules(String category, Int32 loadingStartIndex, Int32 loadingPageSize, String searchTerm, String excludeCategories, Boolean sortBookmarks, String topModule) in c:\Code\Dnn.Platform\DNN Platform\DotNetNuke.Web\InternalServices\ControlBarController.cs:line 115
at lambda_method(Closure , Object , Object[] )
at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass13.<GetExecutor>b__c(Object instance, Object[] methodParameters)
at System.Threading.Tasks.TaskHelpers.RunSynchronously[TResult](Func`1 func, CancellationToken cancellationToken)```

**Comment by bdukes** [comment]
I'm testing with http://teamcity.engagesoftware.com/repository/download/EngageEmployment_Ci/271:id/Employment_01.12.08_Install_DNN5.2%2B.zip

**Comment by stephen-lim** [comment]
Hi Brian,

The error is happening on an unrelated code from my changes. To confirm, I downloaded your test package and installed it on a clean DNN 7.4.1 as well as on the development branch (without my code changes) and both are giving the exact same error at the same line. It's an unrelated bug that has something to do with your particular package that you may want to take a closer look. It may be your manifest has an error or there is another bug worth reporting to DNN tracker.

Thanks!

**Comment by EPTamminga** [comment]
Did the package pass the EVS without errors and warnings?

**Comment by stephen-lim** [comment]
I think I associated the pull request to the wrong JIRA number. This is implementation fix for DNN-7120 and not DNN-5599.

https://dnntracker.atlassian.net/browse/DNN-7120

I have now renamed the title from DNN-5599 to DNN-7120 to be accurate. If you can get this merged, I can take a look at starting a different branch and pull request to work on DNN-5599.

My apologies. Thanks,

**Comment by bdukes** [comment]
@stephen-lim that makes more sense, no worries.

with regards to DNN-7120, I've added some [comments into JIRA](https://dnntracker.atlassian.net/browse/DNN-7120?focusedCommentId=79621&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-79621), and I think this needs a review by a product manager (@jbrinkman, @cpaterra, @brucerchapman, etc.) as to whether this is a change that the platform wants.

**Comment by cnurse** [comment]
Per @bdukes - I have assigned this to @jbrinkman for his final decision.

**Comment by stephen-lim** [comment]
Hi @jbrinkman , I'm just wondering if you had the chance to go over the comments in JIRA on why this UI change makes sense and improves usability? I hope we can get this pull request in time for the next release.

**Comment by jbrinkman** [comment]
@stephen-lim I am reviewing this for potential inclusion in DNN 8.  Given the potential impact, it is not a viable candidate for a maintenance release.

**Comment by stephen-lim** [comment]
Thank you @jbrinkman I hope it gets merged into DNN 8 on time before the release.

**Comment by stephen-lim** [comment]
Will this be part of DNN 8 CPT3?

**Comment by jbrinkman** [comment]
No.  CTP 3 is going out today and this hasn't been merged yet as I still need to do a review of the pull request.

**Comment by stephen-lim** [comment]
Too bad, but thank you @jbrinkman for the update. I hope it gets merged in the next update :)

**Comment by stephen-lim** [comment]
Now that CTP3 is out. I like to know if this pull request will this be reviewed for CTP4? This pull request has been committed since June 3  :)

**Comment by stephen-lim** [comment]
@jbrinkman  any news?

**Comment by stephen-lim** [comment]
Hi @jbrinkman, do you know how soon this change can be merged?

**Comment by stephen-lim** [comment]
@jbrinkman  ?

**Comment by cpaterra** [comment]
The community voice item pointed out and this change are not the same problem being addressed. I also feel that this change is a step backward for a number of reasons. I am closing this out as if we were to address the true problem noted in Jira it should be done differently than this.

**Pull request closed without merging**
