### PR TITLE
Update Default Website template for DNN 10

### PR DESCRIPTION
**Pull request by david-poindexter**
## Summary
This PR updates the `Default Website` template for DNN 10.  Following are highlights of the changes.
* Re-implement localization of the template (which was previously only leveraging three resource keys and the RESX file had tons of leftover resources from very old versions of DNN, mostly DNN 6.x)
* Remove unnecessary declarations of theme layouts and containers.
* Update for new `Aperture` theme and content.
* Remove tabs that are no longer used (e.g., `User Accounts`).
* Update template resources file to remove old images and add new images
* Update template resources file to remove CSS file previously used with `Xcillion` theme

### CODE REVIEW

**Review by valadas — APPROVED** [review]
This is awesome, much less clutter.
I downloaded the CI build, did an install and everything worked perfect out-of-the-box.
Thanks so much for all the time invested.

I'd just like if we can replace a few png images with their jpg versions for smaller size...

**Comment by valadas** [comment]
Just for clarity for the second reviewer, I am fine merging this and adjusting the images in another PR

**Comment by david-poindexter** [comment]
> Just for clarity for the second reviewer, I am fine merging this and adjusting the images in another PR

FYI, @valadas is working on a PR to replace the photos now.  I just pushed a commit to update the HTML content in the template to point to JPGs and to add CSS classes for the rounded borders.

**Comment by david-poindexter** [comment]
Okay, a new commit has been pushed to replace the photos from @valadas - thanks so much for the Photoshop help!  Also, #5932 will handle the rounded corners for these replaced DNN Connect and DNN Summit group photos.  This PR is ready for final review/approval/merge.

**Review by valadas — APPROVED** [review]
Awesome

**Review by donker — APPROVED** [review]
Awesome

**Pull request merged**
