### PR TITLE
Journal Links + Comments Word-Break and Resizing

### PR DESCRIPTION
**Pull request by thabaum**
To resolve Issue #2225 plus issue #2981 

## Summary

Dedicated to enhance the Journal Module Styles for the Journal UI.
- This PR Expands Journal Editor and Comment Areas to use 100% Width of Site Theme Module Container Width.
- This PR Adds Visibility Setting to Save Space for for Closing Items Replacing Display Setting for Journal Close Items as Needed to Keep Text from Shifting When Hovering Mouse Pointer Over a Journal Item.
- This PR Adds Word Break Feature in the Journal  and Link Author, Titles, Description and Comment Areas.
- This PR Adds Inline-Flex to Author Links
- This PR adjusts author image area margin allowing more screen use.
- This PR Removes Border and Padding from Author Images.
- This PR Removes borders from Journal Link Images.
- This PR Adds Responsive Effect to Journal Link Images Allowing up to 25% Screen Width Size.

### CODE REVIEW

**Comment by valadas** [comment]
Please wait before reviewing/merging this Pull Request, I would like to take some time to look into it properly in combination with some of my current efforts to move stuff away from default.css into their more appropriate place (here).

**Comment by thabaum** [comment]
Can you post that link again @valadas thank you.  Make edits as you feel makes it work best.  No worries if this PR does not work, I just would like to see the changes for everyone to enjoy.  Not looking for credit as much as just seeing things get doctored up in DNN and trying to help lift the load a little here as I can without being too much of a distraction.

Thank you.

**Comment by valadas** [comment]
Oh yeah, no problem @thabaum just wanted to make sure I had time to review before this gets quickly merged, on it now...

**Comment by thabaum** [comment]
I have made a couple more similar adjustments missing I just tested today:

#journalEditor, .jcmt .cmteditarea { width: 100%;}
.journalTools #journalOptionArea {width: 100%;}
.journalrow div.journalitem .jlink img {border: 0px;}

I think these last three cleaned up all my visuals other than one thing that sort of bugs me with the text pushing to the sides when you hover and it shows an X to close it shifting the text around.  Not a big deal just a bit annoying but uses more screen for reading so no worries there at least there is a trade off...

If I can add these to the file as well if it is moving to development branch or you can add them.

This finishes my style fixes for the journal module just let me know how you would like to proceed and I will focus on the hyperlink issue again with some better luck hopefully.

**Comment by thabaum** [comment]
the development branch scared me to work on... now I know I can I will make these changes as well as re-submit my other PR's based on the dev branch.  I should have these done today.

I also wanted to resized the Image more like how it is shown here in GitHub.  Rounded corners and size with no border.  I will try to add that as well but if next version rolls out between now and then I can push it into a new PR later.  I was working on it last night so I will see what I have done if it works ok I will add them.

**Comment by bdukes** [comment]
@thabaum just to clarify, we renamed and rearranged the branches a bit, so `develop` is where changes for the next release go.  It's a copy of `release/9.4.x` from a couple of days ago, so there's no real difference between them, just naming at this point.  The old `development` branch was copied/renamed to `future/10` and is where breaking changes go.  `master` was re-added and contains only the released source code (so it is the same as the `v9.4.3` tag right now).  Finally, `release/*` branches will be created upon code freeze as we're getting ready for a release, and only regression fixes and showstoppers will be addressed on that branch.

Ultimately this means that almost all PRs should be submitted against `develop`.  We hope this simplifies things for contributors going forward (though we understand that the change itself can lead to confusion).

Hope it helps!

**Comment by thabaum** [comment]
I LOVE how it is on the top and I do not have to dig for it 👍

**Comment by thabaum** [comment]
I think I have made my final adjustments.  Please review because I was really having a tough time with my developer environment tossing me all over causing some confusion. 

I adjusted margins and removed borders along with making text areas and options area use 100% of the screen.

**Comment by thabaum** [comment]
@valadas made some extra changes here let me know if they look ok.  Also give him a chance to review before merging. thank you.

**Comment by thabaum** [comment]
The only issue I currently have left with the CSS is making the comments and items close button shifts the text over.  

A normal journal post does not have this effect shifting the text area field size:
image
image

vs what a journal comment or journal item does when you hover:

image
image

Another issue I am working on.  not sure if the display:none has anything to do with it I am trying to find out what the difference is between these two types of posts.  One has the correct desired effect at least which is the normal journal posts that do not convert into journal items due to links or images posted.  Hope this makes sense while you review maybe something might come to mind here.

**Comment by thabaum** [comment]
@valadas I made some adjustments to this PR.  

- I was able to get the closing buttons to work using visibility instead of display.  This keeps the text from bouncing around while moving your mouse around.  
- Journal items and text areas should all scale out 100% of the screen area allowed in a skin template.
- Word-Breaks added where needed.
- Author Image margins adjusted along with padding removed to allow the most use of screen space.

I believe that should wrap it up other than taking out some whitespace and trying to get things to tab together in github.

**Comment by david-poindexter** [comment]
@thabaum one thing that would help greatly is to work out everything prior to submitting the PR.  The only changes after the original submittal of a PR should be changes as a result of an approver’s request for changes.  Otherwise, it all becomes a moving target.  That said, let us know when you are done and we will re-review this PR.  Thanks.

**Comment by thabaum** [comment]
@david-poindexter i just kept improving although I new i was going to get a ding for this one... one thing led to another and since it was not merged yet I went ahead and added some more improvements each day it was not.  Otherwise I would of made separate issues and PR's for each one waiting for each merge to happen.  I sorta grouped a bunch together here.  Thank you.

**Comment by thabaum** [comment]
I am 100% done... let me know what you think and if you prefer any changes here.  Thank you.

**Comment by david-poindexter** [comment]
@valadas @bdukes @mitchelsellers although these are potentially good changes...do we consider this breaking?  I know a lot of themes that will essentially be broken as a result of these changes.  Should we target v10 for this one?

**Comment by thabaum** [comment]
the added controls possibly may be a 10... I can put anything breaking in another PR later on the future branch. This is fixing for me :)

**Comment by valadas** [comment]
My vote would be to include this in 9.5.0 because it is a minor release and not a patch release, I think we can afford a small change like this, worst case scenario is some little bit of css to adjust in a couple of themes. IMO but if there is strong traction to move it to 10, I can live with that too... I love that it is a css only fix, the markup will stay the same and the effect on other themes will probably be very minimal and certainly not unusable.

**Comment by thabaum** [comment]
I wanted to resize the graphic icons for the photo file and privacy however that is a bit more tricky and new for me to understand.  I would like the icons to be twice the size.  Maybe a later 9.5 release.  This current style fix cures all the issues I have with just a simple clean look and feel for the journal without stepping on anyone's toes too much hopefully.

I just copied and pasted it to my module css and took away all my css changes from my custom css page... all changes seem to be as intended and desired.

I hope some enjoy this and maybe it can help get more DNN users liking the CMS going forward with a little better feel IMO out of the box.

Journal concerns going forward:
I am still digging deep into the URL not being present when getting set to the database.  In the database it is being set as `URL: ''` so for some reason the '' is not getting set as I set a url in there with http:// or https:// in front it will set a link.  I also would like to possibly add a switch to allow all links and images to be converted to or at least try and set first https:// in front of the www url and image data provided.  Maybe even another switch to check if non-ssl images/urls are allowed.  If anyone understands what I am talking about maybe can take a look toss some suggestions or a PR fix I feel I am getting closer to a solution I just need to spend some more time poking around to try learn all the passes for touchdowns and interceptions.  :)  Thank you.

**Comment by david-poindexter** [comment]
@thabaum by the way, take a look at [THIS DOCUMENTATION](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords) for tips on how to properly reference issues that a pull request addresses.  This will ensure the referenced issue(s) automatically get closed upon merge of the PR.  Thanks!

**Pull request merged**
