### PR TITLE
Add PR workflow to optimize images

### PR DESCRIPTION
**Pull request by bdukes**
This adds a GitHub Actions workflow which optimizes images automatically in pull requests.

### CODE REVIEW

**Comment by valadas** [comment]
Do we actually have github actions enabled on the repository ?

**Comment by bdukes** [comment]
Good question.  If not, we can sign up at https://github.com/features/actions/signup/?account=dnnsoftware

**Comment by valadas** [comment]
Yeah, dnnsoftware does not show on my list, @mitchelsellers does that link work for you?

**Comment by mitchelsellers** [comment]
It is available, but an error:

" Thank you for your interest. GitHub Actions is not available to legacy per-repository accounts. Please upgrade your plan."

**Comment by bdukes** [comment]
Ah, I just saw [Nick Craver tweet](https://twitter.com/Nick_Craver/status/1192203178055479301) about that same issue.  

@ashishpd are y'all still using private repos on GitHub, or has all that moved?  Could this org become only OSS (or do y'all want to look at upgrading from legacy pricing)?

**Comment by valadas** [comment]
Oh, that would explain some other things too...

**Comment by mitchelsellers** [comment]
It looks like we have to stay on the paid version due to the "Version History" repos, not sure if we can clear this easily.

**Comment by valadas** [comment]
Oh, I see... Hmm, because of git LFS?

**Comment by david-poindexter** [comment]
Git LFS is definitely one of the things making this prohibitive.  That is used heavily for all the DNN archive repos.

**Comment by valadas** [comment]
Unfortunately we do not have github actions enable, if that changes in the future, we can revisit, closing this for cleanup in the meantime...

**Comment by bdukes** [comment]
@ashishpd can you contact GitHub support to see what effect it would have to move to the new style of billing plan that would support actions (as well as, e.g. the [Triage permission](https://github.blog/2019-10-03-delegate-responsibilities-with-expanded-repository-permissions/#triage))

**Comment by mitchelsellers** [comment]
@bdukes We already know this, I'll come to you offline about this

**Pull request closed without merging**
