### PR TITLE
DNN-7249 DCC Add a context menu to insert Content Type fields to template 

### PR DESCRIPTION
**Pull request by cnurse**
This also includes the code for DNN-7250 (Add a context menu to insert Razor Helper tags into template )

### CODE REVIEW

**Comment by jbrinkman** [comment]
This code is not working correctly.  I am seeing very strange behavior in Chrome, FF and Edge browsers.  In no case does the context menu display (although I can see that the underlying html is present).  In FF, the default browser context menu is being displayed.

**Comment by cathalconnolly** [comment]
tested this (from the PR) - different results per browser: chrome (works fine), FF (partly works, browser context menu appears as well but can be ignored), IE (doesnt work, browser context menu overlays template context menu so it is unreachable)

**Comment by cnurse** [comment]
I have it working in Edge, Chrome and Opera, but no matter what I try I cannot get IE and FF to stop showing their menus.

**Comment by cnurse** [comment]
If in doubt use jQuery - switched from using code mirror's own event handling to using jQuery's bind method on the CodeMirror object and hey presto it works in all browsers - Chrome, Edge, Opera, IE and Firefox.

**Pull request merged**
