### PR TITLE
Swap CodeMirror in SqlConsole for monaco-editor

### LINKED ISSUE #4168: Swap CodeMirror in SqlConsole for monaco-editor
## Description of problem
The current `SqlConsole` PersonaBar module uses is `CodeMirror`.  This editor is antiquated and lacking many useful features of a modern code editor.  It needs to be replaced.

## Description of solution
Replace `CodeMirror` in the `SqlConsole` PersonaBar module with [monaco-editor](https://microsoft.github.io/monaco-editor).

## Description of alternatives considered
n/a

## Screenshots
n/a

## Additional context
The `SqlConsole` module in the PersonaBar is not a `*.Web` project, so for now `monaco-editor` will not be managed via `Yarn`.  This should go on the wishlist though - to convert the `SqlConsole` project to a proper front end project with package management.

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

### PR DESCRIPTION
**Pull request by david-poindexter**
## Summary
Resolves #4168 

Please see the linked issue for more details on why this was implemented without package management.  It is a stepping-stone PR to get the editor integrated into a project that does not already have package management set up.

image

image

image

### CODE REVIEW

**Review by valadas — APPROVED** [review]
Awesome!

**Review by mitchelsellers — APPROVED** [review]

**Comment by scottri** [comment]
I installed 9.8.1 over 9.7.2 and the SQL Console is not working, the "text" windows does not appear. I reverted this change temporarily on my installation and the SQL Console is working. Any ideas on how to debug this?

**Comment by mitchelsellers** [comment]
Clear cache?

**Comment by scottri** [comment]
Hi Mitchel, I had tried clear cache with no luck. I got a copy of under my development environment working and Chrome shows the following parent page element for the control:
    <div id="monaco-editor" data-keybinding-context="1" data-mode-id="sql">...</div>
where as the VM and production system show effectively an empty div:
    <div id="monaco-editor"></div>

**Comment by bdukes** [comment]
So, to confirm, your application root is `http://test.nvicadvocacy.org/members` (i.e. there is _not_ a DNN site at http://test.nvicadvocacy.org)?

**Comment by scottri** [comment]
Brian, correct the DNN application is only in /members/.

**Pull request merged**
