### PR TITLE
DNN-7818: add send verification mail link in unverified message.

### PR DESCRIPTION
**Pull request by zyhfish**

### CODE REVIEW

**Comment by EPTamminga** [comment]
@zyhfish If I look into Jira, the issue # DNN-7818 is a completely different issue. 
https://dnntracker.atlassian.net/browse/DNN-7818
Can you please address the correct issue #?

**Comment by thabaum** [comment]
https://dnntracker.atlassian.net/browse/DNN-10721?jql=project%20%3D%20%22DNN%22%20AND%20text%20~%20%22SMTP%22%20ORDER%20BY%20priority%20DESC

Here you go another link to the same issue.  This one they made a fix for Evoq after I reported it and gave me the finger pretty much it looks like...

**Comment by valadas** [comment]
@zyhfish any reason for closing this PR ? @dnnsoftware/tag-group do you guys see any issue reopening this PR and merging it up ?

**Comment by zyhfish** [comment]
Hi @valadas , I can't remember why it gets closed, I checked the Jira history but no information there. could this was closed by accident? :)

**Comment by valadas** [comment]
Yes, looks like it was accidental during a branch cleanup. If you can resubmit it would be great if not I will try to replay this as a new PR next week. Thanks.

**Comment by zyhfish** [comment]
which branch should set the PR with? I can try to submit a new PR

**Comment by valadas** [comment]
If it is no breaking change then that should go against release/9.4.x please @zyhfish 

Thanks

**Comment by zyhfish** [comment]
Thanks @valadas , PR #3144 created, please check.

**Comment by valadas** [comment]
Thank you !

**Pull request closed without merging**
