### PR TITLE
complete fix for DNN-6758

### PR DESCRIPTION
**Pull request by sleupold**
update stored procedures, which are using the columns with modified size.
Using proper size for CultureCode as well.

### CODE REVIEW

**Comment by ohine** [comment]
:+1: this look good, we will need to update this to use a new incremental sql version to ensure it will run on any existing 7.4.2 sites. Assigning to Joe for the decision to include in 7.4.2 or 8.0

**Comment by jbrinkman** [comment]
This will go in 8.0.  We are already past the point where we want to take any more changes for 7.4.2.

**Comment by sleupold** [comment]
No problem for me, fix is included already in my Turbo Scripts V 0.9.9

**Comment by zyhfish** [comment]
this commit include lots of unrelated changes with DNN-6758, some of the included change have already been merged in some other PRs, also it contains duplicated code in this PR, we need make ONE PR only for ONE problem.

**Comment by zyhfish** [comment]
Looks good.

**Comment by sleupold** [comment]
please be aware that the PR had been made before incremental scripts were implemented.

**Comment by antoniodgonzalez** [comment]
Hi @sleupold, as commented above, the SQL changes must be added to a incremental 8.0 script before this pull request can be merged. Thanks

**Comment by sleupold** [comment]
closing request in order to re-create against development branch

**Pull request closed without merging**
