### PR TITLE
upgrade jquery-ui version

### LINKED ISSUE #4816: Upgrade to latest jQuery UI
## Description of problem
https://blog.jqueryui.com/2021/09/jquery-ui-1-13-0-rc-2-released/ indicates that this next release is focused on compatibility with newer versions of jQuery. It seems good to adopt this version (even while the core is reducing its usage of jQuery UI) so that we don't prevent updates for folks.

## Description of solution
Update the JS Library (ensure jQuery Migrate is also up-to-date).

## Description of alternatives considered
Remove jQuery UI altogether (should those APIs be marked as deprecated?)

### LINKED ISSUE #5115: Update Jquery-UI version from 1.12.1 to latest 1.13.1
## Description of problem
DNN is using an old version of jquery-ui 1.12.1

## Description of solution
Upgrade jquery-ui to newer version from 1.12.1 to latest 1.13.1

## Description of alternatives considered
I will create a new PR including a solution

## Affected browser

* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer
* [X] Edge

### PR DESCRIPTION
**Pull request by armaganpekatik**
Fixes #5115
Closes #4816 

## Summary

DNN is using an old version of jquery-ui 1.12.1
Upgrade jquery-ui to newer version from 1.12.1 to latest 1.13.1

### CODE REVIEW

**Review by mitchelsellers — COMMENTED** [review]
Has this been validated to not impact the functionality of core DNN Features?  I believe the only major function is the modal dialogs (Login, Module Settings, etc).

**Comment by armaganpekatik** [comment]
> Has this been validated to not impact the functionality of core DNN Features? I believe the only major function is the modal dialogs (Login, Module Settings, etc).

No it hasn't. How to proceed these steps?

**Comment by mitchelsellers** [comment]
At a minimum after updating a package such as this we need to ensure that the standard flows that are utilizing this functionality are still operational without error.

This would involve at a minimum the setup of a clean instance using the artifacts from this build, and then validating that the items dependent upon this functionality are still operational.  I believe, at a minimum, the areas that use this are the Login popup and Module Settings.  But there might be more.

**Comment by armaganpekatik** [comment]
> At a minimum after updating a package such as this we need to ensure that the standard flows that are utilizing this functionality are still operational without error.
> 
> This would involve at a minimum the setup of a clean instance using the artifacts from this build, and then validating that the items dependent upon this functionality are still operational. I believe, at a minimum, the areas that use this are the Login popup and Module Settings. But there might be more.

My question is how to prove this as working. Is there any pass QBs? Or do you want me to just test it as Ad-Hoc?

**Comment by mitchelsellers** [comment]
We do not have any automated UI testing for this at this time, validation that pop-ups appear, without console errors is the best first-level validation at this time.

**Comment by armaganpekatik** [comment]
> We do not have any automated UI testing for this at this time, validation that pop-ups appear, without console errors is the best first-level validation at this time.

Who shall do this test? Is it ok if I do this as ad-hoc and say done? What kind of proof shall I bring?

**Comment by mitchelsellers** [comment]
Yes, totally fine for you.

Just before we take the time to also validate (which we will) we want to know that it has been tested.

Simply acknowledgment that you have tested is enough here

**Comment by armaganpekatik** [comment]
Installer is taken from https://dev.azure.com/dotnet/DNN/_build/results?buildId=71787&view=results

**1.13.1 Jquery-UI path is shown in ss**

Login screen with console
image

Extension settings with console
image

Tabs, sub-tabs and different layouts
image

Note: This `Uncaught TypeError: c is not a function` error is also there in the current version. It is not new.

**Review by valadas — APPROVED** [review]
Looks about right to me. Thanks!

Now if we would have a v9.10.x release, would we put this in it or should we target 9.11.x ?

**Comment by bdukes** [comment]
I believe there are more places that need to be updated to be consistently using the new version:

* [Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/contrib/jquery-ui.min.js](https://github.com/dnnsoftware/Dnn.Platform/blob/14e39b9bb68fef59e3851063bd9b001b60323627/Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/contrib/jquery-ui.min.js)
* [DNN Platform/Website/Resources/Shared/scripts/jquery/jquery-ui.js](https://github.com/dnnsoftware/Dnn.Platform/blob/14e39b9bb68fef59e3851063bd9b001b60323627/DNN%20Platform/Website/Resources/Shared/scripts/jquery/jquery-ui.js)
* [DNN Platform/Website/Resources/Shared/scripts/jquery/jquery-ui.min.js](https://github.com/dnnsoftware/Dnn.Platform/blob/14e39b9bb68fef59e3851063bd9b001b60323627/DNN%20Platform/Website/Resources/Shared/scripts/jquery/jquery-ui.min.js)
* [DNN Platform/Library/Framework/jQuery.cs (Default CDN URL)](https://github.com/dnnsoftware/Dnn.Platform/blob/9f83285a15d23203cbaad72d62add864ab5b8c7f/DNN%20Platform/Library/Framework/jQuery.cs#L35)
* [jQuery UI fix that can be removed](https://github.com/dnnsoftware/Dnn.Platform/blob/9f83285a15d23203cbaad72d62add864ab5b8c7f/DNN%20Platform/Website/js/Debug/dnn.js#L28-L84)
* [CodeEditor shared component loads 1.11.0 via CDN](https://github.com/dnnsoftware/Dnn.Platform/blob/9f83285a15d23203cbaad72d62add864ab5b8c7f/DNN%20Platform/Website/Resources/Shared/components/CodeEditor/mode/slim/index.html#L10-L11)
* [CKEditor Options always uses latest via CDN](https://github.com/dnnsoftware/Dnn.Platform/blob/9f83285a15d23203cbaad72d62add864ab5b8c7f/DNN%20Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Options.aspx.cs#L84)
* [CKEditor Browser always uses latest via CDN](https://github.com/dnnsoftware/Dnn.Platform/blob/9f83285a15d23203cbaad72d62add864ab5b8c7f/DNN%20Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs#L477)

**Comment by armaganpekatik** [comment]
> I believe there are more places that need to be updated to be consistently using the new version:
> 
> * [Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/contrib/jquery-ui.min.js](https://github.com/dnnsoftware/Dnn.Platform/blob/14e39b9bb68fef59e3851063bd9b001b60323627/Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/contrib/jquery-ui.min.js)
> * [DNN Platform/Website/Resources/Shared/scripts/jquery/jquery-ui.js](https://github.com/dnnsoftware/Dnn.Platform/blob/14e39b9bb68fef59e3851063bd9b001b60323627/DNN%20Platform/Website/Resources/Shared/scripts/jquery/jquery-ui.js)
> * [DNN Platform/Website/Resources/Shared/scripts/jquery/jquery-ui.min.js](https://github.com/dnnsoftware/Dnn.Platform/blob/14e39b9bb68fef59e3851063bd9b001b60323627/DNN%20Platform/Website/Resources/Shared/scripts/jquery/jquery-ui.min.js)
> * [DNN Platform/Library/Framework/jQuery.cs (Default CDN URL)](https://github.com/dnnsoftware/Dnn.Platform/blob/9f83285a15d23203cbaad72d62add864ab5b8c7f/DNN%20Platform/Library/Framework/jQuery.cs#L35)
> * [jQuery UI fix that can be removed](https://github.com/dnnsoftware/Dnn.Platform/blob/9f83285a15d23203cbaad72d62add864ab5b8c7f/DNN%20Platform/Website/js/Debug/dnn.js#L28-L84)
> * [CodeEditor shared component loads 1.11.0 via CDN](https://github.com/dnnsoftware/Dnn.Platform/blob/9f83285a15d23203cbaad72d62add864ab5b8c7f/DNN%20Platform/Website/Resources/Shared/components/CodeEditor/mode/slim/index.html#L10-L11)
> * [CKEditor Options always uses latest via CDN](https://github.com/dnnsoftware/Dnn.Platform/blob/9f83285a15d23203cbaad72d62add864ab5b8c7f/DNN%20Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Options.aspx.cs#L84)
> * [CKEditor Browser always uses latest via CDN](https://github.com/dnnsoftware/Dnn.Platform/blob/9f83285a15d23203cbaad72d62add864ab5b8c7f/DNN%20Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs#L477)

I am not sure if nothing goes wrong if we update these versions. Some of them look like component specific to me. This can be done through this  #5114

**Comment by mitchelsellers** [comment]
We need to have all versions of jQuery UI standardized before we can merge this pull request, as we do not want to introduce diverging versions.

**Comment by bdukes** [comment]
1.13.2 has been released

**Comment by nick-stepanenko** [comment]
Hi, team, @bdukes , @mitchelsellers , @valadas !

I've seen different issues related to JQuery/Jquery-UI upgrade:
https://github.com/dnnsoftware/Dnn.Platform/issues/4816 (Upgrade to latest jQuery UI)
https://github.com/dnnsoftware/Dnn.Platform/issues/5114 (Standardize jQuery Usage to Current Version)
https://github.com/dnnsoftware/Dnn.Platform/issues/5115 (Update Jquery-UI version from 1.12.1 to latest)
and this PR: https://github.com/dnnsoftware/Dnn.Platform/pull/5116


+ valuable comments from the issues above:
PR 5116: We need to have all versions of jQuery UI standardized before we can merge this pull request, as we do not want to introduce diverging versions.
Issue 5114: We need to ensure that all versions, including those loaded from a CDN are secure and up to latest versions. Ideally using the standardized registration processes for jQuery.


1) Could you please confirm, that Jquery and JQuery-UI are separate upgrades (e.g. release them in different DNN versions, so we can focus on JQuery-UI upgrade only and release it first)?

2) What do you mean by "standardized registration processes for jQuery"(I believe this should be also applied to JQuery-UI)?

Per this comment https://github.com/dnnsoftware/Dnn.Platform/pull/5116#issuecomment-1123197658 I can see 2 patterns: hard-coded urls(external components) and embedded Jquey/JQuery-UI files into DNN codebase.
I guess we can have:
1. Global config file to store external library URLs as parameters, so we can manage external JQuery-UI dependencies in one place
2. We could choose the same approach for local files, e.g. keep all the used versions locally and use global 'selector' parameter to define which version is used.
3. If you already have standards that I'm not aware of - could you please share them?

Best regards, Nick

**Comment by mitchelsellers** [comment]
#4816 & #5115 Are duplicate issues, and #4816 is the one that actually did the upgrade, as such #5116 (this item) can be closed as it is duplicate of the efforts from the other PR.

However, as noted by @bdukes there are other places that we need to standardize as part of the larger, OTHER jQUery issue #5114.

Given where we are today, I would love to be standardized 100% on using the DNN way to include this, but I don't believe it is fully possible.  (CKEditor for example loads in a page, not a DNN context to the DNN way to load isn't going to work)

We need to just make sure that we get everything updated, and to the SAME version.  If we can centralize the location/version that would be great, but might be a bit out of scope for the current time where we just need to get the upgrade done.

**Comment by nick-stepanenko** [comment]
Hi, @mitchelsellers !
Thanks for your response.

I'm a bit confused: https://github.com/dnnsoftware/Dnn.Platform/issues/4816 does not have any linked PRs, except this one (linked to the issue by @valadas  in this comment: https://github.com/dnnsoftware/Dnn.Platform/issues/4816#issuecomment-1121453664).

So, I consider this PR is the only one that contains JQuery-UI updates (although we still need to update all the JQuery-UI occurrences + it's better to update to the most actual version: 1.13.2) and fixes https://github.com/dnnsoftware/Dnn.Platform/issues/4816


Given that we are going to fix all the JQuery-UI occurrences, unsolved larger JQuery issue https://github.com/dnnsoftware/Dnn.Platform/issues/5114 would not be a blocker to merge this PR into the next upcoming release.

Please, confirm my understanding.

**Comment by mitchelsellers** [comment]
@nick-stepanenko wow, sorry about that, following links I got turned around a bit.

You are correct, I would propose the following.

- Update this PR (#5116) to the latest version of jQuery UI
- Expand this PR to also fix the other instances of jQuery UI Usage (https://github.com/dnnsoftware/Dnn.Platform/search?q=jquery-ui as a good starting point)
- Create a separate PR to address #5114 and standardize jQuery

**Comment by mitchelsellers** [comment]
@nick-stepanenko Are you planning any effort on this issue?

**Comment by hermetheuscoffee** [comment]
@nick-stepanenko since this issue was created, JQuery UI has released a newer build (1.13.2). Is it possible for this build to be used for this issue instead of 1.13.1? Thank you!

**Comment by bdukes** [comment]
@dnnsoftware/approvers This PR is ready for review.

I also upgraded jQuery Migrate from 3.2.0 to 3.4.0 and a couple of places we were still using jQuery 3.2.1 or 3.4.1 instead of 3.5.1

**Review by mitchelsellers — APPROVED** [review]
@bdukes You are awesome!

**Pull request merged**
