### PR TITLE
DNN-8218: Fix validation of SMTP server

### PR DESCRIPTION
**Pull request by janjonas**
See https://dnntracker.atlassian.net/browse/DNN-8218.

### CODE REVIEW

**Comment by galatrash-at-dnn** [comment]
@janijones, the changes will take care of the smtpserver when it is whitespaces, but if you enter ``:25`` or ``xxx:zzz`` you will receive similar errors. The first will throw the same error and the second an error related to converting text to integer.

IMO, the fix must be more robust and check against these types of issues.

**Comment by galatrash-at-dnn** [comment]
@janjonas any update on this?

**Comment by janjonas** [comment]
@galatrash-at-dnn Sorry, I haven't had any time yet. I will look into this as soon as I have some free time. I also saw your comment and I will provide an update for this pull request.

**Comment by galatrash-at-dnn** [comment]
@janjonas any ETA for this task?

**Comment by janjonas** [comment]
@galatrash-at-dnn: I created a new pull request (see #1915). This one can be deleted.

**Comment by galatrash-at-dnn** [comment]
Closing because a replacement PR 1915 is submitted.

**Pull request closed without merging**
