### PR TITLE
Update jspdf to version 1.3.2

### PR DESCRIPTION
**Pull request by thabaum**
#3116 is having issue printing PDF.  

## Summary

Please review make any adjustments I have added the latest version of jspdf code to this file.  This also needs tested...

### CODE REVIEW

**Comment by valadas** [comment]
@thabaum this has 189 changes :) Can you rebase or restart from the branch you are targetting please.

**Comment by thabaum** [comment]
crap... again i thought i was all good sorry...

**Comment by valadas** [comment]
No problem, happens to all of us :)

**Comment by david-poindexter** [comment]
Been there, done that!  I always cry for help from @bdukes 🤣

**Comment by thabaum** [comment]
I did this using github instead of VS... 
image

Is this normal to have to "skip" all the commits or can I push some majic button that does them all.

image

**Comment by thabaum** [comment]
Off the the races... back tonight. I can't believe there isnt a skip all button.  for one file change this is a bummer.  live an learn on PR at a time here 👍

**Comment by valadas** [comment]
If this started a a commit later than the target merge branch, it is a bit advanced to rebase. For a 1 file change, I usually just start over which takes less time :)

**Comment by thabaum** [comment]
redo...

**Pull request closed without merging**
