### PR TITLE
Upgrade Cake to 1.0.0-RC3

### PR DESCRIPTION
**Pull request by bdukes**
We're currently using RC1 of Cake 1.0.0 and RC2 was recently released.

### CODE REVIEW

**Comment by bdukes** [comment]
Looks like this is running into an issue with https://github.com/cake-build/cake/issues/3038, so this PR can hang out until next Cake release

**Comment by bdukes** [comment]
I did adjust this in a way to work around the RC2 issue, so this does appear to be working if we want to merge.  No hurry.

**Review by donker — APPROVED** [review]

**Comment by bdukes** [comment]
I've updated to the Cake 1.0.0-RC3 release, which is working fine now.

**Review by valadas — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
