### PR TITLE
ENH: Return Id when inserting item into PetaPoco repository

### LINKED ISSUE #5983: [Enhancement]: Return Id (primary key) of INSERTed entity in PetaPoco repository
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of problem

When calling DAL2 I`nsert()` method, a frequent strategy for determining the new Id / primary key of the inserted object is to requery the database directly after the insert to get the highest id. 

### Description of solution

Not only is this wasteful, in that it requires an additional database roundtrip, is not 100% reliable since another `INSERT` could have happened in between, but it's unnecessary. PetaPoco patches in the `INSERT`ed Id into the object, so you really only need to call Insert(item), and then item.Id has the new primary key. What would be even better is to return the Id as an additional Insert method, e.g. `int Id = repo.Insert<int>(item);`

### Description of alternatives considered

```
repo.Insert(item);
int Id = item.Id;
```

### Anything else?

_No response_

### Do you be plan to contribute code for this enhancement?

- [X] Yes

### Would you be interested in sponsoring this enhancement?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by johnhenley**
Close #5983

## Summary

ENH: Return Id when inserting item into PetaPoco repository

### CODE REVIEW

**Review by valadas — COMMENTED** [review]
Does'nt the exisint Insert method update the item itself with the new id in it ?

**Comment by johnhenley** [comment]
> Does'nt the exisint Insert method update the item itself with the new id in it ?

Yes it does. But it's not obvious and I see a lot of DAL2 examples where an insert is immediately followed by a (full) get then orderbydescending by create date then firstordefault-- all just to find the new ID.

**Comment by valadas** [comment]
> > Does'nt the exisint Insert method update the item itself with the new id in it ?
> 
> Yes it does. But it's not obvious and I see a lot of DAL2 examples where an insert is immediately followed by a (full) get then orderbydescending by create date then firstordefault-- all just to find the new ID.

No I mean does it not update the ID of the passed item to save ? Like one does not need an extra fetch to begin with ?

**Comment by johnhenley** [comment]
> > > Does'nt the exisint Insert method update the item itself with the new id in it ?
> 
> > 
> 
> > Yes it does. But it's not obvious and I see a lot of DAL2 examples where an insert is immediately followed by a (full) get then orderbydescending by create date then firstordefault-- all just to find the new ID.
> 
> 
> 
> No I mean does it not update the ID of the passed item to save ? Like one does not need an extra fetch to begin with ?

That is correct. All I added was a new method that returns the ID rather than void. Just to make it obvious because a lot of people write code like "var id = insert ...

**Comment by valadas** [comment]
Well one can't do var id = Insert.... was it returns void.

What I mean is that one should be able to do:
```cs
var dog = new Dog{Name="Clara", Age=2};
this.repository.Insert(dog);
var newId = dog.Id;
```

**Comment by valadas** [comment]
Well one can't do var id = Insert.... was it returns void.

What I mean is that one should be able to do:
```cs
var dog = new Dog{Name="Clara", Age=2};
this.repository.Insert(dog);
var newId = dog.Id;
```

**Comment by johnhenley** [comment]
> Well one can't do var id = Insert.... was it returns void.
> 
> 
> 
> What I mean is that one should be able to do:
> 
> ```cs
> 
> var dog = new Dog{Name="Clara", Age=2};
> 
> this.repository.Insert(dog);
> 
> var newId = dog.Id;
> 
> ```
> 
> 

Exactly why I thought the new method would be helpful, since it's a typical code pattern.  
var newId = this.repository.Insert(dog);

But no problem if you don't think it's worthwhile.

**Comment by valadas** [comment]
Well, I am not opposed on the idea, but this way means clearing cache to get an ID that is already available and potentially an additional database roundtrip... Plus the original way would also return the results of any other computed and/or autogenerated fields in the entity... Also in this scenario what would be the type of a compound key ?

**Pull request closed without merging**
