### PR TITLE
DNN-6615: Users cannot subscribe to public security role

### PR DESCRIPTION
**Pull request by sleupold**
fixed version of sproc GetServices

### CODE REVIEW

**Comment by galatrash-at-dnn** [comment]
@sleupold please re-fix for DNN 9.2.0 release

**Comment by sleupold** [comment]
I will review and resubmit asap

**Comment by mitchelsellers** [comment]
Closing, @sleupold will be submitting a new pull request

**Comment by billwitham** [comment]
it appears this never made it over to DNN9.3 either. I still this as an issue.

**Pull request closed without merging**
