### PR TITLE
Upgrade NUnit to 3.13.3 and Test Adapter to 4.2.1

### PR DESCRIPTION
**Pull request by bdukes**
## Summary
This PR upgrades NUnit and NUnit3TestAdapter

### CODE REVIEW

**Comment by mitchelsellers** [comment]
Looks like the build is failing on this one

**Comment by bdukes** [comment]
@mitchelsellers build's fixed (apparently Visual Studio failed halfway through updating the NuGet references the first time)

**Review by mitchelsellers — APPROVED** [review]

**Review by david-poindexter — APPROVED** [review]
Should this be against `develop` or was it intentionally against `release/9.11.0`?

**Comment by david-poindexter** [comment]
Looks like there are some conflicts now as well.  CC @bdukes

**Comment by bdukes** [comment]
I've resolved conflicts, rebased on `develop` and changed the base to `develop`.

**Review by valadas — APPROVED** [review]

**Pull request merged**
