### PR TITLE
Broken language selector menu

### PR DESCRIPTION
**Pull request by SCullman**
DNN-6576
LanguageSelector Menu is broken

### CODE REVIEW

**Comment by jbrinkman** [comment]
Stefan,
  Can you fix your repository and resubmit so it only includes this one change? You have likely branched from an old version of the repository.

**Comment by SCullman** [comment]
Yes, I will try. My job is now how to update my cloned repository here on github. I created that in preperation for the dnn connect meeting in Italy last year.

**Comment by cathalconnolly** [comment]
you can sync your repo by configuring an upstream provider and then merging i.e.
git remote add upstream https://github.com/dnnsoftware/Dnn.Platform.git
git checkout development
git merge upstream/development

**Comment by jbrinkman** [comment]
Cathal,
  Maybe you could do a quick video of the process and write-up a short blog. It seems that we see this same problem from a number of potential contributors.

Thanks,
Joe Brinkman
Co-Founder, VP of Technology and Community Relations
DNN Corp. | www.dnnsoftware.com<http://www.dnnsoftware.com/>
o 650.288.3154 | m 330.242.7742
Twitter <https://twitter.com/jbrinkman> | Facebook <https://www.facebook.com/joe.brinkman> |  LinkedIn  <http://www.linkedin.com/in/joebrinkman/> | Google+<https://plus.google.com/u/0/102047675986512918810/posts> | DNN<http://www.dnnsoftware.com/Activity-Feed/userId/8129>

**Comment by liffeyd** [comment]
And a presentation for DNN-Connect in France on May 29th ;)

**Comment by cathalconnolly** [comment]
i'll add it to my list @jbrinkman

**Comment by SCullman** [comment]
Thanks Cathal. Is your list still uncomplete?

Step 3 failed, now I am doing a 
git fetch upstream first

When the merge is completed, should I push first to origin?

**Comment by SCullman** [comment]
That did not work, I am getting a lot of merge conflicts.

It might be better to delete my repository on github and start from the beginning. 
It is very frustrating to spend several hours just for a pull request of 4 additional words in 2 files.
However, I would prefer If I would be able to fix my local (and origin) repositories, as I want to send a few more pull requests in the next time.

**Comment by cathalconnolly** [comment]
@SCullman yes, I do a push to origin after that (typically though I don't see merge conflicts)

**Comment by EPTamminga** [comment]
@liffeyd : I intend to submit a GitHub session and Q&A for DNN-Connect in France (and prepare to to the show without internet connection for everyone).

**Comment by cathalconnolly** [comment]
@SCullman if you repo is very old then you can do the following:
git fetch upstream
git rebase upstream/development

**Comment by EPTamminga** [comment]
@SCullman If there are no local changes waiting to be pushed/pulled, an easy way is to restart fresh and be fully synced is to delete your clone & fork, and do a fork & clone again.

**Comment by SCullman** [comment]
Thanks everybody. The easiest way yesterday was indeed to delete clone and fork and to start again. However as this takes an amount of time to clone from beginning, I hope that was the last time. Git rebase upstream/development sounds faster :+1: 

Ernst Peter, I doubt that a git session without internet connection will work. You should at least bring a local git server and a wifi access point with you.

**Pull request closed without merging**
