### PR TITLE
DNN-4734: Full URL as ReturnURL does not work anymore

### PR DESCRIPTION
**Pull request by stephen-lim**
Fix https matching logic in ReturnURL.

### CODE REVIEW

**Comment by cathalconnolly** [comment]
Stephen, this PR has 5 different commits, can you please clean up your branch so it only has the dnn-4734 one (i.e. rebase) or else branch off latest

**Comment by stephen-lim** [comment]
Hi Cathal

Sorry about that. Please cancel the pull request and I will try to submit another one.





---- On Thu, 21 May 2015 16:36:12 -0400 Cathal Connolly&lt;notifications@github.com&gt; wrote ---- 

Stephen, this PR has 5 different commits, can you please clean up your branch so it only has the dnn-4734 one (i.e. rebase) or else branch off latest

**Comment by cathalconnolly** [comment]
closing on behalf of the original reporter.

**Comment by bdukes** [comment]
this PR is superceded by #540

**Pull request closed without merging**
