### PR TITLE
Changes to Insert DateTime at start of upgrade

### PR DESCRIPTION
**Pull request by mitchelsellers**
Changes to support DNN-7280 for enhanced experience when upgrading.  Localization values used for UpgradeStarted.Text were obtained from Google Translate, and a few validated to be correct.  Would appreciate a review from native speakers

### CODE REVIEW

**Comment by cathalconnolly** [comment]
not sure how to process this - typically for translations you just add any new keys into the existing en-us resx file and then when I generate the difference files for the translators they provide the translations -I don't know if accepting the translations directly will cause any issues -in this case as it's the installation files which we ship I think it should be fine, but I'll probably check with the translators just in case

**Comment by mitchelsellers** [comment]
@cathalconnolly if I need to pull back the changes to the others by all means I'll modify my repro and update the pull request.  Wasn't 100% sure on this one for process language

**Comment by vmasanas** [comment]
There's only 1 change in the resx file, although most of the localized files seem changed. My suggestion would be to NOT include the localized values in the pull request and let the translators provide the new key.

**Comment by mitchelsellers** [comment]
@vmasanas Done!  I updated things to remove the other changes.

**Pull request merged**
