### PR TITLE
DNN-7446

### PR DESCRIPTION
**Pull request by BehnamEmamian**
These fields are needed to fetch from Facebook.

### CODE REVIEW

**Comment by BehnamEmamian** [comment]
Hi
did you check it? it solve my problem on this site
http://crm.persianmigrant.com/

facebook api in version 2.4 removed default parameters so we should tell api witch parameters we need to fetch.

**Comment by cathalconnolly** [comment]
FYI https://dnntracker.atlassian.net/browse/DNN-7446 is planned for 8.0.0

**Comment by cathalconnolly** [comment]
this has also been done as #880 -ive added a comment to that to ensure that this PR is processed and you get credit for your work.

**Comment by antoniodgonzalez** [comment]
#880 is now merged

**Pull request closed without merging**
