### PR TITLE
Modify Next Button on install wizard

### PR DESCRIPTION
**Pull request by uzmannazari**
## Summary
Modification of the next button in the get package information step, whose name could not be called from language resource files and could not be translated in multilingual portals.

### CODE REVIEW

**Comment by mitchelsellers** [comment]
Can we get more detail on this particular change?  I don't see any addition to the resource files to then set this value, yet it was pulling from localization files already.

**Comment by uzmannazari** [comment]
{Localization.get("Next.Button")} just added. 
The element is already available in the language resource file

**Review by valadas — APPROVED** [review]
Correct, fiund it here https://github.com/dnnsoftware/Dnn.Platform/blob/06e467e84fad58805e0fb04b10ec49d09e9a7144/Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Extensions/App_LocalResources/Extensions.resx#L1068

LGTM

**Review by mitchelsellers — APPROVED** [review]
Thanks for the extra information that this was already in the language pack

**Comment by uzmannazari** [comment]
> Correct, fiund it here
> 
> https://github.com/dnnsoftware/Dnn.Platform/blob/06e467e84fad58805e0fb04b10ec49d09e9a7144/Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Extensions/App_LocalResources/Extensions.resx#L1068
> 
> LGTM

Thanks mr @valadas and @mitchelsellers

**Pull request merged**
