### PR TITLE
Merge CKEditor Provider

### PR DESCRIPTION
**Pull request by bdukes**
This PR merges the `development` branch from https://github.com/dnn-connect/CKEditorProvider into DNN Platform (moving that source code to `DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE`).  This does _not_ yet do anything to include it in the main build process.

### CODE REVIEW

**Comment by mitchelsellers** [comment]
When we merge this, I assume we want to Squash?

**Comment by bdukes** [comment]
No, we want to merge, this will let us retain the CKEditorProvider history

**Comment by mitchelsellers** [comment]
Ok, sounds good

**Review by valadas — APPROVED** [review]
Looks good to me until we get this building but yeah, we kinda need to merge to continue. I gonna go move issues from the other repo here that are still relevant.

**Review by david-poindexter — APPROVED** [review]

**Pull request merged**
