### PR TITLE
Fixed Memory Leak in Web API Modules

### PR DESCRIPTION
**Pull request by ahoefling**
Fixes: #3186

## Summary
Fixes the significant Memory Leak discussed in #3186 in Web API Modules. I duplicated the test I performed in https://github.com/dnnsoftware/Dnn.Platform/issues/3186#issuecomment-544974596

### Test Result
* 506,787 requests in 360 seconds: 257.6 MB of Memory
image

This is a marked improvement from 11,553.2 MB of Memory

### Description of Changes
I removed the `DnnHttpControllerActivator` which is not the recommended approach for Dependency Injection in Web API 2 by Microsoft. This was an oversight when Dependency Injection was originally implemented in v9.4.0.

I created a `DnnDependencyResolver` which handles communication with the `Globals.DependencyProvider` and applies the implementation of `IDependencyResolver` to the Web API 2 Configuration. This allows the controller life-cycle to be handled by ASP.NET Web API 2

If you want more information on this, check out the [Docs](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/dependency-injection) from Microsoft

### CODE REVIEW

**Comment by david-poindexter** [comment]
Fantastic @ahoefling!

**Comment by mitchelsellers** [comment]
\azp run

**Comment by ahoefling** [comment]
Some unit tests failed that I need to fix, if you want to test this against the happy path please clone the repo and run the create install command
```
./build.ps1 -Target CreateInstall
```

**Comment by valadas** [comment]
Awesome @ahoefling I have a test bed here ready to upgrade and compare, I created a test that calls 5 endpoints 20 times with different parameters in a module that uses the Dependency Injection that was added in 9.4.0 and also Entity Framework 6.

With Dnn 9.4.1, I rand that test for 5 minutes and memory usage kept growing up to 506MB after 5 minutes. I let the site cool down for 15 minutes and that value never went down significantly from there.

With the build from this PR and the same test, it stopped growing at 217MB, then I let the site cool down and it went back to about 170MB.

Also I see nothing broken on the site so far.

So this looks good to me.

**Comment by valadas** [comment]
Just the build is failing, I think because of a test, other than that, looks good to me.

**Comment by ahoefling** [comment]
I fixed the failing unit tests and updated the `IServiceProvider` mock to build a full Service Provider. This is much easier than trying to mock it out. Doing so allowed me to add more unit tests to the new `DnnDependencyResolver` so we now have 100% code coverage over the new class that this PR adds 🥂 .

After the successful PR build I grabbed the installer and ran the same test provided in the issue.

Memory prior to the load test
image

Memory after the load test
image

Interestingly enough I had less memory allocation in the IIS Worker Process than before. It appears this does solve the memory leak

**Comment by bdukes** [comment]
🎉 Thanks @ahoefling!

**Pull request merged**
