### PR TITLE
Update JwtController.cs

### PR DESCRIPTION
**Pull request by thienvc**
Fix unapproved user passed jwt login https://github.com/dnnsoftware/Dnn.Platform/pull/4266#issuecomment-720211413

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dnnsoftware/Dnn.Platform?pullRequest=4274) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dnnsoftware/Dnn.Platform?pullRequest=4274) before we can accept your contribution.<br/><br/>:x: thienvc [sign now](https://cla.dotnetfoundation.org/dnnsoftware/Dnn.Platform?pullRequest=4274)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dnnsoftware/Dnn.Platform?pullRequest=4274) it.</sub>

**Comment by valadas** [comment]
I don't understand this PR, from a look at it, it just groups the 2 conditions and it would return null only when tracing is enabled. Can you explain a bit the purpose of this ?

**Comment by thienvc** [comment]
> I don't understand this PR, from a look at it, it just groups the 2 conditions and it would return null only when tracing is enabled. Can you explain a bit the purpose of this ?

when User unapproved and tracing is NOT enabled it would not return null, it passed and return a valid User but this user is unapproved

**Comment by valadas** [comment]
Oh, I totally misread that, sorry.

Since this relates to security, please email this to security@dnnsoftware.com we will keep track of this out of the public world.
Thanks

**Pull request closed without merging**
