### PR TITLE
DNN-6798: Allow CSV, XSLT file extensions

### PR DESCRIPTION
**Pull request by stephen-lim**

### CODE REVIEW

**Comment by sleupold** [comment]
I vote against this change for upgraded sites, it might be added to the default template though.

**Comment by stephen-lim** [comment]
I have modified it so it now only affects the default host template being installed.

**Comment by sleupold** [comment]
thanks a lot!

**Comment by stephen-lim** [comment]
You're welcome :)

**Comment by bdukes** [comment]
I squashed and rebased the relevant commits (ignoring your unrelated changes for DNN-5873) and have merged them into development (for 7.4.2)

**Pull request closed without merging**
