### PR TITLE
DNN-6265 Update OAuthClientBase to support optional parameters

### PR DESCRIPTION
**Pull request by skydnn**
Updated OAuthClientBase to support the optional parameter "resource" of the OAuth V2 standard, as this field is required to support the Microsoft Azure Active Directory OAuth implementation.
Also added UrlEncode logic to the APISecret, as apparently secret keys generated by Azure are not url friendly. 
Tested implementation on dev box and an Azure site for LiveConnect, Google, Facebook and Azure Active Directory.

### CODE REVIEW

**Comment by skydnn** [comment]
Looks like I left off the bug number in the title.  It is DNN-6265

**Comment by cathalconnolly** [comment]
thanks -we're in code-freeze for 7.4.0, so this will be processed for the 7.4.1 release

**Comment by tatigo** [comment]
I'm having issues integrating UseOpenIdConnectAuthentication to Azure (from Owin startup class). 
I'm on DNN  7.04. Do I need to pull the most current Dnn version?

**Comment by bdukes** [comment]
@tatigo it looks like this change was included in 7.4.1, so if you're planning to use DNN's `OAuthClientBase` to create your authentication provider, than you will need to get that version of DNN.

**Pull request merged**
