### PR TITLE
DNN-4505: improve robustness and readability

### PR DESCRIPTION
**Pull request by sleupold**

### CODE REVIEW

**Comment by jbrinkman** [comment]
There are no details on why this change is needed.

**Comment by galatrash-at-dnn** [comment]
@sleupold please fix conflicts and submit for DNN 9.2.0 (or wait for the release after).

**Comment by sleupold** [comment]
I will review and resubmit asap

**Comment by mitchelsellers** [comment]
Closing, @sleupold will be submitting a new pull request

**Pull request closed without merging**
