### PR TITLE
Remove samples folder from CKEditor

### PR DESCRIPTION
**Pull request by bdukes**
The CKEditor upgrade includes a `samples` folder that wasn't in the previous version. Among other things, it includes `php` files which get flagged by the Security Analyzer. These shouldn't be included.

### CODE REVIEW

**Comment by bdukes** [comment]
@skamphuis I didn't see any usages of this `samples` folder, does that seem right to you that we can remove it altogether?

**Review by valadas — APPROVED** [review]
Good idea

**Comment by skamphuis** [comment]
Yes, that does seem right. I obviously just unpacked the editor there.

Another thing I though of the other day: should we remove the old one in the installer package?

**Review by mitchelsellers — APPROVED** [review]

**Comment by bdukes** [comment]
@skamphuis yes, removing the old files in the installer makes sense to me

**Pull request merged**
