### PR TITLE
bug/DNN-7068

### PR DESCRIPTION
**Pull request by robsiera**
This fix for [DNN-7068](https://dnntracker.atlassian.net/browse/DNN-7068) has [already been merged](https://github.com/dnnsoftware/Dnn.Platform/pull/630) into v8.
But this a request to merge it into v7.4.2.

### CODE REVIEW

**Comment by sleupold** [comment]
this would be helpful for many users

**Comment by ohine** [comment]
:+1: I'm all for merging this into 7.4.2, but the final decision is up to Joe.

**Comment by iJungleboy** [comment]
+1 - IMHO critical :(

**Comment by iJungleboy** [comment]
:+1:

**Pull request merged**
