### PR TITLE
Fixed a bug that prevented selecting folders for Browser Root and Default Upload folders in HtmlEditor

### LINKED ISSUE #5100: CKEditor missing default folder for images
## Description of problem
Administrators still used to the RadEditorProvider are missing the option to specify a default folder for images in the Editor Provider Settings (and obviously in the file browser).
This is keeping sites from being upgraded to the latest version of DNN, with CKEditorProvider, or at least keeps them from removing Telerik.

## Description of solution
Options should be added to CKEditorProvider settings, to specify a default browser folder for images, and a default upload folder for images.

## Description of alternatives considered
I tried to think of other ways to achieve the same thing, but could think of any.

## Screenshots
image
image

## Additional context
I have a PR almost ready for this change.

## Affected browser
not browser related

### PR DESCRIPTION
**Pull request by skamphuis**
Closes #5100 

## Summary
This PR adds  settings for
* Browser Root Folder for images
* Default Upload Folder for images

These settings are used when the user opens the browser for images, or uploads an image.

image

Often, it is desirable that images are kept separated from documents, and with these settings, it is no longer up to the content editor to remember to select the correct folder.

### CODE REVIEW

**Review by donker — APPROVED** [review]
Looks good to me. Nice feature.

**Comment by donker** [comment]
Note: the changes in #5123 include the changes in this PR.

**Review by valadas — APPROVED** [review]
Looks good, thanks

**Comment by valadas** [comment]
@donker  #5123 does not have all the commits (hash) as this one. Also you put the 9.11.0 milestone, if so we need to target the release/9.11.0 branch if not, then we need to change that milestone. What way do we want to go ?

**Comment by mitchelsellers** [comment]
@skamphuis can we get a comparison between this one #5122 and #5123, as it does not appear that this one has everything from the other, but it does have some.  

Ideally, I'd like to see if we can get to a single PR for these changes

**Comment by skamphuis** [comment]
@mitchelsellers I can create a single pr for them if that's easier. I based the second feature branch on the first, so I'm pretty sure the last one contains all change. But let me just create a single pr for both changes and go from there. 

I will do so in the morning.

**Comment by valadas** [comment]
Oh, I just merged this one and will help on the other if a rebase is needed...

**Pull request merged**
