### PR TITLE
DNN-7769: New default skin Xcillion

### PR DESCRIPTION
**Pull request by EPTamminga**
Expanded installed skin. We coudl also create an install pack and extension.
Please note that the original source files (not minified & the .less files) are still in the original repo (https://github.com/XCESS-NL/xcillion)

### CODE REVIEW

**Comment by hismightiness** [comment]
How is this pronounced?  Does it have anything to do with the LOLKING game?  (I don't know anything about it, just googled the word.)  Hopefully, there's no copyright issues if it is. :)

**Comment by EPTamminga** [comment]
No connection to any game. We thought it up as a fantasy word. 
We did not check copyrights on the word itself. Anybody an idea?

**Comment by agrueso** [comment]
I have merged this Pull Request. Finally, we are going to create a package with its content but this task will be part of a different Pull Request.

**Comment by EPTamminga** [comment]
@agrueso @jbrinkman 
I can supply the skin & the site template also as installable packages i.s.o. including the individual files in de various folders. That might be a better solution? If so, we can reverse this PR and I will create a new one.

**Pull request merged**
