### PR TITLE
StyleCop fixes

### PR DESCRIPTION
**Pull request by bdukes**
## Summary
This PR resolves all StyleCop warnings from SA10xx through SA15xx.

Many of the naming rule violations would result in breaking changes, so those have been suppressed.
I tried to keep each commit to a single rule, though did some occasional small cleanup related to changes I made.
I also answered _Yes_ whenever asked to resolve conflicting line endings.

### CODE REVIEW

**Review by valadas — APPROVED** [review]
Looks good to me

**Review by mitchelsellers — APPROVED** [review]

**Comment by valadas** [comment]
Microsoft does not want me to login today, @bdukes do you know if the failed tests are a fluke or related to these changes ?

**Comment by bdukes** [comment]
It appears to be the same tests failing consistently, so I think it's related to these changes, but I haven't been able to reproduce locally yet.

list of failing tests

**Comment by bdukes** [comment]
@valadas I found a renamed private variable that was being accessed via reflection in a test, all issues resolved now.

**Comment by valadas** [comment]
Awesome, great catch! I downloaded the CI build and tried a couple things, nothing went out in smoke, so great improvement!

**Pull request merged**
