### PR TITLE
Keep track of whether in global assets mode

### PR DESCRIPTION
**Pull request by bdukes**
## Summary
I haven't had a chance to test this, but I believe this should pass through to the API whether the module is in Global Assets mode or for the current portal.

### CODE REVIEW

**Review by valadas — APPROVED** [review]
You are awesome!

**Comment by valadas** [comment]
It looks right but we have another problem (don't let this hold merging this PR as it's probably not caused by this)...
But we are now missing all the scripts in the module zip:
image

I'll try to figure out what happened with that the next weekend...

**Review by mitchelsellers — APPROVED** [review]

**Comment by valadas** [comment]
> I'll try to figure out what happened with that the next weekend...

Hmm, I tried a build from develop and fixed some stuff on another PR and the files were there, nothing in this PR appears to possible be able to break that. @bdukes could you rebase on develop to see if the files are there with a new build that includes that fix...

**Comment by bdukes** [comment]
I've rebased @valadas

**Pull request merged**
