### PR TITLE
Allow superusers upload to any portal

### LINKED ISSUE #3850: FileUpload validation code prevents super users from uploading to the default portal
## Description of bug
#3654 introduced a protection mechanism to the FileUpload component (validation code) to make sure the uploads come from a trusted FileUpload component, rendered **to current portalID** and for the current user ID. This protection is good but it currently prevents superusers from uploading files to the default portal (ID = -1) for example, or to any portal different than the one where the FileUpload component was rendered to.
Specifically, this affects the Assets module in Evoq, where the FileUpload component is used to upload files to any portal visible to the user.

## Steps to reproduce
These steps are specific to Evoq, but can apply to other scenarios as well:
1. Open the Assets panel
2. Click on "Global Assets"
3. Upload a file

## Current behavior
"Bad Request" error message is returned.

## Expected behavior
File should get uploaded without issues.

## Screenshots
image

## Error information
```
2020-06-23 14:46:02.945+00:00 [DNN-QA-01][D:2][T:38][ERROR] DotNetNuke.Web.InternalServices.FileUploadController - System.InvalidOperationException: Bad Request
   at DotNetNuke.Web.InternalServices.FileUploadController.UploadFile(Stream stream, Int32 portalId, UserInfo userInfo, String folder, String filter, String fileName, Boolean overwrite, Boolean isHostPortal, Boolean extract, String validationCode)
```

## Affected version
* [X] 10.00.00 alpha build (in development)
* [X] 09.06.01 latest supported release

## Affected browser
* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer 11
* [X] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

### PR DESCRIPTION
**Pull request by daguiler**
Fixes #3850

## Summary
Removes the validation code check for superusers.

### CODE REVIEW

**Comment by mitchelsellers** [comment]
This check was is required to ensure that files that are uploaded are "images".  This validation rule SHOULD apply to all user types, we will not be merging this request.

**Comment by daguiler** [comment]
Hi @mitchelsellers 
Maybe we can take a second look at this?
The purpose of the validation code is not to check whether uploaded files are images.
Thanks.

**Comment by mitchelsellers** [comment]
@daguiler Where this change was in the IsImage check, is checking against the image type

**Comment by daguiler** [comment]
The change is in the `UploadFile` method, the one below :-)

**Comment by daguiler** [comment]
but I see how this can be confusing

image

**Comment by mitchelsellers** [comment]
@daguiler Given the nature of this, can you email me please rather than discussing here.

**Pull request closed without merging**
