### PR TITLE
Send email to administrator when an unauthorized user requests a password reset

### LINKED ISSUE #5245: Send email notification to administrator when an unauthorized user requests a password reset
## Description of problem
Users who have been unauthorized request a password reset. They receive an email but cannot login and/or reset their login because they are unauthorized. 
## Description of solution
Email administrator when a user who is unauthorized requests a password reset. Then the administrator can verify that it is a valid request, and authorize the user so they can login.
## Description of alternatives considered
Provide a clear and concise description of any alternative solutions considered.

## Screenshots
If applicable, provide screenshots to help explain the problem and/or enhancement.

## Additional context
Add any other context about the enhancement that may be helpful with implementation.

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

### PR DESCRIPTION
**Pull request by johnhenley**
Closes #5245

## Summary

Email administrator when an unapproved user requests a password reset. Then the administrator can verify that it is a valid request, and if so, authorize the user and send a new password reset.

### CODE REVIEW

**Comment by johnhenley** [comment]
* I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

**Comment by bdukes** [comment]
@johnhenley you need to write `@microsoft-github-policy-service agree` to tell the bot you agree with that statement

**Review by mitchelsellers — COMMENTED** [review]
I understand the intent here, but I'm slightly concerned that this could allow someone to abuse the system by constantly requesting a forgotten password and overwhelming administrators otherwise?

@dnnsoftware/approvers thoughts?

**Comment by bdukes** [comment]
I think the value is greater than the potential for abuse.

**Review by mitchelsellers — APPROVED** [review]

**Comment by johnhenley** [comment]
> I understand the intent here, but I'm slightly concerned that this could allow someone to abuse the system by constantly requesting a forgotten password and overwhelming administrators otherwise?
> 
> 
> 
> @dnnsoftware/approvers thoughts?

@mitchelsellers understand and agree with your concerns about potential for abuse. What are your thoughts on adding a PasswordResetOutstandingRequestCount  (or just a flag that a request is outstanding) to UserInfo and only sending to administrator on first request?

**Review by bdukes — APPROVED** [review]

**Comment by bdukes** [comment]
Thanks!

**Pull request merged**
