### PR TITLE
correct fix for DNN-6518

### PR DESCRIPTION
**Pull request by sleupold**
use portal default language, if no culture code is specified

### CODE REVIEW

**Comment by jbrinkman** [comment]
How extensively was this change tested?  There are many places in core platform and in 3rd party systems which rely on GetPortals returning data correctly in all scenarios.

**Comment by sleupold** [comment]
stored procedure has been tested on live installs.
Code changes cannot result in a different result as before the first fix.
The previous version of the fix would return all sites with any portal language, if the requested language is not used for the site, i.e. requesting GetPortals('zn-CH') would return all sites, even if they don't have this language assigned.

**Comment by jbrinkman** [comment]
I have tested this based on both upgrades and new installs and have included it with some modification to ensure that we retained behavioral compatibility with prior versions.  The new version is still undergoing internal testing but should be merged either today or tomorrow.  Thanks for catching the issue Sebastian.

**Comment by cathalconnolly** [comment]
tested and merged into release/7.4.0

**Pull request closed without merging**
