### PR TITLE
3936 url provider uninstall

### PR DESCRIPTION
**Pull request by stephen-lim**
Fixed the uninstall URL provider was throwing object reference not found exception. I tested and it uninstalls correctly now.

### CODE REVIEW

**Comment by cathalconnolly** [comment]
thanks Stephen - however looking at this I see a mass of unrelated changes. This isn't uncommon as opening the sln in vs.net can sometimes "touch" the csproj files. If you can update your branch to remove those it would be a great help (if using a tool such as sourcetree click the csproj files and discard the changes)

**Comment by stephen-lim** [comment]
Hi Cathal

Sorry, I'm familiar with SVN, but I'm still learning GIT. If you can email me privately and assist would be much appreciated. I like to contribute more and I made several pull requests lately suffering from multiple commits that I'm unsure how to properly clean up. :(

**Comment by cathalconnolly** [comment]
I'm about to go on holiday for a week so don't have time I'm afraid - hopefully someone else can help.

When I return I'll try to record a video/set of steps to help with this as it's not uncommon (though if you update your clone of dnn and then branch and then apply your change [i.e. cherrypick] it's an easy way to work around it, if you'd like to avoid having to do a bunch of git rebase commands)

**Comment by stephen-lim** [comment]
I'll wait for your return and the video if it helps. Right now, I have several open pull requests (~3) submitted from different branches. If you could in anyway accept them and just ignore the few csproj file diffs that don't matter would be incredible helpful since it's going to be a problem to update that many branches. I don't want to mess them up unless you tell me there's an easy way to update the branches without redoing the work.

**Comment by EPTamminga** [comment]
The easiest way to handle this is: 
- save your changes somewhere on disk
- do a get latest on the DNNPlatform repo
- push these changes to your gig hub repo
- set your local repo to the develop branch of DNNPlatform 
- create separate branches for each of your changes 
- copy the saved changes one by one and commit each of them
- reset to the development branch for each change, do you get small and individual commits
Now create pull requests for each change. 

Suggestion:  Use SourceTree as local management tool.

**Comment by stephen-lim** [comment]
Thank you for the suggestion. The create branch approach is what I did originally but I accidentally included the .csproj changes in my commit. It would be fine if i had just one pull request. Unfortunately, i have submitted several pull requests and they all suffer from the extra .csproj commits and the copy back approach is tedious. In SVN, there's an easy way to exclude certain files on commit without ignoring them in the source control. GIT doesn't seem to have this ability, and we have to cherry pick to exclude them in the commit :(

**Comment by EPTamminga** [comment]
Git has the .gitignore file that lists all files that must be ignored. In addition to that SourceTree would help you to manage the files to be included in commit and pull requests.

**Comment by stephen-lim** [comment]
Please close this pull request. In the end, I'm resubmitting entirely new pull request. It seems like that was the only way to clean up my messed up branches.

**Comment by bdukes** [comment]
this PR is superceded by #560

**Pull request closed without merging**
