### PR TITLE
DNN-5829 SEO Sitemap provider needs defensive coding

### PR DESCRIPTION
**Pull request by vmasanas**
Added defensive coding and exception logging to url generation to prevent the sitemap to fail in case some providers fail with url generation

### CODE REVIEW

**Comment by vmasanas** [comment]
Seems one of the files got incorrect line endings, not sure how I can fix this.
In case the merge can be done from this, the only changes I did where around line 104:

List<SitemapUrl> urls = new List<SitemapUrl>();
try
{
urls = _provider.GetUrls(PortalSettings.PortalId, PortalSettings, SITEMAP_VERSION);
 }
 catch (Exception ex)
 {
 Services.Exceptions.Exceptions.LogException(new Exception(Localization.Localization.GetExceptionMessage("SitemapProviderError",
 "URL sitemap provider '{0}' failed with error: {1}",
 _provider.Name, ex.Message)));
 }

**Comment by cathalconnolly** [comment]
cheers, i'll do it as a manual merge and just discard the files with bad endings (not sure either how that happened, though I've seen it before)

**Comment by cathalconnolly** [comment]
are you sure they're the only changes, I see two new resx keys - SitemapProviderError.Text and SitemapUrlGenerationError.Text

**Comment by vmasanas** [comment]
I was refering to the changes in SitemapBuilder.cs.

**Comment by cathalconnolly** [comment]
thanks

**Comment by jbrinkman** [comment]
Manually merged and committed.

**Pull request closed without merging**
