### PR TITLE
Add DI support to scheduler

### LINKED ISSUE #3602: Support Dependency Injection from Scheduler
## Description of problem
There is no way to access services in the Dependency Injection container from a scheduler client.

## Description of solution
When DNN creates a scheduler client, it needs to use the DI container.

## Additional context
Based in a discussion at https://dnncommunity.org/forums/aft/890 and via https://dnntag.slack.com/

### PR DESCRIPTION
**Pull request by bdukes**
Fixes #3602, thanks for the direction @dimarobert!

### CODE REVIEW

**Comment by bdukes** [comment]
@mitchelsellers I've tested that this works with existing scheduler clients and a new one that takes an `INavigationManager`.  I have not done any perf testing on it.

**Comment by dimarobert** [comment]
@bdukes I think that `ActivatorUtilities.CreateInstance` can get by without the SchedulerClient registrations in the `AddSchedulerClients`. It uses the `IServiceProvider` to resolve the dependencies of the instantiated type not the type itself.
If that is the only reason that the clients are registered you should give it a try without the registrations and see if it still works.

**Comment by bdukes** [comment]
Thanks @dimarobert, you're right, it works perfectly without the registrations.  I've pushed that change, @mitchelsellers.

@mitchelsellers do you think it's worth looking into using `CreateFactory` instead of `CreateInstance`?  We'd need to introduce a static `ConcurrentDictionary` or something like that to store the factory delegates.

**Comment by mitchelsellers** [comment]
@bdukes I think we take this as it is now, as this gives us DI support while maintaining the current limitation.  I think a future change to use CreateFactory would be awesome, but it is a larger risk.

**Comment by bdukes** [comment]
@dnnsoftware/approvers can I get a second approval?

**Comment by valadas** [comment]
Any reason why this got closes @bdukes ?

**Comment by bdukes** [comment]
@valadas sorry, I must have accidentally hit the _Close and comment_ button

**Comment by ahawes-clarity** [comment]
Can you tell me how add the dependencies to a SchedulerClient? Do we just add them to the constructor?

**Comment by bdukes** [comment]
Yes, if you've registered `IThingamajigger` with the `IServiceCollection` in your `IDnnStartup`, you can add that as a constructor argument to your `SchedulerClient` implementation. For example:

```
    public class AwsConfigurationTask : SchedulerClient
    {
        private readonly ISettingsService settingsService;

        private readonly IAwsService awsService;

        /// <summary>Initializes a new instance of the <see cref="AwsConfigurationTask"/> class.</summary>
        /// <param name="item">The schedule history item.</param>
        /// <param name="settingsService">The settings service.</param>
        /// <param name="awsService">The AWS service.</param>
        public AwsConfigurationTask(ScheduleHistoryItem item, ISettingsService settingsService, IAwsService awsService)
        {
            this.ScheduleHistoryItem = item;
            this.settingsService = settingsService;
            this.awsService = awsService;

            this.ProcessErrored += (client, exception) => Exceptions.LogException(exception);
        }

        public override void DoWork()
        {
            try
            {
                this.Progressing();
                
                this.ScheduleHistoryItem.AddLogNote("<ol>");
                // TODO: implement scheduler logic
                this.ScheduleHistoryItem.AddLogNote("</ol>");

                this.ScheduleHistoryItem.Succeeded = true;
                this.ScheduleHistoryItem.AddLogNote("<p><strong>AWS configuration completed for all sites</strong></p>");
            }
            catch (Exception exc)
            {
                this.ScheduleHistoryItem.Succeeded = false;
                this.ScheduleHistoryItem.AddLogNote("</ol>");
                this.ScheduleHistoryItem.AddLogNote("<p><strong>Unexpected error during AWS configuration</strong></p>");
                this.Errored(ref exc);
            }
        }
    }
```

**Pull request merged**
