### PR TITLE
Updated contributing guide for GitHub issues

### PR DESCRIPTION
**Pull request by ahoefling**
Updated contribution guide to use GitHub Issues instead of JIRA issues

#2044

### CODE REVIEW

**Comment by ahoefling** [comment]
@bdukes I agree it is unnecessary in the title. Does commit  4aa5cb390ddaad494f29b6016cbdc8df352ca739 cover it?

**Comment by ahoefling** [comment]
I think I am going to clean this up a little based on your feedback

**Comment by bdukes** [comment]
@ahoefling I pushed a commit with a change more like what I'm thinking (feel free to adjust how you see fit)

**Comment by ahoefling** [comment]
@bdukes I didn't see your message and I squashed the commits. Can you reapply it? Sorry about that, should have checked here before I squashed.

**Comment by ahoefling** [comment]
Looks good to me

**Pull request merged**
