### PR TITLE
DNN-7151: Convert to Web Application Project

### PR DESCRIPTION
**Pull request by ohine**
initial conversion to a wap project. very basic smoke testing (installed clean site, no upgrade tests yet)

### CODE REVIEW

**Comment by cnurse** [comment]
I'll merge this once we finalize the CTP 3 build

**Comment by cnurse** [comment]
Merged with a couple of small modifications.

**Comment by cnurse** [comment]
So far - and that was not really related.  I am sure other issues will arise - there might be an upgrade issue, but they will be treated as bugs moving forward.

**Comment by zyhfish** [comment]
Reviewed code, looks good.

**Pull request merged**
