### PR TITLE
StyleCop fixes

### PR DESCRIPTION
**Pull request by bdukes**
Most of the auto-fixes

### CODE REVIEW

**Comment by valadas** [comment]
Odd, there are random charaters missing here and there:

image

**Comment by bdukes** [comment]
😦 Looks like these auto-fixes aren't without their bugs…  Ugh.

**Comment by bdukes** [comment]
Alright, build succeeded.  [55,464 warnings](https://dev.azure.com/dotnet/DNN/_build/results?buildId=34500&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=a04569be-1b08-5c9a-7e65-a83076350a0c&l=121924) instead of [194,461 warnings](https://dev.azure.com/dotnet/DNN/_build/results?buildId=34446&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=a04569be-1b08-5c9a-7e65-a83076350a0c&l=399772) on the previous build.

I'm going to manually apply/fix some of the auto-fixes that caused build errors.  Y'all can merge this now and I'll push those changes as a separate PR, or I can push to this PR if nothing's moved on it before I'm done.

**Comment by valadas** [comment]
Hmm, we have a new error, not sure if caused by my fixing of conflicts, they where pretty basic to resolve...

**Comment by bdukes** [comment]
Thanks @valadas! I've just pushed a change which should fix it.  One side moved the `using` statements inside the namespace and the other side added a new `using` statement, and the resolution left out the new `using` statement.

**Comment by bdukes** [comment]
Also, with the SA1200 change, we're down to [36,883 warnings](https://dev.azure.com/dotnet/DNN/_build/results?buildId=34510&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=a04569be-1b08-5c9a-7e65-a83076350a0c&l=84633).

**Comment by valadas** [comment]
Oh, sorry, my bad :)

/azp run

**Comment by valadas** [comment]
Cool, it builds :) Can we get a second approver @dnnsoftware/approvers

**Comment by mitchelsellers** [comment]
Just confirming before I do this, we are good to merge this right? @valadas @bdukes

**Comment by bdukes** [comment]
Yessir

**Pull request merged**
