### PR TITLE
DNN-7984 Removed useless code preventing users to upload files into a…

### PR DESCRIPTION
**Pull request by mean2me**
… subfolders of the User folder

### CODE REVIEW

**Comment by mitchelsellers** [comment]
Do you have recreation steps for how this was failing before?  Looking at Ticket DNN-7984 that appears to have been closed back in 2015 and was not related to this issue (https://dnntracker.atlassian.net/browse/DNN-7984)

**Comment by tomepoh** [comment]
I am not sure this is the right area to post this but adding an existing module to a page will move all the modules already on the page to the location of the new module. Is there any fix for this in the next release? 
Thank you,
Tom
[Managed IT Services](https://www.bizconnectors.com)

**Comment by mean2me** [comment]
Hello @mitchelsellers , we recently migrated to a new JIRA platform, so we have new IDs. That issue is still on the old JIRA and not related to the current fix.

**Comment by tpluscode** [comment]
@mitchelsellers the issue being fixed is tracked as [DNN-10682](https://dnntracker.atlassian.net/browse/DNN-10682) in the old Jira

**Comment by tpluscode** [comment]
I'm not sure this is something we are aware of @tomepoh. See if you can find a related issue on https://dnntracker.atlassian.net/. 

If not then do report an issue there keeping in mind that we'll need some more information: your running version and anything you think is specific to your problem.

**Pull request merged**
