### PR TITLE
Merge latest changes from 9.6.2 into develop

### PR DESCRIPTION
**Pull request by valadas**
This is a release management task and we are self-approving it for that reason.

### CODE REVIEW

**Comment by bdukes** [comment]
Here's the auto-resolution I got from [SemanticMerge](https://www.semanticmerge.com/). 

[PagesController.cs](https://github.com/dnnsoftware/Dnn.Platform/files/4865668/PagesController.cs.txt)

**Comment by valadas** [comment]
Interesting tool...

**Comment by EPTamminga** [comment]
It certainly is interesting

**Comment by bdukes** [comment]
Let me know if you're planning to purchase, I can get you a small discount (via email).

**Pull request merged**
