### PR TITLE
Fix for #4566 in SiteSettingsController

### PR DESCRIPTION
**Pull request by yog-it**
Fix for #4566.  

## Summary
ValidateTabId used for the 3 redirect settings, "Redirect_AfterLogin", "Redirect_AfterLogout" and "Redirect_AfterRegistration".

### CODE REVIEW

**Comment by sleupold** [comment]
are chages to PasswordReset really related to issue #4566? 
If needed, please move to a separate PR

**Comment by yog-it** [comment]
No.  That was my first pull request to the DNN platform. Reviewing it I noticed I didn't make a separate branch name for that issue off of develop.  I was assuming that creating a new branch and adding this commit would be completely separate from that one.  It appears I was mistaken.

**Comment by yog-it** [comment]
What is the proper way to fix this?  Do I close this PR, and delete this branch and wait for the other PR to be merged before continuing?

**Comment by yog-it** [comment]
I see where my mistake was made.  I'm closing this PR and will open a new one separate from the first PR.

**Comment by valadas** [comment]
I general, changes should not be made on develop branch of your fork and you should create your own branch for each PR you intend to submit. This makes it easier to manage while PRs are under review.

**Comment by valadas** [comment]
Or if changes are requested...

**Comment by yog-it** [comment]
Thank you @valadas. This all has been a good learning experience for how to contribute.  I truly appreciate it.

**Comment by valadas** [comment]
You are welcome, also we usually put something descriptive in the PR title like "Fixed an issue where x y z would fail", it helps figure out quickly and we use those almost as is in the release notes.

Then to mark which issue it closes we use a keyword and the # sing to automatically link to the issue and as a bonus the issue get's closed when the PR is merged. There are a couple of those know keywords that do the magic, I usually use `closes` but all these ones are supported https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Pull request closed without merging**
