### PR TITLE
DNN-7147 Remove Widget framework

### PR DESCRIPTION
**Pull request by cnurse**

### CODE REVIEW

**Comment by hismightiness** [comment]
Such a sad day for me...  :'(

You know, the one person that uses this feature.  :)

**Comment by BobKruger** [comment]
Are you still using it, Will?     :-)

-Bob

BOB KRUGER
SVP Engineering
DNN Corp.
<http://www.dnnsoftware.com/>www.dnnsoftware.com<http://www.dnnsoftware.com/>

m +1 408-421-8153
o  +1 650-288-3687

WATCH 3 MINUTE VIDEO --><http://www.dnnsoftware.com/products/product-demos>
Publish / Measure / Optimize / Repeat

On Oct 13, 2015, at 4:45 PM, hismightiness <notifications@github.com<mailto:notifications@github.com>> wrote:


Such a sad day for me... :'(

You know, the one person that uses this feature. :)

**Comment by hismightiness** [comment]
Yes, but not in a mission critical way. Everything I'm doing has alternative methods. It's not the end of the world, and as I told Joe... Removing it is the better good here.  :)

**Comment by nvisionative** [comment]
Ha, just when we were finally getting onboard with widgets!  :-)  No biggie though!

**Comment by zyhfish** [comment]
Reviewed, looks good.

**Pull request merged**
