### PR TITLE
Bumped react-tabs to v4.2.1

### PR DESCRIPTION
**Pull request by valadas**
Supercedes #5255

I was having issues validating the other PR and there has been a few more minor/patch updates to this component. So I manually bumped it and tested it on a new branch, so here is a tested PR for that.

### CODE REVIEW

**Comment by david-poindexter** [comment]
@valadas I kicked off the build again hoping it will not fail this time.  :)

**Review by david-poindexter — APPROVED** [review]
Thanks @valadas 🎉

**Review by bdukes — APPROVED** [review]

**Comment by bdukes** [comment]
The release notes indicate that React 16.8 or newer is required, you didn't run into any issues in testing?

**Comment by valadas** [comment]
I did not, but you are right, let's be cautious here, I'll close this pr...

**Pull request closed without merging**
