### PR TITLE
DNN-8900 Update Microsoft CodeDOM extension

### PR DESCRIPTION
**Pull request by bdukes**
See [DNN-8900](https://dnntracker.atlassian.net/browse/DNN-8900)

> A new version of Microsoft.CodeDom.Providers.DotNetCompilerPlatform has been released: https://blogs.msdn.microsoft.com/webdev/2016/09/20/announcing-the-dotnetcompilerplatform-1-0-2-release/, which improves performance and fixes a bug.

### CODE REVIEW

**Comment by galatrash-at-dnn** [comment]
@bdukes this is an old PR. The latest CodeDOM library in now 1.0.7. Will you be able to update this PR with the latest one for me to process it?

**Comment by galatrash-at-dnn** [comment]
@bdukes  any update?

**Comment by bdukes** [comment]
@galatrash-at-dnn I intend to update this today

**Comment by bdukes** [comment]
@galatrash-at-dnn I've updated this for 1.0.7 of the package, and verified that `int.TryParse(value, out int result)` compiles correctly in an ascx file.

**Comment by bdukes** [comment]
I was _not_, however, able to get it to let me use the new `default` literal from C# 7.1, but I also don't see any specific details on whether this package is supposed to support C# 7.1 or not. 🤷‍♂️

**Comment by galatrash-at-dnn** [comment]
We are not going to support C# 7 syntax yet in DNN source code (all our compilation is still based on VS 2015).

**Pull request merged**
