### PR TITLE
Create more meaningful issue templates

### LINKED ISSUE #2253: Create more meaningful issue templates
## Description 
Currently only one issue template exists and it is very **ISSUE** focused.

## Steps to reproduce
Click **New Issue** button on GitHub repo.

## Current result
A single issue template is used based on **ISSUE_TEMPLATE.md**.

## Desired result
The user should be able to choose from several issues types (e.g., **Bug Report**, **Feature Request**, **Help & Other Questions**)

## Affected version
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

### PR DESCRIPTION
**Pull request by nvisionative**
## Summary
Deleted single ISSUE_TEMPLATE.md file and created three new issue templates in the ISSUE_TEMPLATE folder:  Bug Report, Feature Request, Help and Other Questions.  This makes this repo consistent with the dnnsoftware/Dnn.AdminExperience repo.

Resolves #2253

### CODE REVIEW

**Comment by EPTamminga** [comment]
Yes, add 9.2.2 as well.

**Comment by nvisionative** [comment]
Did you want me to add 9.2.2?

**Comment by ohine** [comment]
I think it makes sense @nvisionative and nobody has said not too yet. Ha!

**Comment by nvisionative** [comment]
@ohine okay, I updated to include 9.2.2.  Thanks.

**Pull request merged**
