### PR TITLE
DNN-9651: drop duplicate index and unused column.

### PR DESCRIPTION
**Pull request by sleupold**
fixing issues from DNN 7.2.0 upgrade and fixing typos in old script to make sure, future upgrades from previous versions don't have issues.

### CODE REVIEW

**Comment by galatrash-at-dnn** [comment]
@sleupold, this column is needed for DNN-2995 and can't be dropped. I will reject this for now.

**Comment by sleupold** [comment]
@galatrash-at-dnn,
I don't have access to DNN-2995, however, the calculated column is stupid (DNN always uses CI collation) and the index does not use this column. There is already an index on Email.

**Comment by galatrash-at-dnn** [comment]
@sleupold any update on when you will submit against the latest code base? Also, there is a need to fix the newly introduced C# ExportUser class as follows to since this column is dropped:
```
namespace Dnn.ExportImport.Dto.Users
{
    public class ExportUser : BasicExportImportDto
    {
       // ... everything stays as is except the LowerEmail property

        [Obsolete("Deprecated in 9.2.0 - use Email property instead.")]
        public string LowerEmail
        {
            get { return string.IsNullOrEmpty(Email) ? null : Email.ToLower(); }
            set { }
        }
```

**Comment by sleupold** [comment]
I will review and resubmit asap

**Comment by mitchelsellers** [comment]
Closing, @sleupold will be submitting a new pull request

**Pull request closed without merging**
