### PR TITLE
Parse date with invariant culture to fix non-Gregorian calendar dates…

### LINKED ISSUE #4163: Search doesn't show any results when Arabic text is searched in Arabic pages.
## Description of bug
Search doesn't show any results in search results page when Arabic language is selected and Arabic text is searched. It does show items in search drop-down but when we click "See More Results" it doesn't show any results.

## Steps to reproduce
1. Install DNN 9.6.1
2. Add language Arabic = العربية (المملكة العربية السعودية)
3. Translate pages
4. Create a page with an Arabic name like كتابة
5. Index the content

## Current behavior
In "SA" language, It is unable to find the page when search. Please note that the quick search able to return the page.
If we add the same Arabic word into a page in "en-us" localization, DNN will be able to find it without any issue.

## Expected behavior
In "SA" language, It should able to find the page when search.

## Screenshots
quick search results:
image
After clicking "See More Results" or hitting Enter key:
image

## Error information
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Specified time is not supported in this calendar. It should be between 04/30/1900 00:00:00 (Gregorian date) and 11/16/2077 23:59:59 (Gregorian date), inclusive.
Parameter name: time
  Source=mscorlib
  StackTrace:
   at System.Globalization.UmAlQuraCalendar.CheckTicksRange(Int64 ticks)
   at System.Globalization.UmAlQuraCalendar.GetDatePart(DateTime time, Int32 part)
   at System.Globalization.UmAlQuraCalendar.GetDayOfMonth(DateTime time)
   at System.DateTimeFormat.FormatCustomized(DateTime dateTime, String format, DateTimeFormatInfo dtfi, TimeSpan offset)
   at System.DateTimeFormat.Format(DateTime dateTime, String format, DateTimeFormatInfo dtfi, TimeSpan offset)
   at System.DateTimeFormat.Format(DateTime dateTime, String format, DateTimeFormatInfo dtfi)
   at DotNetNuke.Common.Utilities.DateUtils.CalculateDateForDisplay(DateTime date) in C:\Source\DNN\Dnn.Platform\master\DNN Platform\Library\Common\Utilities\DateUtils.cs:line 158
   at DotNetNuke.Services.Search.Entities.SearchResult.get_DisplayModifiedTime() in C:\Source\DNN\Dnn.Platform\master\DNN Platform\Library\Services\Search\Entities\SearchResult.cs:line 37
   at DotNetNuke.Web.InternalServices.SearchServiceController.GetGroupedDetailViews(SearchQuery searchQuery, Int32 userSearchTypeId, Int32& totalHits, Boolean& more)
   at DotNetNuke.Web.InternalServices.SearchServiceController.Search(String search, String culture, Int32 pageIndex, Int32 pageSize, Int32 sortOption)

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [x] 10.00.00 alpha build
* [x] 09.07.02 release candidate
* [x] 09.07.01 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

### PR DESCRIPTION
**Pull request by tauqeer-haider**
… issue

Fixes #4163 

## Summary

Date is parsed using invariant culture to fix non-Gregorian calendar dates.

### CODE REVIEW

**Review by bdukes — APPROVED** [review]

**Comment by bdukes** [comment]
Do you know where in the code this value is first generated (where the conversion from `DateTime` to `string` is happening)?  Let's make sure that's always using `InvariantCulture`, too

**Review by mitchelsellers — APPROVED** [review]

**Comment by tauqeer-haider** [comment]
> Do you know where in the code this value is first generated (where the conversion from `DateTime` to `string` is happening)? Let's make sure that's always using `InvariantCulture`, too

I have spotted these places where this is converted to string without invariant culture. I can apply invariant culture fix there too. Just confirm if it should be included in same PR or do you want me create a new issue for it? thanks.
<repo>\DNN Platform\Library\Services\Search\Entities\SearchDocument.cs
Line 89 ToString() method: "Last Modified: " + this.ModifiedTimeUtc.ToString("O"),

<repo>\DNN Platform\Library\Common\Utilities\DateUtils.cs
Line 158 CalculateDateForDisplay() method: return date.ToShortDateString();

<repo>\DNN Platform\Library\Services\Search\Internals\InternalSearchControllerImpl.cs
Line 612 AddSearchDocumentParameters() method: doc.Add(new NumericField(Constants.ModifiedTimeTag, Field.Store.YES, true).SetLongValue(long.Parse(searchDocument.ModifiedTimeUtc.ToString(Constants.DateTimeFormat))));

**Comment by bdukes** [comment]
I think the first two of those usages look fine:

* `this.ModifiedTimeUtc.ToString("O")` the [Round-trip ("O", "o") Format Specifier](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-round-trip-o-o-format-specifier) always uses an invariant culture
* `CalculateDateForDisplay` sounds like it should always use the user's culture, i.e. it's not storing the value, just displaying

That last one _does_ look like it would be affected by current culture, when it shouldn't be.  Since it's directly related to this PR, please add it as another commit into this PR.  Please add `CultureInfo.InvariantCulture` to both the `ModifiedTimeUtc.ToString` and `long.Parse` calls.

**Comment by valadas** [comment]
I think this is ready to go now right @bdukes

**Comment by david-poindexter** [comment]
@valadas looks like all requested changes have been incorporating.  I'll go ahead and merge in prep for the 9.8.0 RC.

**Pull request merged**
