### PR TITLE
adjust version

### LINKED ISSUE #3783: Update DNN version list in bug report
## Description of bug
DNN version list hasn't been updated after DNN 9.6.1 release

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to "issues" on Github and click "new issue".
2. select "bug report" and fill in the form

## Current behavior
for DNN version affected, the list states DNN 9.6.0 as current release

## Expected behavior
should state 9.6.1 and 9.6.2 as RC

## Affected version
* [ ] 10.00.00 alpha build
* [XXX] 09.06.01 release candidate
* [XXX] 09.06.00 latest supported release

## Affected browser

* [·] any

### PR DESCRIPTION
**Pull request by sleupold**
fix #3783

### CODE REVIEW

**Comment by sleupold** [comment]
@valadas 
when and where did you release 9.6.2 - I can find 9.6.1 only

**Comment by david-poindexter** [comment]
> I am coming up with an automation for this, but if we do a manual adjustment as of now we are out of RC and 9.6.2 is released.
> 
> Can you please adjust to remove the release candidate line and just update the latest supported release to 9.6.2

Looks good to me.  9.6.1 is the latest release.  ;-)

**Comment by valadas** [comment]
I am sorry, my mistake, I live in the future... But we do not have a 9.6.2 RC at the moment, can you please just remove the release candidate line, there is an automation in place that will add it when we do create a 9.6.2 RC.

**Comment by valadas** [comment]
Thank you sir, sorry for the confusion there :)

**Pull request merged**
