### PR TITLE
Fixes UserRequestIPAddressController.cs IPv6 handling 

### PR DESCRIPTION
**Pull request by alanhoman**
GetUserRequestIPAddress has a bug since it assumes that all incoming requests are IPv4 addresses.  This causes bugs in all downstream IP address handling.  One specific example is the LOGIN_SUCCESS event log entry does not include the IPv6 address (IPv4 addresses are working).  My proposed change checks if the request is coming from a valid IPv4 address and returns it if it is IPv4.  If not, it checks if it is an IPv6 address and returns it or string.Empty if the IP address is not valid.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dnnsoftware/Dnn.Platform?pullRequest=4229) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dnnsoftware/Dnn.Platform?pullRequest=4229) before we can accept your contribution.<br/><br/>:x: alanhoman [sign now](https://cla.dotnetfoundation.org/dnnsoftware/Dnn.Platform?pullRequest=4229)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dnnsoftware/Dnn.Platform?pullRequest=4229) it.</sub>

**Comment by bdukes** [comment]
This scenario was handled by @mikebigun in 3cb35055b1cf7589227fe4792c2d3143e2011c07, where it logs the IPv6 address separately.  I believe the reason for keeping the IPv6 address separate was to avoid breaking changes.  I would be okay with updating the `LOGIN_SUCCESS` entry to log the IPv6 address, but we'd need further investigation to see if it's safe to change this API to always return IPv6.

**Comment by alanhoman** [comment]
Hi Brian,

I can understand not introducing breaking changes, but as it is right now, DNN does not handle IPv6 addresses correctly right now.  You should see my code suggestion, but if you have another way to solve this, I will leave it up to you or others.

Also, I started a pull request to provide the code I was suggesting.  Can you just delete this for me as it is having a merge issue?

Thanks for taking a look so quickly,
Alan Homan

**Comment by valadas** [comment]
It look like this started off from the wrong branch @alanhoman I don't know exactly how it started, you may be able to do `git merge upstream/develop` to resolve the discrepencies.

If the change is small enough sometimes it is easier to restart the PR than to try to resolve strange conflicts. You should setup https://github.com/dnnsoftware/Dnn.Platform as an upstream remote and while on the develop branch, do a `git pull upstream develop` and then create a branch from there for your changes.

**Comment by alanhoman** [comment]
I closed the PR and will wait to hear back from Brian as to how he would like to proceed with the IPv6 fix.

**Comment by bdukes** [comment]
@dnnsoftware/approvers @mikebigun Any thoughts on where we should worry about potential breakages if we start using IPv6 addresses in places where IPv4 addresses are stored now?  Here are example usages I could find:

* Logging
  * [Password Reset](https://github.com/dnnsoftware/Dnn.Platform/blob/80b6b2c56c06a058a8995196f8fa8375a28c9508/DNN%20Platform/Website/admin/Security/PasswordReset.ascx.cs#L338-L360)
  * [Send Password](https://github.com/dnnsoftware/Dnn.Platform/blob/80b6b2c56c06a058a8995196f8fa8375a28c9508/DNN%20Platform/Website/admin/Security/SendPassword.ascx.cs#L333-L358)
* [`UserInfo.LastIPAddress`](https://github.com/dnnsoftware/Dnn.Platform/blob/b9f27910947d84e7f0ae19a4a2cea6f689704b4f/DNN%20Platform/HttpModules/Membership/MembershipModule.cs#L146)
* `UserController.ValidateUser`
  * [JWT Controller](https://github.com/dnnsoftware/Dnn.Platform/blob/80b6b2c56c06a058a8995196f8fa8375a28c9508/DNN%20Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/JwtController.cs#L113-L116)
  * [Upgrade Wizard](https://github.com/dnnsoftware/Dnn.Platform/blob/f086bc324214c4be2a92d9c680d8aaed567d2dbd/DNN%20Platform/Website/Install/UpgradeWizard.aspx.cs#L407-L409)
  * [Basic Auth Message Handler](https://github.com/dnnsoftware/Dnn.Platform/blob/80b6b2c56c06a058a8995196f8fa8375a28c9508/DNN%20Platform/DotNetNuke.Web/Api/Auth/BasicAuthMessageHandler.cs#L70-L73)
  * [Digest Auth](https://github.com/dnnsoftware/Dnn.Platform/blob/80b6b2c56c06a058a8995196f8fa8375a28c9508/DNN%20Platform/DotNetNuke.Web/Api/Internal/Auth/DigestAuthentication.cs#L123)
  * Login Control
    * [Associate button](https://github.com/dnnsoftware/Dnn.Platform/blob/f5660d908ea456026039d04af73e2ce6c6d383f2/DNN%20Platform/Website/DesktopModules/Admin/Authentication/Login.ascx.cs#L506-L516)
* [Login Control calling `UserController.UserLogin`](https://github.com/dnnsoftware/Dnn.Platform/blob/f5660d908ea456026039d04af73e2ce6c6d383f2/DNN%20Platform/Website/DesktopModules/Admin/Authentication/Login.ascx.cs#L1351-L1353)
* General Get IP Address APIs
  * [`HttpRequestMessageExtensions.GetIPAddress()`](https://github.com/dnnsoftware/Dnn.Platform/blob/80b6b2c56c06a058a8995196f8fa8375a28c9508/DNN%20Platform/DotNetNuke.Web/Api/HttpRequestMessageExtensions.cs#L40-L43)
  * [`HttpRequestExtensions.GetIPAddress()`](https://github.com/dnnsoftware/Dnn.Platform/blob/80b6b2c56c06a058a8995196f8fa8375a28c9508/DNN%20Platform/DotNetNuke.Web.Mvc/Routing/HttpRequestExtensions.cs#L38-L41)
  * [`AuthenticationLoginBase.IPAddress`](https://github.com/dnnsoftware/Dnn.Platform/blob/a37c4f80c516272c9f4129b1c157920cae95ab14/DNN%20Platform/Library/Services/Authentication/AuthenticationLoginBase.cs#L48-L56)
  * [`UserRequestIPAddressController.Instance`](https://github.com/dnnsoftware/Dnn.Platform/blob/a37c4f80c516272c9f4129b1c157920cae95ab14/DNN%20Platform/Library/Services/UserRequest/IUserRequestIPAddressController.cs#L9-L25) (this is the method called by all of the above and whose is adjusted by this PR)

`UserController.ValidateUser` logs the IP address in three failure scenarios
https://github.com/dnnsoftware/Dnn.Platform/blob/8bb34af67f456699cfba62a150f77b1055edec64/DNN%20Platform/Library/Entities/Users/UserController.cs#L1525-L1529

`UserController.UserLogin` calls `ValidateUser`, updates `UserInfo.LastIPAddress`, and also logs the IP address on success and user not found
https://github.com/dnnsoftware/Dnn.Platform/blob/8bb34af67f456699cfba62a150f77b1055edec64/DNN%20Platform/Library/Entities/Users/UserController.cs#L1447-L1454
https://github.com/dnnsoftware/Dnn.Platform/blob/8bb34af67f456699cfba62a150f77b1055edec64/DNN%20Platform/Library/Entities/Users/UserController.cs#L2175-L2191

If we need to keep the existing IP addresses IPv4 only, we could, at least, add an IPv6 log property to those events and optionally populate that instead of the IP property.

**Pull request closed without merging**
