### PR TITLE
Ensure StandardFolderProvider always returns an absolute URL.

### LINKED ISSUE #5085: Link click for files doesn't take into account the SSL Offload.
## Description of bug
When requesting a link to a file through the LinkClick/FileServerHandler a relative URL is returned, which doesn't take into account the   SSL offload.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Request a file link through LinkClick.
2. Open browser console. Click on the link.
3. File will not open automatically.
4. In the console you will notice a mixed content error. 

## Current behavior
Currently, the FileServerHandler simply returns a relative URL, which in some cases might not be enough in order for the browser to properly determine the protocol (HTTP/HTTPS).

## Expected behavior
FileServerHandler should return an absolute URL, while taking into account the SSL Offload.

## Screenshots
If applicable, provide screenshots to help explain the bug.

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [ ] 10.00.00 alpha build
* [ ] 09.10.02 release candidate
* [x] 09.10.01 latest supported release

## Affected browser

* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

### PR DESCRIPTION
**Pull request by rhaiamz**
Fixes #5085 

Includes the fixes suggested in PR #5086.

### CODE REVIEW

**Review by mitchelsellers — COMMENTED** [review]
Upon further consideration and thought, I'm not sure that this is an acceptable change at all, as it will have major breaking change implications to how files are managed within the platform.

Consider a few situations that are impacted by this change.

* With this change a request for a file link will always be an absolute path, as much as this "fixes" the SSL offload issue.  In a situation where the SSL Offload is a different URL this is expected, but for almost all other situations this is going to create a real issue.  For example if I want to move my site from production to a test environment, every single file link will be incorrect now as it is hard-coded with an absolute path.  With no way to edit
* With this change, settings in the Editor, or other locations for allowing, or disallowing relative paths will no longer function

It MIGHT be possible to override this, ONLY when SSL is enabled, with an offload, AND a different URL but still not 100% sure that is a proper solution.

@dnnsoftware/approvers thoughts on this one?

**Comment by rhaiamz** [comment]
@mitchelsellers In this case, what are the next steps? Your current concerns are the reason why in my initial implementation, I placed it at a lower level, so the changes only happen at runtime.

**Comment by bdukes** [comment]
I think this logic should only apply when there's an SSL offload header setup.

**Comment by mitchelsellers** [comment]
I agree with @bdukes that only doing this logic if an offload url is set would be proper. 

That is a situation where content owners will expect environmental specific urls.

**Comment by mitchelsellers** [comment]
There is a very, very unique situation where the SSL Offload is done using a DIFFERENT URL rather than the actual public/normal URL.

**Comment by valadas** [comment]
> There is a very, very unique situation where the SSL Offload is done using a DIFFERENT URL rather than the actual public/normal URL.

Exactly the source of my confusion, being relative, it does not include the admin part in it right? So relative should work, unless I am missing something, I don't understand...

**Comment by rhaiamz** [comment]
I will post some screenshots in order to bring some light to this issue. 
This is the setup made in the security tab
image
This is the link that will be clicked in order to open the file in the browser.
image
Which the browser will autocomplete with https as you can see in the below screenshot.
image
But after the request is made to the LinkClickController, the browser opens this tab for the returned URL
image

**Comment by rhaiamz** [comment]
I will post a more extended explanation in the following hours.

**Comment by rhaiamz** [comment]
We did a bit of digging on our end. The URL(line 175 in [FileServerHandler](https://github.com/dnnsoftware/Dnn.Platform/blob/3697c5344cef8d49214230f0cc2efcd9e93a00a8/DNN%20Platform/Library/Services/FileSystem/FileServerHandler.cs#L175)) that leaves the DNN code remains relative before it is passed to [Response.Redirect](https://referencesource.microsoft.com/#system.web/HttpResponse.cs,2372) at line 190 in [FileServerHandler](https://github.com/dnnsoftware/Dnn.Platform/blob/3697c5344cef8d49214230f0cc2efcd9e93a00a8/DNN%20Platform/Library/Services/FileSystem/FileServerHandler.cs#L190).

As you can see, at [line 2394](https://referencesource.microsoft.com/#system.web/HttpResponse.cs,2394) this will force the URL to be [converted](https://referencesource.microsoft.com/#system.web/HttpResponse.cs,3308) to an Absolute URL based on a configuration setting found in system.web/httpRuntime. This for DNN seems to default to true, possibly from the days when the [RFC2616](https://www.rfc-editor.org/rfc/rfc2616#section-14.30) which required the Location header to be an absolute URI. In 2014 it was replaced by [RFC7231](https://www.rfc-editor.org/rfc/rfc7231#section-7.1.2) which states that relative URIs in the Location header are now permitted. Upon setting the  "useFullyQualifiedRedirectUrl" to false, the URL remained relative in the Location header, and the request no longer changed from HTTPS to HTTP. 
While simply turning this option off would fix the issues mentioned, I still think that returning an absolute URL for the file would be a better option, as this would eliminate any confusion and possibility for such an issue to occur in the future.

**Comment by bdukes** [comment]
Thanks @rhaiamz, that clarification helps a lot.

As @valadas pointed out, using a relative URL here seems most correct, so if we could preserve the relative URL, that would resolve the issue completely from my perspective.

I would suggest that the PR add a [config transform](https://github.com/dnnsoftware/Dnn.Platform/tree/develop/DNN%20Platform/Website/Install/Config) to set `useFullyQualifiedRedirectUrl` to `false`. The only issue noted in the [docs for that setting](https://docs.microsoft.com/en-us/dotnet/api/system.web.configuration.httpruntimesection.usefullyqualifiedredirecturl) states "Some browsers might have problems loading pages in cookieless sessions when this value is false."

My assumption is that "some browsers" includes old browsers we don't support, and we don't support cookieless sessions, either AFAIK, so this seems like a safe change to me.

**Comment by valadas** [comment]
Thanks, that explanation helps me understand now

**Comment by valadas** [comment]
As discussed, this PR cannot be merged this way as it would produce too many side-effects.

**Pull request closed without merging**
