### PR TITLE
Recursive read lock acquisitions not allowed

### PR DESCRIPTION
**Pull request by mikebigun**
fixes [issue 2185](https://github.com/dnnsoftware/Dnn.Platform/issues/2185)

### CODE REVIEW

**Comment by mitchelsellers** [comment]
Pending customer verification per @daguiler will follow-up again no later than 1/1/2019

**Comment by daguiler** [comment]
@mitchelsellers We had preliminary confirmation from customer three weeks ago that this worked, and I'm touching base with them again to confirm there were no negative side effects.

**Comment by daguiler** [comment]
We got confirmation from 2 customers that this patch works. They have patched their production environments and they've been stable for several weeks now.
I think we should merge this @dnnsoftware/approvers

**Comment by daguiler** [comment]
Looks like we have a few outdated unit tests breaking the build. Will take care.

**Pull request merged**
