### PR TITLE
Move module out of `PolyDeploy` folder and rename a few base project files

### PR DESCRIPTION
**Pull request by david-poindexter**
## Summary
This is the first of many PRs in support of #5920

### CODE REVIEW

**Review by valadas — COMMENTED** [review]
Looks like this is mostly a move/rename of files but the build is failing and I could not quickly find out why from the logs here. @david-poindexter do you see more details when doing a full build locally or it just works fine?

**Comment by david-poindexter** [comment]
@valadas I am pretty sure the project didn't build correctly before.  We just didn't see it because it had not been added to the `DNN_Platform.sln`.  I was honestly expecting the build to fail until we get a lot of this project converted to the new namespace, etc.  How would you like for me to handle this?  I can do one of the following:

* Remove the project from the solution for now.
* Try to make a much larger PR and get the project to compile.

If you have another idea, I am open to that as well.

**Comment by david-poindexter** [comment]
Okay, I just verified.  The project was unable to build successfully before my changes, so would you like for me to remove it from the solution, or we ignore the build issues for now?

**Comment by valadas** [comment]
Ok sounds good. Unless anyone disagrees so we can work faster on this, only on this (feature) branch we will work with one reviewer and backpedal only if needed. We will then follow the branch rules when we merge the whole bulk-install feature in a protected branch (release/10.0.0 for instance).

Until we get farther along it is kinda normal to get build failures here.

**Review by valadas — APPROVED** [review]

**Pull request merged**
