### PR TITLE
DNN-7569: Remove the FeedBrowser.

### PR DESCRIPTION
**Pull request by zyhfish**

### CODE REVIEW

**Comment by cnurse** [comment]
@Ben - can you tweak this to use the incremental version 8.0.0.12 - rather than 8.0.0.6 - you will need to add a new cleanup file (08.00.00.00.12.txt) and a new private method in Upgrade.cs.  Otherwise people who are using CTPs won't get the change correctly.

Thanks

**Comment by zyhfish** [comment]
done.

**Comment by cathalconnolly** [comment]
sorry folks, 8.0.0.12 is being used already, it'll need moved again

**Comment by jbrinkman** [comment]
:shipit:

**Pull request merged**
