### PR TITLE
Standardize Upload interfaces

### PR DESCRIPTION
**Pull request by bdukes**
## Summary
Standardize file upload implementations to all use either upload file or select file workflows.

### Before
Icon upload on Pages
User profile upload

### After
Icon upload on Pages
User profile upload

### CODE REVIEW

**Review by mitchelsellers — APPROVED** [review]
Thank you for this contribution!

**Review by david-poindexter — APPROVED** [review]
This looks great - thank you @bdukes

**Review by valadas — APPROVED** [review]
Looks geat! Thanks!

**Review by donker — APPROVED** [review]

**Comment by bdukes** [comment]
I've updated the base for this PR to the new `release/9.11.0` branch, it is ready to merge

**Pull request merged**
