### PR TITLE
Fix bug #DNN-21129

### LINKED ISSUE #2135: While creating group file upload by browse file not working but drag'n'drop is fine
## Steps to reproduce

Login as host user 
Goto Community > Groups 
Click on "Create Group" button 
A popup window appear to gather info for new group 
Click on "Upload File" 
Another pop up Click on "DRAG FILES HERE OR CLICK TO BROWSE" 
Select file to upload from file explorer 

## Current result

Error as shown in attached screenshot

fileuploadscreenshot

## Expected result

file should be uploaded successfully

## Affected version

* [x] 9.2.1

This issue is not producing in 9.2.0

### PR DESCRIPTION
**Pull request by Mohtshum**
fixes #2135 

- Possible regression due to #2035 

## Summary
- Pull back the deleted code
- Check if folder object null, then go for portal base folder

### CODE REVIEW

**Comment by tpluscode** [comment]
@dnnsoftware/tag please review.

Also, I think this should go with 9.2.1 as it fixes a regression we inadvertently introduced

**Comment by bdukes** [comment]
I've merged this into `development` and `release/9.2.1`

**Comment by ohine** [comment]
@bdukes, when merging can you also add the milestone? It greatly helps with generating the release notes and tracking what was in each release. I've added it to this pull request already.

**Comment by bdukes** [comment]
Sure thing, @ohine, I definitely didn't think about that.

That said, since this issue is addressing a regression introduced during 9.2.1 development, do we want it showing up "on the roadmap"?

**Comment by ohine** [comment]
IMO, yes. I think it's important to have a full list of all changes, regardless if it's a fix to a new issue that was introduced during the development of an upcoming release.

**Pull request merged**
