### PR TITLE
Warnings as Errors for test projects

### PR DESCRIPTION
**Pull request by bdukes**
This turns off the documentation rules for StyleCop and turns on Warnings as Errors for all test projects

### CODE REVIEW

**Review by mitchelsellers — APPROVED** [review]

**Review by valadas — APPROVED** [review]
Providing it builds after the rebase, this looks good to me.

**Comment by daguiler** [comment]
Hi @bdukes
the solution doesn't build anymore in Visual Studio bacause of this. Am I missing something?

**Comment by bdukes** [comment]
@daguiler it builds fine for me.  What errors are you getting?  Are you on the latest `develop`?

**Comment by daguiler** [comment]
I am on latest `develop`, and I'm getting errors because of all the broken rules in the test projects.
Are you not getting the same?

image

**Comment by bdukes** [comment]
No, those should be suggestions rather than warnings because of the configuration in https://github.com/dnnsoftware/Dnn.Platform/blob/7c3d891dc8a1e60666cbe104e9c6b877821a3593/DNN%20Platform/Tests/.editorconfig#L153-L226

**Comment by bdukes** [comment]
What version of Visual Studio are you using?  I bet it's a fairly new feature to read severity for those rules through `.editorconfig`.

**Comment by daguiler** [comment]
mm.. I'm still on 2017 Enterprise

**Comment by daguiler** [comment]
According to [this article](https://dotnetthoughts.net/editorconfig-support-in-visual-studio-2017/), VS 2017 supports `.editorconfig` files. I'll dig a bit more.

**Comment by bdukes** [comment]
The [Analyzer configuration documentation](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#configure-severity-levels) says
>Starting in Visual Studio 2019 version 16.3, you can configure the severity of analyzer rules, or diagnostics, in an [EditorConfig file](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#set-rule-severity-in-an-editorconfig-file), from the [light bulb menu](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#set-rule-severity-from-the-light-bulb-menu), and from the error list.

**Comment by daguiler** [comment]
I had an update available for my 2017 version (from 15.9.23 to 15.9.30), but unfortunately it didn't help with this issue.
So I guess I will have to undo this change in my local environment from now on every time I want to build the solution :-(

**Comment by bdukes** [comment]
If you'd like to submit a change which would work for VS 2017, we'd happily accept it.  The best option would be, of course, to resolve the warnings, but that's rather time consuming, which is why we haven't done it 😄 

A partial option would be to add a new `stylecop.json` file for tests which loosens the strictness of the rules (specifically, you can disable the documentation rules), but fix the other issues which can't be controlled via `stylecop.json`.

The other option is to introduce a `.ruleset` file which disables the rules and reference that from the test projects.

**Pull request merged**
