### PR TITLE
DNN-7232 update client dependency framework

### PR DESCRIPTION
**Pull request by ohine**
this request updates the cdf component to the latest version. we were stuck on I believe v1.3 or v1.4, and this gets us up to v1.8 as of commit 17d935408f4c8a37c6e83b19814aa3637c411b85

### CODE REVIEW

**Comment by sleupold** [comment]
will this be merged?

**Comment by ohine** [comment]
It's tagged for 7.5.0 aka 8.0, I'm going to clean up the merge conflicts with the hope it might get pushed up to 7.4.2.

**Comment by cnurse** [comment]
I reviewed the diff that @bdukes posted, and while the only significant change is not in the 1.8 release - it seems to be a positive change, so I have accepted the merge from @ohine as submitted (resolving all the merge conflicts due to the switch of development from 7.4.x to 8.0.0 since the PR was submitted).  I am currently testing the changes and the merge before push the change to development.

**Comment by cnurse** [comment]
After reviewing all of Oliver's changes I noticed that the CDF is now on version 1.8.4 on Nuget so I have synchronized all those changes with our source

**Comment by cnurse** [comment]
Merged Manually

**Pull request closed without merging**
