### PR TITLE
DNN-8377: Installation fails on non-English databases

### PR DESCRIPTION
**Pull request by sleupold**
Use ISO date format for comparisons

### CODE REVIEW

**Comment by bdukes** [comment]
:+1:

**Comment by ohine** [comment]
Looks good to me, but since it touches a sql file from a released build. I'm deferring the final decision to @jbrinkman, @ashishpd or @cpaterra.

**Comment by sleupold** [comment]
Oliver, if the current version of the script fails during the upgrade, there is no option to fix it in a later one. This will not affect users upgrading from DNN 8.0.0, but all users (with non-english SQL Server language) upgrading from a previous version.

**Comment by ohine** [comment]
I completely agree, but I'm still more comfortable leaving that decision up to one of the PMs.

**Comment by ashishpd** [comment]
In rare situations, we've gone and updated the older SQL providers to deal with Upgrade situations. Merging this change. Thanks guys!

**Pull request merged**
