### PR TITLE
Search Results UI Alignment changes

### PR DESCRIPTION
**Pull request by kieran23101**
## Summary
These are very minimal changes to make the SearchResults page look more appealing, these are things that I seem to be repeating when creating a DNN installation and I'm sure that many other do too.

This PR is is a suggestion and there is no issues with it not being done, just thought I'd try and be helpful...

Please let me know if this will have a negative impact on the system.

Regards

Kieran

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dnnsoftware/Dnn.Platform?pullRequest=4074) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dnnsoftware/Dnn.Platform?pullRequest=4074) before we can accept your contribution.<br/><br/>:x: kieran23101 [sign now](https://cla.dotnetfoundation.org/dnnsoftware/Dnn.Platform?pullRequest=4074)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dnnsoftware/Dnn.Platform?pullRequest=4074) it.</sub>

**Comment by mitchelsellers** [comment]
THanks for the submission!  Do you happen to have any before/after comparison images?

Paging @valadas and @david-poindexter for review

**Comment by kieran23101** [comment]
Hi @mitchelsellers,

Yes, sure. Have attached them below.

Thank you for the speedy response!

## Before
image

## After
image

**Comment by mitchelsellers** [comment]
Thanks!  This helps us validate your intended before & after.  I'll defer to others for the proper nature of these.

**Review by david-poindexter — APPROVED** [review]
Thank you @kieran23101 for the contribution.  This is a great improvement and I'll target this for a `Future: Minor` release due to the possibility of it being a potential breaking change for some themes that may be styling Search Results.

**Review by valadas — APPROVED** [review]
Looks good to me

**Pull request merged**
