### PR TITLE
Feature/5101 ck editor resize images on upload

### LINKED ISSUE #5101: CKEditor option to resize images on upload
## Description of problem
Administrators still used to the RadEditorProvider are missing the option to specify a maximum size for images in the Editor Provider Settings. Since images from phones are getting larger and larger, and users tend to upload images straight from their device, people are very much used to the convenience of the RadEditor to resize the images to a certain maximum size on upload.
This is keeping sites from being upgraded to the latest version of DNN, with CKEditorProvider, or at least keeps them from removing Telerik.

## Description of solution
The CKEditor Provider settings should get an extra option for maximum height and width of images being uploaded. On upload images larger than these dimensions need to be automatically resized to fit within those dimensions.

## Description of alternatives considered
It would also be possible to check for maximum dimensions and present the user with an error, but that would be inacceptable from a UX point of view. Users should not have to worry about the resizing for a maximum size. Users needing more control (e.g. on quality) will know how to resize themselves, but most users won't care.

## Screenshots
image

## Additional context
A PR is being worked on

## Affected browser
Not browser related

### PR DESCRIPTION
**Pull request by skamphuis**
This PR is a redo of #5123 because of merge/rebase issues. As @valadas advised, I cherry picked the relevant commits, and gave it a quick test based on a fresh 9.11.0 install.

Closes #5101 
This PR is built on PR #5122 which was submitted for #5100, but is not necessarily related.

## Summary
This PR adds settings for:
* Image Resize Width On Upload
* Image Resize Height On Upload
And will resize any uploaded image to fit within these dimension on upload.

Since pictures are becoming larger and larger, it can be important on many portals, to have this automatic resize option, to allow users uncapable of resizing images themselves, to upload reasonably sized images.
image

### CODE REVIEW

**Comment by valadas** [comment]
I have seen the failed test fail for no reason so re-firing the build to see...

**Comment by skamphuis** [comment]
> I have seen the failed test fail for no reason so re-firing the build to see...

seems to have worked now

**Review by valadas — APPROVED** [review]
Cool, cool, so looks good to me then

**Review by bdukes — APPROVED** [review]
I'd like a couple of the manual `Dispose` calls converted to `using` statements (to avoid things not getting closed if there are errors), otherwise it looks good to me.

**Comment by skamphuis** [comment]
@bdukes thanks for your comments, Do I need to commit your changes? Or did you already do the changes? (I'm a bit scared to mess it up again :-) )

**Comment by bdukes** [comment]
I have not applied the changes, you can go ahead and do that. Thanks!

**Comment by skamphuis** [comment]
> I have not applied the changes, you can go ahead and do that. Thanks!

Did that just now, tnx

**Pull request merged**
