### PR TITLE
(DNN-9983) Localization: Install Wizard: part of the texts require translation.

### PR DESCRIPTION
**Pull request by nvisionative**
See [JIRA Issue DNN-9983](https://dnntracker.atlassian.net/browse/DNN-9983) for more detail.  I have added all the missing resource keys and have provided initial translations for each.

### CODE REVIEW

**Comment by kanm2015** [comment]
thanks, all changes look good. PR merged

**Comment by kanm2015** [comment]
Forgot to mention. Please sign and send the CLA document back to me. See this https://github.com/dnnsoftware/Dnn.Platform/blob/development/CONTRIBUTING.md

**Comment by nvisionative** [comment]
@kanm2015 I signed that a long time ago and it should already be on file.  :)

**Comment by nvisionative** [comment]
@kanm2015 please check with @galatrash-at-dnn to confirm.

**Comment by kanm2015** [comment]
cool, all good then. thx

**Pull request merged**
