### PR TITLE
DNN-8941 Package names should be case insensitive

### PR DESCRIPTION
**Pull request by bdukes**
[DNN-8941](https://dnntracker.atlassian.net/browse/DNN-8941)

> When a package has a dependency on another package, that dependency is currently case sensitive. Likewise, when installing a package, the search for duplicate packages (to determine if this is an upgrade, repair, etc.) is case sensitive. This behavior should not be case sensitive.
> # Scenario
> 
> The attached package [knockout-postbox_0.5.2_mismatch-dependency.zip](https://dnntracker.atlassian.net/secure/attachment/40755/knockout-postbox_0.5.2_mismatch-dependency.zip) has a dependency on "knockout," whereas the package that comes with DNN has the name "Knockout" with a capital _K_
> 
> ```
> <dependencies>
>   <dependency type="managedPackage" version="2.0.0">knockout</dependency>
> </dependencies>
> ```
> ## Steps to reproduce
> - Install the attached [knockout-postbox_0.5.2_mismatch-dependency.zip](https://dnntracker.atlassian.net/secure/attachment/40755/knockout-postbox_0.5.2_mismatch-dependency.zip) into your DNN site
> ## Expected
> - Package installs correctly
> ## Actual
> - Package fails because of an unmet dependency
> # Scenario
> 
> The attached package [Knockout-PostBox_0.5.2_mismatch-package.zip](https://dnntracker.atlassian.net/secure/attachment/40754/Knockout-PostBox_0.5.2_mismatch-package.zip) has the package name "Knockout-PostBox," whereas the package [knockout-postbox_0.5.2.zip](https://dnntracker.atlassian.net/secure/attachment/40753/knockout-postbox_0.5.2.zip) has the lowercase package name "knockout-postbox"
> ## Steps to reproduce
> - Install the attached [knockout-postbox_0.5.2.zip](https://dnntracker.atlassian.net/secure/attachment/40753/knockout-postbox_0.5.2.zip) into your DNN 
> - Install the attached [Knockout-PostBox_0.5.2_mismatch-package.zip](https://dnntracker.atlassian.net/secure/attachment/40754/Knockout-PostBox_0.5.2_mismatch-package.zip) into your DNN site
> ## Expected
> - Second package install indicates package is already installed, asks to do repair install
> ## Actual
> - Second package installs without indicating any issue

### CODE REVIEW

**Comment by ashishpd** [comment]
@galatrash-at-dnn you have worked recently on the entire Extensions experience in the new Persona Bar. Can you please review the code, do some testing and process the PR.

**Comment by galatrash-at-dnn** [comment]
Hi Brian,

Your changes are god but still there are many other places that need similar changes to make sure this case is covered well. I identified all of these and listed them below:
```
//In PackageInstaller.cs file:
        private void CheckSecurity()
        {
            PackageType type = PackageController.Instance.GetExtensionPackageType(t => t.PackageType == Package.PackageType);

//In Upgrade.cs file:
        private static void UninstallPackage(string packageName, string packageType)
        {
            var searchInput = PackageController.Instance.GetExtensionPackage(Null.NullInteger, p => p.Name == packageName && p.PackageType == packageType);

        public static IDictionary<string, PackageInfo> GetInstallPackages()
        {
            ...
                    if ( package.Value.Dependencies.All(
                            d => sortedPackages.Any(p => p.Value.Name == d.PackageName && p.Value.Version >= d.Version) ) )


//In EditExtension.ascx.cs file
        protected IPackageEditor PackageEditor
        {
            ...
        var pkgType = PackageController.Instance.GetExtensionPackageType(t => t.PackageType == Package.PackageType);

//In ExtensionWizard.ascx.cs file
        protected IPackageEditor PackageEditor
        {
            ...
                        PackageType _PackageType = PackageController.Instance.GetExtensionPackageType(t => t.PackageType == Package.PackageType);
        protected void wizNewExtension_NextButtonClick(object sender, WizardNavigationEventArgs e)
        {
            ...
                        PackageInfo tmpPackage = PackageController.Instance.GetExtensionPackage(Null.NullInteger, p => p.Name == newPackage.Name);


//In InstalledExtensions.ascx.cs file:
        private void BindGrid(string packageType, DataGrid grid, Label noResultsLabel)
        {
            ...
                default:
                    packages = PackageController.Instance.GetExtensionPackages(Null.NullInteger, p => p.PackageType == packageType).ToList();

//In LanguageInstaller.cs file:
        protected override void ReadCustomManifest(XPathNavigator nav)
        {
            ...
                PackageInfo package = PackageController.Instance.GetExtensionPackage(Null.NullInteger, p => p.Name == packageName);

//In PackageController.cs file:
        public static bool CanDeletePackage(PackageInfo package, PortalSettings portalSettings)
        {
            ...
            var dependencies = Instance.GetPackageDependencies(d => d.PackageName == package.Name && d.Version <= package.Version);

        ...

        public static bool CanDeletePackage(PackageInfo package, PortalSettings portalSettings)
        {
            ...
                    //Check if there is an alternative package
                    var packages = Instance.GetExtensionPackages(package.PortalID,
                                                                 p => p.Name == dep.PackageName

//In EditModuleDefinition.ascx.cs file:
        private ModuleDefinitionInfo ImportControl(string controlSrc)
        {
            ...
                var packageInfo = PackageController.Instance.GetExtensionPackage(Null.NullInteger, p => p.Name == name || p.FriendlyName == friendlyName);

            ...
							if (package.Name == txtName.Text || package.FriendlyName == txtName.Text)

//In JavaScriptLibraryEditor.ascx.cs file:
        public override void Initialize()
        {
            var usedBy = PackageController.Instance.GetPackageDependencies(d => d.PackageName == Package.Name && d.Version <= Package.Version).Select(d => d.PackageId);

//In LanguagePacks.ascx.cs file:
        private void BindGrid(string installPath, DataGrid grid)
        {
            ...
							if (packages.Any(p => p.Name == package.Name))
							{
								var existPackage = packages.First(p => p.Name == package.Name);

```

When you complete these, I will merge this PR.

**Comment by bdukes** [comment]
@galatrash-at-dnn I've made all of your suggested changes, and found a few more using ReSharper's structural search & replace.

Let me know if you see anything more that's off.

cc: @ashishpd

**Comment by galatrash-at-dnn** [comment]
Hi Brian, today I wanted to merge this PR but it had lots of conflicts. I tried doing it from the command line but it didn't work as well (I got SSL certificate related error). So, please redo these against latest development branch or send me a diff patch to merge and resolve locally.

**Comment by bdukes** [comment]
@galatrash-at-dnn I've rebased, but there were a number of changes in modules that have since been deleted, so we'll also need to look at the new Persona Bar implementations related to package names and see that those issues didn't get copied over.

**Comment by bdukes** [comment]
Changes in these files were lost in the rebase, because they were removed in 1e06ccff1fbec611a3aa5b328e0051d7e988624c:
 - `/Website/DesktopModules/Admin/Extensions/LanguagePacks.ascx.cs`
 - `/Website/DesktopModules/Admin/Extensions/InstalledExtensions.ascx.cs`
 - `/Website/DesktopModules/Admin/Extensions/ExtensionWizard.ascx.cs`
 - `/Website/DesktopModules/Admin/Extensions/Editors/JavaScriptLibraryEditor.ascx.cs`
 - `/Website/DesktopModules/Admin/Extensions/Editors/EditModuleDefinition.ascx.cs`
 - `/Website/DesktopModules/Admin/Extensions/Editors/SkinEditor.ascx.cs`
 - `/DNN Platform/Admin Modules/Dnn.Modules.Languages/LanguagePackWriter.ascx.cs`

**Pull request merged**
