### PR TITLE
DNN-8125 - updating Newtonsoft to version 7

### PR DESCRIPTION
**Pull request by donker**
This PR updates all NuGet Newtonsoft versions to v7. It also adds the correct binding in the web.config for Newtonsoft. I ran the tests in the platform solution and they all turned out fine.

### CODE REVIEW

**Comment by ashishpd** [comment]
@donker it looks there are conflicts with the PR, I was wondering if you can clean those. Please @francescorivola will review this on Friday.

**Comment by francescorivola** [comment]
Hi @donker, could you please report a new jira for this issue as DNN-5820 has been closed in October. We then can link your jira to DNN-5820 for history tracking. Thank you.

**Comment by donker** [comment]
Done:

https://dnntracker.atlassian.net/browse/DNN-8125

**Comment by francescorivola** [comment]
Thks @donker :)

**Comment by fjlucas** [comment]
Merged, the conflicts were related to some deleted modules (Dynamic Content Manager and Viewer). I also had to add a few new references.

**Pull request closed without merging**
