### PR TITLE
v9.11.0 Bump react-collapse from 4.0.3 to 5.1.0

### PR DESCRIPTION
**Pull request by bdukes**
Applying #4808 to release/9.11.0

### CODE REVIEW

**Review by mitchelsellers — APPROVED** [review]

**Review by valadas — CHANGES_REQUESTED** [review]
I mentioned that #4808 would need some good UI testing but it was merged without anyone confirming..

I just gave that build a quick test and we have issues with that:
image

image

image

I _think_ we need to revert that until someone has time to adjust it's usage...

**Comment by bdukes** [comment]
I'll look into fixing the usage

**Comment by david-poindexter** [comment]
Good catch @valadas - thanks for the effort @bdukes 🎉

**Review by valadas — APPROVED** [review]
As discussed on Slack with @bdukes , it will be easier to merge this and then do the react-collapse usage fix. So merging this one now.

**Pull request merged**
