### PR TITLE
DNN-23121: sanitize the properties.

### PR DESCRIPTION
**Pull request by zyhfish**

### CODE REVIEW

**Comment by zyhfish** [comment]
we can't save these into db, as if some code read it and use decode in future, the issue will occur again. we should remove them for safety.

**Comment by mitchelsellers** [comment]
@zyhfish In that case sanitization into the DB done via Html.Encode would be preferred.

**Comment by zyhfish** [comment]
Hi @mitchelsellers , generally we shouldn't save those scripts, as its just like a bomb, we don't know who will read and how to display it. we should always remove them before saving into db.

**Comment by tpluscode** [comment]
I agree. HTML encoding should be preferred instead of removing content

**Comment by zyhfish** [comment]
code updated.

**Pull request closed without merging**
