### PR TITLE
DNN-9537: Fix for a Journal Module ImageURL Bug

### PR DESCRIPTION
**Pull request by ChrisHammond**
Fix for the Journal Module having problems with PreviewURL Links that do not have an Image in the page anywhere.

### CODE REVIEW

**Comment by ChrisHammond** [comment]
Any chance these PRs will be looked at?

**Comment by kanm2015** [comment]
I'd prefer to have a backend fix also. Just add a null check to Journal.ServicesController.IsImageFile()

**Comment by galatrash-at-dnn** [comment]
@ChrisHammond, any chance to add a code-behind fix in the backend as well (per @kanm2015's comment)? Once done, I'll review and take proper actions.

**Comment by galatrash-at-dnn** [comment]
It seems this is already fixed in [DNN-10071](https://dnntracker.atlassian.net/browse/DNN-10071). Therefore, I'm closing this PR without merging.

**Pull request closed without merging**
