### PR TITLE
upgrade lucene.net component to 4.8.0

### LINKED ISSUE #3977: upgrade lucene.net component to 4.8.0
## Description of problem
lucene.net component is out-to-date.

## Description of solution
upgrade lucene.net component to 4.8.0

### PR DESCRIPTION
**Pull request by zyhfish**
Fix #3977

### CODE REVIEW

**Comment by mitchelsellers** [comment]
Can we get more detail on this change. 

We’re there known breaking changes etc?

Also does anyone know why we don’t use a NuGet reference for this?

**Comment by valadas** [comment]
Also I think 4.8.0 is still beta no?

**Comment by zyhfish** [comment]
Hi @mitchelsellers , this PR is created for upgrade lucene.net to the latest release, there should be no break changes as I already cover the upgrade scenarios, but one of the purposes of this PR is asking your code review to check whether we are good to go. currently, 4.8.0 is still in beta, so we shouldn't merge the PR until they officially release the 4.8.0, then I will update this PR so that we can do the upgrade smoothly with enough time to test it(from now).

Thanks,

**Comment by david-poindexter** [comment]
This PR should be put into draft and not targeting 9.7.0.

**Comment by bdukes** [comment]
This PR looks good to me.

Do we know if there are plans to release a stable version anytime soon?  4.8.0-beta00006 was released Aug 11, 2020, work on 4.8 started in 2014 and the other 4.8 betas were released in 2017.

**Comment by bdukes** [comment]
@zyhfish do you know what fixes or features this update provides?

**Comment by mitchelsellers** [comment]
At this time we cannot accept a PR for a non-stable release of a third-party component.  Once it becomes a stable release we will consider this.

**Pull request closed without merging**
