### PR TITLE
add email to password sent message for error tracing, fixes #4605

### LINKED ISSUE #4605: Improve logged details for password sent failure event
## Description of problem
Our site uses the standard DNN Authentication module. After a recent upgrade to Evoq 09.06.04, we began experiencing some issues related to user logins.

The most puzzling of those is the PASSWORD_SENT_FAILURE event, which appears to occur in the DNN Platform code.

- The message suggests possible success but the user does not receive the email.
- No corresponding entries are found in the DNN exception log.
- The SMTP server is confirmed to be working and has no additional information corresponding to the logged timestamps.
- If the user's email is known (sometimes they contact support), we're able to look at their account details, but a comparison of those vs. another account (which has no problems logging in) reveals nothing. It's not a simple issue of the email being entered incorrectly.

## Description of solution
Include, at minimum, the email address that was used in the request, but anything that would indicate the root cause would helpful.

## Screenshots
DNN password sent failure

## Affected browser
All, probably.

### PR DESCRIPTION
**Pull request by jcmrva**
#4605

## Summary
Includes the email address or username in the password reset message for better visibility into PASSWORD_SENT_FAILURE events.

### CODE REVIEW

**Review by bdukes — CHANGES_REQUESTED** [review]
For security reasons we can't have different message formats based on whether the username matches or doesn't. But I think it would be okay to include the username/email in all of the messages, whether it matched or not.

I would prefer to add a placeholder to the default message and use string.Format rather than just tacking it on to the end, so that administrators can have control over the formatting of that message (and have the option to include or exclude the extra information)

**Comment by mitchelsellers** [comment]
@jcmrva Do you plan on making adjustments to this PR based on the feedback above?

**Comment by jcmrva** [comment]
@mitchelsellers It's been my intention to. Is there a target date for the 9.9.2 milestone (which would help me prioritize it)?

**Comment by mitchelsellers** [comment]
2-3 weeks

**Comment by mitchelsellers** [comment]
@jcmrva Any update on possible changes?

**Comment by jcmrva** [comment]
It seems like the change the last commit will take care of it. Should any of the other messages be updated as well?

**Review by bdukes — APPROVED** [review]
LGTM, thanks!

**Comment by bdukes** [comment]
FYI, we don't get notified on pushes, so we weren't aware you'd already addressed this. We appreciate your quick responsiveness 👍🏻

**Comment by jcmrva** [comment]
My bad, I should've added a comment.

**Review by valadas — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
