### PR TITLE
StyleCop

### PR DESCRIPTION
**Pull request by bdukes**
Add StyleCop.Analyzers NuGet package to all projects, reference a shared `stylecop.config` file in projects

### CODE REVIEW

**Comment by bdukes** [comment]
Whoops, looks like `stylecop.json` was in the `.gitignore` and wasn't included at all in the commit.  Weird how only 4 projects failed.  New build running now, hopefully it'll be all green.

**Comment by bdukes** [comment]
> 
> 
> It looks like a couple of projects are missing the reference to the stylecop.json
> 
> See build errors here:
> image

@valadas it's 🟢 now

**Comment by bdukes** [comment]
We now have [239,659 warnings](https://dev.azure.com/dotnet/DNN/_build/results?buildId=33936&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=a04569be-1b08-5c9a-7e65-a83076350a0c&l=490065) vs. [428 warnings](https://dev.azure.com/dotnet/DNN/_build/results?buildId=33903&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=a04569be-1b08-5c9a-7e65-a83076350a0c&l=11295) from the previous build 😬 

We may need to walk through some configuration and auto-fixes.

**Comment by valadas** [comment]
Nice, it builds :) Now do we merge it now or you have other changes to make as per your previous comment @bdukes ?

**Comment by bdukes** [comment]
I would say we merge it now, and tackle other issues separately

**Comment by mitchelsellers** [comment]
Works for me as well.  Merging, and this will work well with the inclusion of SonarCube as well.

**Pull request merged**
