### PR TITLE
DNN-6913: Removed unused paramter hideSync in function prepareForFilteredContent()

### PR DESCRIPTION
**Pull request by janjonas**
See https://dnntracker.atlassian.net/browse/DNN-6913

### CODE REVIEW

**Comment by cathalconnolly** [comment]
I've raised this with the original developer, as it may not be used in platform, but I suspect it is used elsewhere

**Comment by cathalconnolly** [comment]
As I suspected this is used, so we cannot accept this change. I will close it and mark it as invalid. Here is the comment from the developer:
"Hi Cathal, you were right.

This method is also used in content, and it is used passing the “hideSync” parameter.
The method is invoked when Tags/Search Results are going to be shown or Subscribed items are shown.

The propose of that parameter is to show/hide the Sync buttons when a content is going to be listed. Obviously, that buttons make no sense when Search Results are shown or Subscribed items, therefore we have to hide them"

**Comment by janjonas** [comment]
@cathalconnolly: Thanks for the information. IMHO, there should be some kind of documented "public" JavaScript APIs or "public" functions should be marked as such. Otherwise you cannot change any JavaScript code without potentially breaking some functionalities...

**Comment by erikvb** [comment]
at the very least, there should be more documentation in code...

**Pull request closed without merging**
