### PR TITLE
Installation resource files reviewed

### PR DESCRIPTION
**Pull request by perezandres**
Added missing translations and some mistakes corrected.

### CODE REVIEW

**Comment by perezandres** [comment]
I Mitch. I think that I edited both files with the language editor inside DNN, but maybe I used Peter's DNN Translator, I'm not really sure right now... Which is the best option? I don't mind if I must review them ;-)

**Comment by EPTamminga** [comment]
Peter’s editor is a far better solution if you have tondo a serious amount of translations and you really want to manage the process.

**Comment by ohine** [comment]
@perezandres @EPTamminga I'm not familiar with the structure of the resource files. I know the system works without any issues I've stumbled on if the schema is removed. My assumption is less repetitive junk in the xml files, and the less ram DNN might consume. I'm OK with this as long as others who are much more familiar with the ins/outs of dnn's localization / resource file system to give it the final OK before we merge it into the platform. 

Can @erikvb or @donker or both take a look and just confirm that the format of the translation is acceptable? A good way to compare is to check the ignore-whitespace differences
https://github.com/dnnsoftware/Dnn.Platform/pull/2088/files/949102e3fe4a8d138becdc0ca5a05826cf3a8a35?utf8=%E2%9C%93&diff=unified&w=1

**Comment by perezandres** [comment]
No problem for me if I have to re-generate both files...

**Comment by donker** [comment]
My DNN Translator removes the schema junk from the resource file (why MS insists on including it in every f*cking resx file is beyond me). A schema is not necessary unless some software wishes to "validate" the XML. But DNN doesn't do that. It knows the format and loads the XML as it finds it.

**Comment by sleupold** [comment]
IMO all translations for the official languages (French, German, Italian, Dutch and Spanish) should be done or coordinated by the official translators, otherwise there is a risk of changes being applied forth and back during install and LP upgrade.

**Comment by perezandres** [comment]
That's a good point, Sebastian. Who's the coordinator for Spanish?

**Comment by sleupold** [comment]
@perezandres the Spanish translation is managed by @vmasanas (Vicenç Masanas)

**Comment by perezandres** [comment]
I've worked previously with Vicenç, translating DNN resources since version 6. I'll contact him for next contributions ;-)

**Comment by sleupold** [comment]
great, thanks a lot!

**Comment by valadas** [comment]
I do not know who are officially maintaining those languages, but if nobody maintains french, i offer myself.

**Comment by sleupold** [comment]
French is maintained by Benoît Sarton from BSI.fr

**Pull request merged**
