### PR TITLE
Tests a merge of the AdminExperience repository

### PR DESCRIPTION
**Pull request by valadas**
At this stage this is just to test merging the admin experience repository into the main repository, please do not merge yet.

### CODE REVIEW

**Comment by david-poindexter** [comment]
Tested locally and this looks really good for me - thanks @valadas!

**Comment by mitchelsellers** [comment]
I looked at this also, this looks great. 

Administrative question - do we squash merge this, or do we retain history?  (If not squashed, @valadas you are going to get a lot of internet points for this one!)

**Comment by valadas** [comment]
For people reviewing this, mainly looking for developer experience.

1. git clone -b pb-merge https://github.com/valadas/Dnn.Platform
2. open powershell as admin and run ./Build.ps1 -Target BuildAll
Let it build then verify the following

** Status should be clean **
`git status` should show nothing to commit (providing there was no build errors that stopped the buidl midway in which case, you should run `git reset --hard` and try again fixing what caused the error.

** You should have 4 zips in the Artifacts folder **
Try a clean install.
Try an upgrade.
Verify the Persona Bar works and gets 9.4.2 version

**Comment by mitchelsellers** [comment]
Per agreement with the Approvers group, I am merging this with a single approval as part of the Build Support processes.

**Pull request merged**
