### PR TITLE
DNN-6286: Performance issue in UriExtensions.IsLocalUri with DNS checks

### PR DESCRIPTION
**Pull request by bogdan-litescu**

### CODE REVIEW

**Comment by cnurse** [comment]
I am not 100% convinced that the behavior is the same, so I am leaving this for now.

**Comment by cathalconnolly** [comment]
agreed - it removes the functionality added in https://github.com/dnnsoftware/Dnn.Platform/commit/7834816fd4daeef2e76270482ff4f7c18ea994b9 which was added in response to https://dnntracker.atlassian.net/browse/DNN-3472

**Comment by bogdan-litescu** [comment]
Not only it removes, but it eliminates the need for it since there's no DNS
check to slow things down.
I don't understand why the DNS check is there. Do you know of some use
cases? Checking DNS is also very unreliable.

**Comment by jbrinkman** [comment]
So, maybe, rather than speculating it would be helpful to add some Unit Tests so that we can validate that behavior didn't change.  That will make it obvious whether we could safely accept this change.

**Comment by cathalconnolly** [comment]
that code was there from quite some time ago (I only added caching code in dnn-3472). Out of interest I checked the CDF codebase, and it appears that umbraco/cdf changed that check a while back so it no longer does a DNS check https://github.com/Shazwazza/ClientDependency/blob/5ed7ac24f37061c12f2db4140219a4eb1f8f8856/ClientDependency.Core/UriExtensions.cs

I'm going to assign this to myself and do some further testing

**Comment by jbrinkman** [comment]
This should be an easy win for Unit Tests.  That would document the behavior we expect.  We need to get in the habit of doing Unit Tests wherever possible. This is definitely one of the places where it is possible.

**Comment by cathalconnolly** [comment]
We feel that the upgrade to the latest CDF is better kept until 7.5.0 (to allow for additional testing), so I will be merging this change into 7.4.1

**Pull request merged**
