### PR TITLE
Update PersonaBar Manage/Roles to show Role ID

### PR DESCRIPTION
**Pull request by jeremy-farrance**
Fixes Issue #6153

## [Enhancement]: PersonaBar, Manage Roles - Add Role ID to Visible Information

This screenshot shows the result of these changes.
image

### CODE REVIEW

**Review by valadas — COMMENTED** [review]
Looks good but:
1. Could it maybe not be bolder than the reset, it stands out a bit much IMO.
2. The added props already existed but were not typed I guess, so it fixes warnings ?

**Comment by jeremy-farrance** [comment]
> Looks good but:
> 
> 1. Could it maybe not be bolder than the reset, it stands out a bit much IMO.
> 2. The added props already existed but were not typed I guess, so it fixes warnings ?

Agree on 1, updated/removed bolder from the label. For 2, yes, left them in because it was nice to see it compile with no warnings! :)

**Review by valadas — APPROVED** [review]
Awesome, thanks for the quick turnaround

**Review by david-poindexter — APPROVED** [review]
Looks good to me - thank you @jeremy-farrance 🎉

**Pull request merged**
